<template><div v-loading="loading">
  <el-breadcrumb separator="/" class="crumb"><el-breadcrumb-item to="/admin/reports">管理决策专题</el-breadcrumb-item><el-breadcrumb-item>课程质量与教学运行</el-breadcrumb-item></el-breadcrumb>
  <h2 class="sa-page-title">课程质量与教学运行</h2><p class="sa-page-sub">从跨学期课程结果识别持续异常、波动和影响面，并对照当前教学供给。</p>
  <el-alert type="info" :closable="false" show-icon title="课程结果不等于教学归因" :description="definition.boundary"/>
  <div class="filters"><el-select v-model="from" clearable placeholder="起始学期"><el-option v-for="s in data.semesters" :key="s" :label="s" :value="s"/></el-select><span>至</span><el-select v-model="to" clearable placeholder="结束学期"><el-option v-for="s in data.semesters" :key="s" :label="s" :value="s"/></el-select><el-button type="primary" @click="refresh">查询</el-button></div>
  <div class="kpis"><div v-for="x in kpis" :key="x.label" class="kpi"><span>{{x.label}}</span><b>{{x.value}}</b><small>{{x.note}}</small></div></div>
  <section class="sa-card"><div class="sa-card-title">重点核查课程 <span class="extra">按持续异常、影响面、波动和重修压力排序</span></div><el-table :data="data.courses" stripe><el-table-column prop="course_name" label="课程" min-width="190"/><el-table-column prop="observed_terms" label="可比学期" width="85"/><el-table-column prop="student_term_count" label="学生人次" width="85"/><el-table-column prop="failures" label="未通过" width="75"/><el-table-column label="未通过率" width="90"><template #default="{row}">{{row.fail_rate}}%</template></el-table-column><el-table-column label="波动" width="80"><template #default="{row}">{{row.volatility}}pp</template></el-table-column><el-table-column prop="retake_attempts" label="重修人次" width="85"/><el-table-column label="识别类型" width="120"><template #default="{row}"><el-tag :type="tagType(row.risk_type)">{{riskName[row.risk_type]}}</el-tag></template></el-table-column><el-table-column label="操作" width="90"><template #default="{row}"><el-button link type="primary" @click="selectCourse(row)">看趋势</el-button></template></el-table-column></el-table><el-pagination v-if="data.total" v-model:current-page="page" :page-size="50" :total="data.total" layout="total, prev, pager, next" @current-change="load"/></section>
  <div class="grid"><section class="sa-card"><div class="sa-card-title">{{selectedName||'重点课程'}}学期趋势</div><el-table :data="selectedTrends" size="small" max-height="360"><el-table-column prop="semester_id" label="学期"/><el-table-column prop="students" label="学生"/><el-table-column prop="avg_score" label="平均分"/><el-table-column label="未通过率"><template #default="{row}">{{row.fail_rate}}%</template></el-table-column><el-table-column prop="retake_attempts" label="重修"/></el-table></section><section class="sa-card"><div class="sa-card-title">当前已接入开课供给 TOP15</div><el-table :data="data.offerings" size="small" max-height="360"><el-table-column prop="course_name" label="课程" min-width="160"/><el-table-column prop="semester_id" label="学期" width="115"/><el-table-column prop="lesson_count" label="教学班"/><el-table-column prop="teacher_count" label="教师"/><el-table-column prop="enrolled" label="选课"/></el-table></section></div>
  <section class="sa-card definition"><div class="sa-card-title">识别口径</div><p>{{definition.sample}}</p><p><b>持续偏高：</b>{{definition.persistent_high}} <b>显著波动：</b>{{definition.volatile}}</p><p><b>影响面较广：</b>{{definition.wide_impact}} <b>重修压力：</b>{{definition.retake_pressure}}</p></section>
</div></template>
<script setup lang="ts">import{computed,onMounted,reactive,ref}from'vue';import{http}from'@/utils/http';const loading=ref(false),from=ref(''),to=ref(''),page=ref(1),selected=ref(''),selectedName=ref('');const data=reactive<any>({summary:{},courses:[],trends:[],offerings:[],semesters:[],total:0}),definition=reactive<any>({});const riskName:any={persistent_high:'持续偏高',volatile:'显著波动',wide_impact:'影响面较广',retake_pressure:'重修压力'};const kpis=computed(()=>[{label:'可比课程',value:data.summary.observed_courses||0,note:'满足最小样本'},{label:'总体未通过率',value:(data.summary.overall_fail_rate||0)+'%',note:(data.summary.attempts||0)+'条成绩'},{label:'持续偏高课程',value:data.summary.persistent_high_courses||0,note:'跨学期持续'},{label:'显著波动课程',value:data.summary.volatile_courses||0,note:'需核查口径与教学变化'},{label:'累计重修人次',value:data.summary.retake_attempts||0,note:'用于资源规划'}]);const selectedTrends=computed(()=>{const id=selected.value||data.courses[0]?.course_id;return data.trends.filter((x:any)=>x.course_id===id)});function tagType(s:string){return s==='persistent_high'?'danger':s==='wide_impact'?'warning':'info'}function selectCourse(r:any){selected.value=r.course_id;selectedName.value=r.course_name}function refresh(){page.value=1;load()}async function load(){loading.value=true;try{const q=new URLSearchParams({limit:'50',offset:String((page.value-1)*50),min_sample:'30'});if(from.value)q.set('semester_from',from.value);if(to.value)q.set('semester_to',to.value);const r=await http.get<any>('/v2/topics/course-quality?'+q);Object.assign(data,r);Object.assign(definition,r.definition);if(!selected.value&&r.courses?.length){selectCourse(r.courses[0])}}finally{loading.value=false}}onMounted(load)</script>
<style scoped>.crumb{margin-bottom:8px}.filters{display:flex;gap:10px;align-items:center;margin:14px 0}.filters .el-select{width:165px}.kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:14px}.kpi{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:15px}.kpi span,.kpi small{display:block;color:#64748b}.kpi b{display:block;font-size:25px;margin:6px 0}.sa-card{margin-bottom:14px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.definition p{font-size:13px;color:#475569;line-height:1.8}.el-pagination{justify-content:flex-end;margin-top:12px}@media(max-width:1100px){.kpis{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}}</style>
