<template><div>
  <el-breadcrumb separator="/" class="crumb"><el-breadcrumb-item to="/admin/reports">管理决策专题</el-breadcrumb-item><el-breadcrumb-item>学业风险与低年级受挫</el-breadcrumb-item></el-breadcrumb>
  <h2 class="sa-page-title">学业风险与低年级受挫</h2><p class="sa-page-sub">从大一首次出现未通过记录开始，观察后续变化并定位需要优先核查的课程、专业和学生。</p>
  <el-alert type="info" :closable="false" show-icon title="群体筛查不等于个人原因判断" :description="definition.boundary"/>
  <div class="filters"><el-select v-model="draftGrade" clearable placeholder="全部入学年级"><el-option v-for="x in grades" :key="x" :label="x+'级'" :value="x"/></el-select><el-button type="primary" :loading="loading" @click="applyFilter">应用筛选</el-button><el-button :disabled="loading" @click="reset">重置</el-button><span>筛选条件不会自动触发整页刷新</span></div>
  <el-skeleton :loading="initialLoading" animated :rows="4"><div class="kpis"><div v-for="x in kpis" :key="x.label" class="kpi"><span>{{x.label}} <el-tooltip :content="x.help"><i>?</i></el-tooltip></span><b>{{x.value}}</b><small>{{x.note}}</small></div></div></el-skeleton>
  <section class="sa-card insight"><div class="sa-card-title">管理员可以如何使用这些结果</div><p>{{definition.management_value}}</p><div class="actions"><span>人数高：评估帮扶资源规模</span><span>比例高：核查群体性课程衔接</span><span>持续人数高：优先查看学生成长档案</span><span>近期改善：避免持续贴标签</span></div></section>
  <div class="grid">
    <section class="sa-card" v-loading="loading"><div class="sa-card-title">各年级大一未通过情况 <span class="extra">不同年级观察时长不同，不直接排名优劣</span></div><el-table :data="data.by_grade" size="small"><el-table-column prop="entry_grade" label="入学年级"/><el-table-column prop="eligible_students" label="观察学生数"/><el-table-column prop="setback_students" label="大一有未通过学生数"/><el-table-column label="占观察学生比例"><template #default="{row}">{{rate(row.setback_students,row.eligible_students)}}%</template></el-table-column><el-table-column prop="persistent_students" label="后续持续学生数"/><el-table-column prop="improved_students" label="后续未再出现未通过"/></el-table></section>
    <section class="sa-card" v-loading="loading"><div class="sa-card-title">大一未通过学生集中的课程 TOP10</div><el-table :data="data.courses" size="small"><el-table-column prop="course_name" label="课程" min-width="180" show-overflow-tooltip/><el-table-column prop="affected_students" label="未通过学生数"/><el-table-column prop="failed_attempts" label="未通过成绩记录数"/></el-table><p class="foot">学生数为去重人数；成绩记录数可能包含同一学生的多次记录。</p></section>
  </div>
  <section class="sa-card" v-loading="loading"><div class="sa-card-title">专业关注优先级 <span class="extra">按后续持续人数、再按大一未通过人数排序</span></div><el-table :data="data.by_major" size="small"><el-table-column prop="major_name" label="专业" min-width="180"/><el-table-column prop="eligible_students" label="观察学生数"/><el-table-column prop="setback_students" label="大一有未通过学生数"/><el-table-column label="大一未通过比例"><template #default="{row}">{{rate(row.setback_students,row.eligible_students)}}%</template></el-table-column><el-table-column prop="persistent_students" label="后续持续学生数"/><el-table-column prop="improved_students" label="后续未再出现未通过"/></el-table></section>
  <section class="sa-card" v-loading="loading"><div class="sa-card-title">学生核查名单 <span class="extra">只提供证据与关注顺序，不自动建立处置任务</span></div><el-table :data="data.students" stripe><el-table-column prop="student_id" label="学号" width="130"/><el-table-column prop="display_name" label="姓名" width="90"/><el-table-column prop="major_name" label="专业" min-width="150"/><el-table-column prop="entry_grade" label="年级" width="70"/><el-table-column prop="first_setback_semester" label="首次未通过学期" width="125"/><el-table-column prop="first_year_failures" label="大一未通过记录"/><el-table-column prop="later_failures" label="后续未通过记录"/><el-table-column label="当前观察状态" width="145"><template #default="{row}"><el-tag :type="tagType(row.recovery_status)">{{statusName[row.recovery_status]}}</el-tag></template></el-table-column><el-table-column label="操作" width="90" fixed="right"><template #default="{row}"><el-button link type="primary" @click="student(row)">成长档案</el-button></template></el-table-column></el-table><el-pagination v-if="data.total" v-model:current-page="page" :page-size="50" :total="data.total" layout="total, prev, pager, next" @current-change="load"/></section>
  <section class="sa-card definition"><div class="sa-card-title">指标口径与管理含义</div><p><b>纳入观察：</b>{{definition.first_year}}</p><p><b>大一有未通过：</b>{{definition.setback}}</p><p><b>后续未再出现未通过：</b>{{definition.recovered}}</p><p><b>后续仍需观察：</b>{{definition.recovering}}</p><p><b>后续持续出现未通过：</b>{{definition.persistent}}</p><p><b>暂无后续成绩：</b>{{definition.pending_observation}}</p><p><b>统计单位：</b>{{definition.number_unit}}</p></section>
</div></template>
<script setup lang="ts">import{computed,onMounted,reactive,ref}from'vue';import{useRouter}from'vue-router';import{http}from'@/utils/http';const router=useRouter(),loading=ref(false),initialLoading=ref(true),draftGrade=ref<number>(),grade=ref<number>(),page=ref(1),requestId=ref(0);const data=reactive<any>({summary:{},by_grade:[],by_major:[],courses:[],students:[],total:0}),definition=reactive<any>({});const grades=computed(()=>data.by_grade.map((x:any)=>x.entry_grade));const statusName:any={recovered:'后续未再出现未通过',recovering:'后续仍需观察',persistent:'后续持续出现未通过',pending_observation:'暂无后续成绩'};const kpis=computed(()=>[{label:'纳入低年级观察',value:(data.summary.eligible_students||0)+' 人',note:'专题统计分母',help:definition.first_year||'有入学年和大一常规学期成绩的去重学生。'},{label:'大一有未通过课程',value:(data.summary.setback_students||0)+' 人',note:(data.summary.setback_students||0)+' / '+(data.summary.eligible_students||0)+' 人，'+(data.summary.setback_rate||0)+'%',help:definition.setback||''},{label:'后续未再出现未通过',value:(data.summary.recovered_students||0)+' 人',note:'避免持续贴风险标签',help:definition.recovered||''},{label:'后续持续出现未通过',value:(data.summary.persistent_students||0)+' 人',note:'优先核查成长轨迹',help:definition.persistent||''},{label:'暂无后续成绩',value:(data.summary.pending_students||0)+' 人',note:'下次成绩发布后复核',help:definition.pending_observation||''}]);function rate(a:number,b:number){return b?Math.round(a*1000/b)/10:0}function tagType(s:string){return s==='persistent'?'danger':s==='recovered'?'success':s==='recovering'?'warning':'info'}function applyFilter(){grade.value=draftGrade.value;page.value=1;load()}function reset(){draftGrade.value=undefined;grade.value=undefined;page.value=1;load()}async function load(){const id=++requestId.value;loading.value=true;try{const q=new URLSearchParams({limit:'50',offset:String((page.value-1)*50)});if(grade.value)q.set('entry_grade',String(grade.value));const r=await http.get<any>('/v2/topics/early-setback?'+q);if(id!==requestId.value)return;Object.assign(data,r);Object.assign(definition,r.definition)}finally{if(id===requestId.value){loading.value=false;initialLoading.value=false}}}function student(row:any){router.push({path:'/admin/student/'+row.student_id,query:{returnTo:'/admin/reports/early-setback',returnLabel:'低年级受挫专题'}})}onMounted(load)</script>
<style scoped>.crumb{margin-bottom:8px}.filters{display:flex;gap:10px;align-items:center;margin:14px 0}.filters .el-select{width:180px}.filters span,.foot{font-size:12px;color:#94a3b8}.kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:14px}.kpi{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:15px}.kpi span,.kpi small{display:block;color:#64748b}.kpi b{display:block;font-size:24px;margin:6px 0}.kpi i{display:inline-flex;align-items:center;justify-content:center;width:16px;height:16px;border-radius:50%;background:#e2e8f0;font-style:normal;cursor:help}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.sa-card{margin-bottom:14px}.insight p,.definition p{font-size:13px;color:#475569;line-height:1.8}.actions{display:flex;gap:8px;flex-wrap:wrap}.actions span{background:#f1f5f9;padding:6px 10px;border-radius:6px;font-size:12px;color:#475569}.el-pagination{justify-content:flex-end;margin-top:12px}@media(max-width:1100px){.kpis{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}}</style>
