<template>
  <div>
    <el-breadcrumb separator="/" class="crumb"><el-breadcrumb-item to="/admin/reports">管理决策专题</el-breadcrumb-item><el-breadcrumb-item>毕业准备核查与课程保障</el-breadcrumb-item></el-breadcrumb>
    <h2 class="sa-page-title">毕业准备核查与课程保障</h2>
    <p class="sa-page-sub">面向教务处和学院定位毕业准备中的学生课程缺口，并核查阻塞课程的开课、师资、重修与替代资源。</p>
    <el-alert type="warning" :closable="false" show-icon title="本页是毕业审核准备工具，不是毕业审核结论" :description="definition.boundary" />
    <el-alert class="scope-alert" type="info" :closable="false" show-icon title="管理口径分为明确问题与数据候选" description="“明确未通过”来自已发布的不及格成绩，可进入核查名单；“到期缺证据候选”仅表示当前没有结果记录，可能包含未选、免修认定未接入或方案课程并非个人实际应修，不能直接认定为缺修。" />
    <el-alert class="ai-entry-alert" type="success" :closable="false" show-icon title="AI 研判入口已收口到证据核查">
      <template #default>学生和课程列表只做管理分层，不再逐行生成 AI 评价。请先打开“核查证据”或“保障证据”；明确未通过、缺证据候选或高保障优先级对象，才会提供 AI 管理研判。</template>
    </el-alert>

    <div class="filters">
      <el-select v-model="draftStatus" clearable placeholder="全部学生"><el-option label="高年级重点核查" value="high_grade_action"/><el-option label="有必修课未通过" value="action_required"/><el-option label="到期缺证据候选（待核验）" value="verification_required"/><el-option label="当前未发现明显缺口" value="evidence_complete"/></el-select>
      <el-button type="primary" :loading="loading" @click="applyFilter">应用筛选</el-button><el-button :disabled="loading" @click="reset">重置</el-button>
      <span class="hint">选择条件后点击“应用筛选”，页面不会自动反复刷新</span>
    </div>

    <el-skeleton :loading="initialLoading" animated :rows="4">
      <div class="kpis"><div v-for="x in kpis" :key="x.label" class="kpi" :class="{action:!!x.filter}" @click="useKpi(x)"><span>{{x.label}} <el-tooltip :content="x.help"><el-icon class="help"><InfoFilled/></el-icon></el-tooltip></span><b>{{x.value}}</b><small>{{x.note}}</small><el-button v-if="x.filter" link type="primary">查看核查名单 →</el-button><em v-else>说明性指标</em></div></div>
    </el-skeleton>

    <div class="grid">
      <section class="sa-card" v-loading="loading"><div class="sa-card-title">各专业毕业准备核查概览 <span class="extra">表中均为去重学生人数，不是成绩条数</span></div>
        <el-table :data="data.majors" size="small" max-height="420"><el-table-column prop="major_name" label="专业" min-width="150" show-overflow-tooltip/><el-table-column prop="students" label="覆盖学生" width="85"/><el-table-column label="必修完成率" width="105"><template #default="{row}">{{row.avg_completion_rate}}%</template></el-table-column><el-table-column prop="failed_students" label="明确未通过" width="100"/><el-table-column prop="verification_students" label="缺证据候选" width="100"/><el-table-column label="操作" width="105" fixed="right"><template #default="{row}"><el-button link type="primary" @click="inspectMajor(row)">核查本专业</el-button></template></el-table-column></el-table>
      </section>
      <section class="sa-card" v-loading="loading"><div class="sa-card-title">需要优先核查的必修课程 <span class="extra">数字表示涉及该课程的去重学生数</span></div>
        <el-table :data="data.courses" size="small" max-height="420"><el-table-column prop="course_name" label="课程" min-width="160" show-overflow-tooltip/><el-table-column prop="failed_students" label="明确未通过学生" width="120"/><el-table-column prop="major_count" label="涉及专业" width="80"/><el-table-column prop="lesson_count" label="教学班" width="70"/><el-table-column prop="teacher_count" label="教师" width="60"/><el-table-column label="管理关注" width="95"><template #default="{row}"><el-tag :type="row.supply_priority==='高'?'danger':row.supply_priority==='中'?'warning':'info'">{{row.supply_priority==='高'?'AI重点':row.supply_priority==='中'?'需核查':'常规'}}</el-tag></template></el-table-column><el-table-column label="核查原因" min-width="180"><template #default="{row}">{{(row.supply_reasons||[]).join('；')||'常规观察'}}</template></el-table-column><el-table-column label="操作" width="95" fixed="right"><template #default="{row}"><el-button link type="primary" @click="openSupply(row)">保障证据</el-button></template></el-table-column></el-table>
      </section>
    </div>

    <div v-if="activeMajor" class="scope-bar" style="display:flex;align-items:center;justify-content:space-between;gap:16px;margin:0 0 14px;padding:12px 14px;border:1px solid #c7d2fe;border-radius:9px;background:#eef2ff"><div><b>当前核查范围：</b><el-tag type="primary" effect="light">{{activeMajorName}}</el-tag><span>下方名单仅显示该专业符合当前核查类型的学生</span></div><el-button type="primary" plain size="small" @click="clearMajor">清除专业条件，返回全部专业</el-button></div>

    <section class="sa-card" v-loading="loading"><div class="sa-card-title">学生核查名单 <span class="extra">逐人查看课程级证据</span></div>
      <el-table :data="data.students" stripe><el-table-column prop="student_id" label="学号" width="130"/><el-table-column prop="display_name" label="姓名" width="90"/><el-table-column prop="major_name" label="专业" min-width="145"/><el-table-column prop="entry_grade" label="年级" width="70"/><el-table-column label="必修完成" width="100"><template #default="{row}">{{row.required_completed}} / {{row.required_courses}}</template></el-table-column><el-table-column prop="explicit_required_failures" label="明确未通过" width="100"/><el-table-column prop="due_required_gaps" label="缺结果记录候选" width="120"/><el-table-column label="管理关注" width="100"><template #default="{row}"><el-tag :type="row.explicit_required_failures?'danger':row.due_required_gaps?'warning':'info'">{{row.explicit_required_failures?'明确处理':row.due_required_gaps?'优先核验':'常规'}}</el-tag></template></el-table-column><el-table-column label="本行核查重点" min-width="220"><template #default="{row}"><span v-if="row.explicit_required_failures">{{row.explicit_required_failures}}门必修课有明确未通过成绩，优先核对重修与开课资源</span><span v-else-if="row.due_required_gaps">{{row.due_required_gaps}}门课程到建议学期仍缺结果记录，先核对选课与认定</span><span v-else>当前未发现明确课程问题</span></template></el-table-column><el-table-column label="操作" width="95" fixed="right"><template #default="{row}"><el-button link type="primary" @click="student(row)">核查证据</el-button></template></el-table-column></el-table>
      <el-pagination v-if="data.total" v-model:current-page="page" :page-size="50" :total="data.total" layout="total, prev, pager, next" @current-change="load"/>
    </section>

    <section class="sa-card definition"><div class="sa-card-title">指标口径与管理动作</div><p><b>方案覆盖可核查学生：</b>已关联到培养方案且生成学生—课程状态的去重学生。管理用途是判断本专题覆盖面，不代表学生总数。</p><p><b>高年级明确未通过：</b>{{definition.high_grade_attention}} 管理动作是优先确认补考、重修、替代课程和开课资源。</p><p><b>全部年级明确未通过：</b>{{definition.action_required}} 管理动作是按专业和课程识别共性瓶颈。</p><p><b>到期缺证据候选：</b>{{definition.verification_required}} 该指标只用于补充数据核验，不直接形成学生处理结论。</p><p><b>必修完成率：</b>{{definition.completion_rate}}</p><p><b>课程保障优先级：</b>{{definition.supply_priority}}</p><p><b>统计单位：</b>{{definition.number_unit}}</p></section>

    <el-dialog v-model="studentVisible" :title="studentEvidence.student?.display_name ? studentEvidence.student.display_name+'：毕业准备核查证据' : '毕业准备核查证据'" width="900px">
      <el-alert type="warning" :closable="false" title="核查边界" :description="studentEvidence.boundary"/>
      <el-descriptions class="dialog-block" :column="4" border><el-descriptions-item label="学号">{{studentEvidence.student?.student_id}}</el-descriptions-item><el-descriptions-item label="年级">{{studentEvidence.student?.entry_grade}}</el-descriptions-item><el-descriptions-item label="专业">{{studentEvidence.student?.major_name}}</el-descriptions-item><el-descriptions-item label="培养方案">{{studentEvidence.student?.plan_name}}</el-descriptions-item><el-descriptions-item label="明确未通过">{{studentEvidence.summary?.failed_courses||0}} 门</el-descriptions-item><el-descriptions-item label="缺结果候选">{{studentEvidence.summary?.candidate_courses||0}} 门</el-descriptions-item><el-descriptions-item label="无开课证据">{{studentEvidence.summary?.courses_without_offering||0}} 门</el-descriptions-item><el-descriptions-item label="有替代证据">{{studentEvidence.summary?.courses_with_substitution||0}} 门</el-descriptions-item></el-descriptions>
      <div class="dialog-actions"><span v-if="!selectedStudentNeedsAi" class="dialog-note">当前未发现需由 AI 进一步归纳的课程缺口。</span><el-button v-else type="primary" plain @click="openStudentAi({student_id:studentEvidence.student?.student_id})">查看 AI 管理研判</el-button></div>
      <h4>一、明确未通过课程（可直接进入管理核查）</h4><el-table :data="studentEvidence.failed_courses||[]" size="small"><el-table-column prop="course_name" label="课程" min-width="150"/><el-table-column prop="effective_score" label="成绩" width="70"/><el-table-column prop="last_semester" label="最近学期" width="110"/><el-table-column prop="lesson_count" label="历史教学班" width="95"/><el-table-column prop="substitution_count" label="替代关系" width="85"/><el-table-column prop="reason" label="为什么核查" min-width="280"/></el-table>
      <h4>二、缺结果记录候选（必须先核验数据）</h4><el-table :data="studentEvidence.candidate_courses||[]" size="small" max-height="240"><el-table-column prop="course_name" label="课程" min-width="150"/><el-table-column prop="suggested_term" label="建议学期" width="85"/><el-table-column prop="lesson_count" label="历史教学班" width="95"/><el-table-column prop="reason" label="为什么核查" min-width="330"/></el-table>
    </el-dialog>

    <el-dialog v-model="supplyVisible" :title="supply.course?.courseName ? supply.course.courseName+'：课程保障证据' : '课程保障证据'" width="860px">
      <el-descriptions :column="3" border><el-descriptions-item label="明确未通过">{{supply.affected?.actionRequiredStudents||0}} 人</el-descriptions-item><el-descriptions-item label="缺证据候选">{{supply.affected?.verificationStudents||0}} 人</el-descriptions-item><el-descriptions-item label="涉及专业">{{supply.affected?.affectedMajors||0}} 个</el-descriptions-item><el-descriptions-item label="历史开课">{{supply.offerings?.length||0}} 个学期</el-descriptions-item><el-descriptions-item label="替代关系">{{supply.substitutions?.length||0}} 条</el-descriptions-item><el-descriptions-item label="未来开课计划">{{supply.availability?.hasFuturePlanEvidence?'已有证据':'暂无证据'}}</el-descriptions-item></el-descriptions>
      <div class="dialog-actions"><span v-if="!selectedCourseNeedsAi" class="dialog-note">当前课程为常规保障观察，不生成 AI 研判。</span><el-button v-else type="primary" plain @click="openCourseAi({courseId:supply.course?.courseId})">查看 AI 课程保障研判</el-button></div>
      <el-alert class="dialog-alert" type="info" :closable="false" title="证据边界" :description="supply.boundary||'结合下一学期开课计划、教师容量、重修班和课程替代规则，确认是否需要增加课程资源。'"/>
      <el-table :data="supply.offerings||[]" size="small" max-height="250"><el-table-column prop="semesterId" label="学期" width="120"/><el-table-column prop="lessonCount" label="教学班" width="85"/><el-table-column prop="teacherCount" label="教师" width="75"/><el-table-column prop="capacity" label="容量" width="80"/><el-table-column prop="enrolled" label="已选人数" width="90"/><el-table-column prop="schedules" label="排课时段" min-width="180" show-overflow-tooltip/></el-table>
      <h4>受该课程影响的学生</h4><el-table :data="supplyStudents" size="small" max-height="220"><el-table-column prop="studentId" label="学号" width="130"/><el-table-column prop="name" label="姓名" width="90"/><el-table-column prop="majorName" label="专业" min-width="150"/><el-table-column prop="failedRequired" label="明确未通过" width="100"/><el-table-column prop="verificationRequired" label="缺证据候选" width="110"/><el-table-column label="操作" width="90"><template #default="{row}"><el-button link type="primary" @click="student({student_id:row.studentId})">核查学生</el-button></template></el-table-column></el-table>
    </el-dialog>
    <AIInsightDrawer v-model="aiDrawerVisible" :insight="aiInsight" :loading="aiLoading" title="毕业准备AI研判" />
  </div>
</template>
<script setup lang="ts">
import{computed,onMounted,reactive,ref}from'vue';import{InfoFilled}from'@element-plus/icons-vue';import{http}from'@/utils/http';import{getGraduationCourseAIInsight,getGraduationStudentAIInsight}from'@/utils/ai';import AIInsightDrawer from'@/components/AIInsightDrawer.vue'
const loading=ref(false),initialLoading=ref(true),draftStatus=ref('high_grade_action'),status=ref('high_grade_action'),page=ref(1),requestId=ref(0),supplyVisible=ref(false),studentVisible=ref(false),activeMajor=ref(''),activeMajorName=ref('')
const aiDrawerVisible=ref(false),aiLoading=ref(false),aiInsight=ref<any>(null)
const data=reactive<any>({summary:{},majors:[],courses:[],students:[],total:0}),definition=reactive<any>({})
const supply=reactive<any>({}),studentEvidence=reactive<any>({}),supplyStudents=ref<any[]>([]),selectedStudentRow=ref<any>(null),selectedSupplyRow=ref<any>(null)
const selectedStudentNeedsAi=computed(()=>Number(studentEvidence.summary?.failed_courses||0)>0||Number(studentEvidence.summary?.candidate_courses||0)>0)
const selectedCourseNeedsAi=computed(()=>selectedSupplyRow.value?.supply_priority==='高')
const statusName:any={action_required:'存在明确未通过课程',verification_required:'存在到期缺记录课程',evidence_complete:'当前未发现明显缺口'}
const kpis=computed(()=>[{label:'方案覆盖可核查学生',value:(data.summary.covered_students||0)+' 人',note:(data.summary.plan_count||0)+' 个培养方案；仅表示数据覆盖',help:'已关联培养方案并生成课程状态的去重学生人数，不是管理问题人数。'},{label:'高年级明确未通过',value:(data.summary.high_grade_attention_students||0)+' 人',note:'优先核查重修与开课保障',help:definition.high_grade_attention||'',filter:'high_grade_action'},{label:'全部年级明确未通过',value:(data.summary.action_required_students||0)+' 人',note:(data.summary.explicit_required_failures||0)+' 条学生－必修课记录',help:definition.action_required||'',filter:'action_required'},{label:'到期缺证据候选',value:(data.summary.verification_students||0)+' 人',note:'先核验选课与认定数据',help:definition.verification_required||'',filter:'verification_required'},{label:'未发现明确问题',value:(data.summary.evidence_complete_students||0)+' 人',note:'边界指标，不等同审核通过',help:definition.evidence_complete||''}])
function tagType(s:string){return s==='action_required'?'danger':s==='verification_required'?'warning':'success'}
function applyFilter(){status.value=draftStatus.value;page.value=1;load()}function reset(){draftStatus.value='high_grade_action';status.value='high_grade_action';activeMajor.value='';activeMajorName.value='';page.value=1;load()}
function useKpi(x:any){if(!x.filter)return;draftStatus.value=x.filter;status.value=x.filter;page.value=1;load()}
function inspectMajor(row:any){if(activeMajor.value===row.major_code){clearMajor();return}activeMajor.value=row.major_code;activeMajorName.value=row.major_name;page.value=1;load()}
function clearMajor(){activeMajor.value='';activeMajorName.value='';page.value=1;load()}
async function load(){const id=++requestId.value;loading.value=true;try{const q=new URLSearchParams({limit:'50',offset:String((page.value-1)*50)});if(status.value)q.set('readiness',status.value);if(activeMajor.value)q.set('major_code',activeMajor.value);const r=await http.get<any>('/v2/topics/graduation-readiness?'+q);if(id!==requestId.value)return;Object.assign(data,r);Object.assign(definition,r.definition)}finally{if(id===requestId.value){loading.value=false;initialLoading.value=false}}}
async function student(row:any){selectedStudentRow.value=row;const r=await http.get<any>('/v2/topics/graduation-readiness/student/'+encodeURIComponent(row.student_id));Object.assign(studentEvidence,r);studentVisible.value=true}
async function openSupply(row:any){selectedSupplyRow.value=row;const id=encodeURIComponent(row.course_id);const [r,s]=await Promise.all([http.get<any>('/v2/curriculum/course-supply/'+id),http.get<any>('/v2/curriculum/management-students?course_id='+id+'&limit=100')]);Object.assign(supply,r);supplyStudents.value=s.items||[];supplyVisible.value=true}
async function openStudentAi(row:any){const sid=row.student_id||row.studentId;if(!sid)return;aiDrawerVisible.value=true;aiLoading.value=true;aiInsight.value=null;try{aiInsight.value=await getGraduationStudentAIInsight(sid)}finally{aiLoading.value=false}}
async function openCourseAi(row:any){const cid=row.course_id||row.courseId||supply.course?.courseId;if(!cid)return;aiDrawerVisible.value=true;aiLoading.value=true;aiInsight.value=null;try{aiInsight.value=await getGraduationCourseAIInsight(cid)}finally{aiLoading.value=false}}
onMounted(load)
</script>
<style scoped>.crumb{margin-bottom:8px}.ai-entry-alert{margin-top:10px}.filters{display:flex;gap:10px;align-items:center;margin:14px 0}.filters .el-select{width:220px}.hint{font-size:12px;color:#94a3b8}.kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:14px}.kpi{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:15px}.kpi span,.kpi small{display:block;color:#64748b}.kpi b{display:block;font-size:24px;margin:6px 0;color:#0f172a}.help{display:inline-flex!important;align-items:center;justify-content:center;width:16px;height:16px;border-radius:50%;background:#e2e8f0;color:#475569;font-size:11px;cursor:help}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.sa-card{margin-bottom:14px}.definition p{color:#475569;font-size:13px;line-height:1.8}.dialog-actions{display:flex;justify-content:flex-end;align-items:center;margin:10px 0}.dialog-note{margin-right:auto;color:#64748b;font-size:13px}.el-pagination{justify-content:flex-end;margin-top:12px}@media(max-width:1100px){.kpis{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}}</style>
