<template>
  <div v-loading="loading">
    <el-breadcrumb separator="/" class="crumb"><el-breadcrumb-item to="/admin/reports">管理决策专题</el-breadcrumb-item><el-breadcrumb-item>培养方案完成与毕业准备度</el-breadcrumb-item></el-breadcrumb>
    <h2 class="sa-page-title">培养方案完成与毕业准备度</h2><p class="sa-page-sub">区分明确未通过与尚无完成证据，支持课程资源核查和毕业审核准备。</p>
    <el-alert type="warning" :closable="false" show-icon title="准备度不是毕业结论" :description="definition.boundary" />
    <div class="filters"><el-select v-model="status" clearable placeholder="全部准备度状态" @change="filterChanged"><el-option label="明确需处理" value="action_required"/><el-option label="待核验候选缺口" value="verification_required"/><el-option label="必修证据完整" value="evidence_complete"/></el-select><el-button type="primary" @click="load">刷新专题</el-button></div>
    <div class="kpis"><div v-for="x in kpis" :key="x.label" class="kpi"><span>{{x.label}}</span><b>{{x.value}}</b><small>{{x.note}}</small></div></div>
    <div class="grid">
      <section class="sa-card"><div class="sa-card-title">专业准备度分布</div><el-table :data="data.majors" size="small" max-height="380"><el-table-column prop="major_name" label="专业" min-width="170" show-overflow-tooltip/><el-table-column prop="students" label="学生" width="65"/><el-table-column prop="avg_completion_rate" label="必修证据率" width="100"><template #default="{row}">{{row.avg_completion_rate}}%</template></el-table-column><el-table-column prop="action_required_students" label="明确需处理" width="95"/><el-table-column prop="candidate_required_gaps" label="候选缺口" width="85"/></el-table></section>
      <section class="sa-card"><div class="sa-card-title">必修课程缺口集中度</div><el-table :data="data.courses" size="small" max-height="380"><el-table-column prop="course_name" label="课程" min-width="180" show-overflow-tooltip/><el-table-column prop="explicit_failures" label="明确未通过" width="95"/><el-table-column prop="candidate_gaps" label="待核验" width="80"/></el-table></section>
    </div>
    <section class="sa-card"><div class="sa-card-title">方案模块缺口 <span class="extra">用于判断资源应优先投向哪些课程模块</span></div><el-table :data="data.modules" size="small"><el-table-column prop="module" label="模块" min-width="200"/><el-table-column prop="students" label="涉及学生"/><el-table-column prop="explicit_failures" label="明确未通过"/><el-table-column prop="candidate_gaps" label="待核验候选"/></el-table></section>
    <section class="sa-card"><div class="sa-card-title">学生准备度清单 <span class="extra">进入档案后可查看具体课程证据与角色化建议</span></div><el-table :data="data.students" stripe><el-table-column prop="student_id" label="学号" width="130"/><el-table-column prop="display_name" label="姓名" width="90"/><el-table-column prop="major_name" label="专业" min-width="150"/><el-table-column prop="entry_grade" label="年级" width="70"/><el-table-column label="必修完成证据" width="160"><template #default="{row}"><el-progress :percentage="row.completion_rate" :stroke-width="8"/></template></el-table-column><el-table-column prop="explicit_required_failures" label="明确未通过" width="95"/><el-table-column prop="candidate_required_gaps" label="待核验" width="80"/><el-table-column label="准备度" width="125"><template #default="{row}"><el-tag :type="tagType(row.readiness_status)">{{statusName[row.readiness_status]}}</el-tag></template></el-table-column><el-table-column label="操作" width="90" fixed="right"><template #default="{row}"><el-button link type="primary" @click="student(row)">查看档案</el-button></template></el-table-column></el-table><el-pagination v-if="data.total" v-model:current-page="page" :page-size="50" :total="data.total" layout="total, prev, pager, next" @current-change="load"/></section>
    <section class="sa-card definition"><div class="sa-card-title">口径解释</div><p><b>明确需处理：</b>{{definition.action_required}}</p><p><b>待核验候选缺口：</b>{{definition.verification_required}}</p><p><b>必修证据完整：</b>{{definition.evidence_complete}}</p><p><b>证据完成率：</b>{{definition.completion_rate}}</p></section>
  </div>
</template>
<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue'; import { useRouter } from 'vue-router'; import { http } from '@/utils/http'
const router=useRouter(),loading=ref(false),status=ref(''),page=ref(1); const data=reactive<any>({summary:{},majors:[],modules:[],courses:[],students:[],total:0}),definition=reactive<any>({})
const statusName:any={action_required:'明确需处理',verification_required:'待核验候选',evidence_complete:'必修证据完整'}
const kpis=computed(()=>[{label:'方案覆盖学生',value:data.summary.covered_students||0,note:(data.summary.plan_count||0)+'个培养方案'},{label:'平均必修证据率',value:(data.summary.avg_completion_rate||0)+'%',note:'选修候选池不进分母'},{label:'明确需处理学生',value:data.summary.action_required_students||0,note:(data.summary.explicit_required_failures||0)+'门必修未通过'},{label:'待核验学生',value:data.summary.verification_students||0,note:'不能直接称为漏选'},{label:'必修证据完整',value:data.summary.evidence_complete_students||0,note:'不等同毕业审核通过'}])
function tagType(s:string){return s==='action_required'?'danger':s==='verification_required'?'warning':'success'} function filterChanged(){page.value=1;load()}
async function load(){loading.value=true;try{const q=new URLSearchParams({limit:'50',offset:String((page.value-1)*50)});if(status.value)q.set('readiness',status.value);const r=await http.get<any>('/v2/topics/graduation-readiness?'+q);Object.assign(data,r);Object.assign(definition,r.definition)}finally{loading.value=false}}
function student(row:any){router.push({path:'/admin/student/'+row.student_id,query:{returnTo:'/admin/reports/graduation-readiness',returnLabel:'培养方案与毕业准备度专题'}})} onMounted(load)
</script>
<style scoped>
.crumb{margin-bottom:8px}.filters{display:flex;gap:10px;margin:14px 0}.filters .el-select{width:210px}.kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:14px}.kpi{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:15px}.kpi span,.kpi small{display:block;color:#64748b}.kpi b{display:block;font-size:25px;margin:6px 0;color:#0f172a}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.sa-card{margin-bottom:14px}.definition p{color:#475569;font-size:13px;line-height:1.8}.el-pagination{justify-content:flex-end;margin-top:12px}@media(max-width:1100px){.kpis{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}}
</style>
