<template>
  <div>
    <div class="head"><div><h2 class="sa-page-title">本科教学师资保障分析</h2><p class="sa-page-sub">从真实教学任务识别课程团队单点承担、任务集中和教授本科教学参与核查对象。</p></div><div class="filters"><el-select v-model="semester" placeholder="选择学期" @change="load"><el-option v-for="s in semesters" :key="s.value" :label="s.label" :value="s.value"/></el-select><el-select v-model="college" clearable filterable placeholder="全部学院" @change="load"><el-option v-for="x in colleges" :key="x.id" :label="x.name" :value="x.id"/></el-select></div></div>
    <el-alert type="warning" :closable="false" show-icon title="本页用于师资供给与课程团队核查，不用于教师个人评价" :description="definition.boundary"/>

    <div class="kpis">
      <div v-for="k in kpis" :key="k.label" class="kpi"><span>{{k.label}} <KpiLabel label="" :formula="k.help"/></span><b>{{k.value}}</b><small>{{k.note}}</small></div>
    </div>

    <section class="sa-card"><div class="sa-card-title">学院本科教学师资保障对比 <span class="extra">点击“核查学院”联动本页全部数据</span></div>
      <el-table :data="data.colleges" stripe size="small"><el-table-column prop="college_name" label="学院" min-width="160"/><el-table-column prop="courses" label="开课课程" width="90"/><el-table-column prop="lessons" label="教学班" width="80"/><el-table-column prop="enrolled" label="选课人次" width="95"/><el-table-column prop="single_teacher_courses" label="单点课程" width="90"/><el-table-column prop="high_impact_courses" label="高影响单点" width="105"><template #default="{row}"><el-tag :type="row.high_impact_courses?'danger':'success'">{{row.high_impact_courses}}</el-tag></template></el-table-column><el-table-column label="管理用途" min-width="210"><template #default="{row}">{{row.high_impact_courses?'优先核查高影响课程的备课与接续安排':row.single_teacher_courses?'核查单一教师课程的团队覆盖':'当前未发现单点课程'}}</template></el-table-column><el-table-column label="操作" width="100"><template #default="{row}"><el-button link type="primary" @click="inspectCollege(row)">核查学院</el-button></template></el-table-column></el-table>
      <div v-if="data.college" class="scope"><span>当前学院：<b>{{data.college}}</b></span><el-button link type="primary" @click="clearCollege">清除学院条件</el-button></div>
    </section>

    <section class="sa-card"><div class="sa-card-title">需要优先核查的课程团队 <span class="extra">风险来自当期授课覆盖和职称证据，不代表教师能力</span></div>
      <el-table :data="data.risk_courses" stripe><el-table-column prop="course_name" label="课程" min-width="180" show-overflow-tooltip/><el-table-column prop="college_name" label="开课学院" min-width="140"/><el-table-column prop="course_nature" label="课程性质" width="105"/><el-table-column prop="lesson_count" label="教学班" width="75"/><el-table-column prop="enrolled" label="选课人次" width="90"/><el-table-column prop="teacher_count" label="实际教师" width="85"/><el-table-column label="职称已知" width="90"><template #default="{row}">{{row.known_title_teachers}} / {{row.teacher_count}}</template></el-table-column><el-table-column label="优先级" width="80"><template #default="{row}"><el-tag :type="row.priority==='高'?'danger':'warning'">{{row.priority}}</el-tag></template></el-table-column><el-table-column label="为什么核查" min-width="260"><template #default="{row}">{{row.attention_reasons.join('；')}}</template></el-table-column><el-table-column label="操作" width="100" fixed="right"><template #default="{row}"><el-button link type="primary" @click="goTeam(row)">团队证据</el-button></template></el-table-column></el-table>
    </section>

    <section class="sa-card"><div class="sa-card-title">主讲教学任务集中教师 <span class="extra">按主讲教师字段的教学班数和选课人次排序；联合授课暂不拆分工作量</span></div>
      <el-table :data="data.teachers" size="small" stripe><el-table-column prop="teacher_name" label="教师" width="100"/><el-table-column prop="college_name" label="学院" min-width="150"/><el-table-column prop="title" label="职称" width="105"><template #default="{row}">{{row.title||'待补充'}}</template></el-table-column><el-table-column prop="course_count" label="课程数" width="85"/><el-table-column prop="lesson_count" label="教学班数" width="90"/><el-table-column prop="enrolled" label="覆盖选课人次" width="110"/><el-table-column label="核查说明" min-width="260"><template #default="{row}">核对是否为正常团队分工、合班记录或任务集中；不能据此直接认定超负荷</template></el-table-column><el-table-column label="操作" width="90"><template #default="{row}"><el-button link type="primary" @click="goTeacher(row)">教学档案</el-button></template></el-table-column></el-table>
    </section>

    <section class="sa-card explain"><div class="sa-card-title">指标口径与管理动作</div><p><b>单一教师覆盖课程：</b>{{definition.single_teacher_courses}} 管理动作是核查是否需要协同备课和接续教师。</p><p><b>高影响单点课程：</b>{{definition.high_impact_courses}} 管理动作是结合下一学期开课规模优先安排资源。</p><p><b>教授本科教学参与率：</b>{{definition.professor_participation}}</p><p><b>职称证据完整率：</b>{{definition.title_completeness}} 完整率不足时不形成职称梯队结论。</p><p><b>任务集中度：</b>{{definition.load_share}}</p></section>
  </div>
</template>

<script setup lang="ts">
import{computed,onMounted,reactive,ref}from'vue';import{useRouter}from'vue-router';import{http}from'@/utils/http';import{getFilterMeta,type SemesterOpt}from'@/utils/meta';import{COLLEGE_MAP}from'@/constants/colleges';import KpiLabel from'@/components/KpiLabel.vue'
const router=useRouter(),semester=ref(''),college=ref(''),semesters=ref<SemesterOpt[]>([]),loading=ref(false)
const colleges=Object.entries(COLLEGE_MAP).map(([id,name])=>({id,name})),data=reactive<any>({summary:{},colleges:[],risk_courses:[],teachers:[],college:''}),definition=reactive<any>({})
const fmt=(v:any,suffix='')=>v===null||v===undefined?'—':v+suffix
const kpis=computed(()=>[{label:'本科教学活跃教师',value:fmt(data.summary.active_teachers,' 人'),note:`覆盖 ${data.summary.courses||0} 门课程`,help:definition.active_teachers||''},{label:'单一教师覆盖课程',value:fmt(data.summary.single_teacher_courses,' 门'),note:'当期教学任务单点承担',help:definition.single_teacher_courses||''},{label:'高影响单点课程',value:fmt(data.summary.high_impact_courses,' 门'),note:'优先核查接续资源',help:definition.high_impact_courses||''},{label:'教授本科教学参与率',value:fmt(data.summary.professor_participation_rate,'%'),note:`${data.summary.professor_active||0} / ${data.summary.professor_total||0} 人`,help:definition.professor_participation||''},{label:'职称证据完整率',value:fmt(data.summary.title_completeness_rate,'%'),note:'决定能否分析职称梯队',help:definition.title_completeness||''},{label:'前10%主讲教师任务占比',value:fmt(data.summary.top10_load_share,'%'),note:'按主讲字段覆盖选课人次计算',help:definition.load_share||''}])
async function load(){loading.value=true;try{const q=new URLSearchParams();if(semester.value)q.set('semester',semester.value);if(college.value)q.set('college',college.value);const r=await http.get<any>('/admin/faculty/management-overview?'+q);Object.assign(data,r);Object.assign(definition,r.definition)}finally{loading.value=false}}
function inspectCollege(row:any){const match=colleges.find(x=>x.name===row.college_name);if(match){college.value=match.id;load()}}function clearCollege(){college.value='';load()}
function goTeam(row:any){router.push({path:'/admin/faculty/team',query:{courseId:row.course_id,courseName:row.course_name}})}function goTeacher(row:any){router.push('/admin/faculty/'+row.teacher_id)}
onMounted(async()=>{const meta=await getFilterMeta();semesters.value=(meta.semesters||[]).slice().reverse();semester.value=semesters.value[0]?.value||'';await load()})
</script>

<style scoped>.head{display:flex;justify-content:space-between;align-items:flex-start;gap:18px}.filters{display:flex;gap:10px}.filters .el-select{width:180px}.kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;margin:14px 0}.kpi{padding:14px;background:#fff;border:1px solid var(--sa-border);border-radius:10px}.kpi span,.kpi small{display:block;color:#64748b}.kpi b{display:block;margin:6px 0;font-size:23px;color:#0f172a}.sa-card{margin-bottom:14px}.scope{display:flex;justify-content:space-between;margin-top:10px;padding:9px 12px;background:#eef2ff;border-radius:8px;color:#475569}.explain p{font-size:13px;line-height:1.8;color:#475569}@media(max-width:1200px){.kpis{grid-template-columns:repeat(3,1fr)}}</style>
