/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIInsightDrawer: typeof import('./../../components/AIInsightDrawer.vue')['default']
    AppPagination: typeof import('./../../components/AppPagination.vue')['default']
    AppTable: typeof import('./../../components/AppTable.vue')['default']
    BusinessPageContext: typeof import('./../../components/BusinessPageContext.vue')['default']
    EChart: typeof import('./../../components/EChart.vue')['default']
    GradeCoursesDrawer: typeof import('./../../components/GradeCoursesDrawer.vue')['default']
    KpiCard: typeof import('./../../components/KpiCard.vue')['default']
    KpiLabel: typeof import('./../../components/KpiLabel.vue')['default']
    MajorAlertStudentsDialog: typeof import('./../../components/MajorAlertStudentsDialog.vue')['default']
    MetricHistoryDialog: typeof import('./../../components/MetricHistoryDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentEvidenceDrawer: typeof import('./../../components/StudentEvidenceDrawer.vue')['default']
  }
}
