<template>
  <aside v-show="panel" class="auxiliary-panel" aria-label="研究资料与个人意见" @keydown.esc.stop="$emit('close')">
    <header><nav aria-label="辅助内容"><button :class="{ active: panel === 'sources' }" @click="$emit('panel', 'sources')">相关资料</button><button :class="{ active: panel === 'opinion' }" @click="$emit('panel', 'opinion')">我的意见</button></nav><button class="close" aria-label="关闭辅助面板" @click="$emit('close')">关闭</button></header>
    <div v-show="panel === 'sources'" ref="sourceContent" class="panel-content">
      <p class="intro">查看本轮实际使用的资料，不以新版替代原依据。</p>
      <p v-if="sourceLoading" role="status">正在读取本轮资料……</p>
      <p v-if="sourceError" class="warning" role="alert">{{ sourceError }}</p>
      <template v-if="sources && !sourceLoading">
        <p v-if="sourceResult" class="source-scope">{{ sourceResult.title }}<br>{{ sourceResult.scope_label }}<br>{{ sourceResult.data_time_note }} {{ researchDate(sourceResult.data_time) }}</p>
        <section v-for="table in sources.tables.filter(t => t.id === sourceTarget)" :key="table.id" :data-source-target="table.id"><h3>{{ table.title }}</h3><p class="intro">{{ table.note }}</p><p v-if="!table.rows.length">本轮范围内没有对应记录，不能据此认定培养内容完全不同。</p><article v-for="(row, i) in table.rows.slice(0, 50)" :key="i"><p v-for="column in table.columns" :key="column.key">{{ column.label }}：{{ row[column.key] ?? '未提供' }}</p></article><p v-if="table.rows.length > 50" class="intro">此处显示前50项，完整清单可在对应讨论结果展开。</p></section>
        <section v-for="doc in sources.documents || []" :key="doc.plan + doc.file" data-source-target="documents"><h3>{{ doc.plan }}</h3><p class="file-name">{{ doc.file }}</p><p class="intro">{{ doc.basis }}</p><p v-for="issue in doc.issues || []" :key="issue" class="warning">{{ issue }}</p>
          <details v-for="(part, i) in doc.sections" :key="i" :open="i === 0"><summary>{{ part.title }}</summary><p class="original">{{ part.text || '这部分原文尚未提供。' }}</p><button v-if="part.text" class="link" @click="$emit('pin', doc.plan + ' · ' + part.title, part.text.slice(0, 1200))">固定这一段到意见旁</button><small v-if="part.text.length > 1200">固定前1200字；完整原文仍在本页。</small></details>
        </section>
        <details v-if="sources.methods?.length" class="source-methods"><summary>计算方法与口径</summary><article v-for="(method, i) in sources.methods" :key="i"><p class="original">{{ method }}</p><button class="link" @click="$emit('pin', '本轮计算方法', method)">固定到意见旁</button></article></details>
        <section v-if="sources.sources?.length"><h3>资料来源</h3><article v-for="source in sources.sources" :key="source.file"><b>{{ source.file }}</b><p>{{ source.detail || '本轮留存的资料来源。' }}</p></article></section>
        <p v-if="!sources.documents?.length && !sources.methods?.length && !sources.sources?.length" class="intro">本轮未提供可展示的原文和计算记录。不能据此补造来源。</p>
      </template>
      <p v-if="!sources && !sourceLoading && !sourceError" class="intro">从分析中的“查看本轮资料”进入具体来源。</p>
    </div>
    <div v-show="panel === 'opinion'" class="panel-content opinion-content">
      <p class="intro">写下自己的判断。新分析和新资料不会改写这里的文字。</p>
      <div class="save-state" :class="{ warning: ['error','conflict'].includes(saveState) }" role="status">{{ stateLabel }}<button v-if="['dirty','error'].includes(saveState)" class="link" @click="$emit('save')">立即保存</button></div>
      <p v-if="saveError" class="warning">{{ saveError }}</p>
      <label for="research-personal-opinion" class="sr-only">我的意见</label>
      <textarea id="research-personal-opinion" ref="editor" :value="text" rows="13" placeholder="例如：我更关注两个专业在实践训练中的差异……" @input="$emit('update:text', ($event.target as HTMLTextAreaElement).value)" @blur="$emit('save')" @select="rememberSelection" />
      <div v-if="conflict" class="conflict" role="alert"><b>这份意见已在其他窗口更新</b><p>你的文字保留在上方，可手动合并。保存为新版本前，请比较另一份内容。</p><label>另一窗口已保存内容<textarea :value="conflict.text" rows="7" readonly /></label><div class="actions"><button @click="$emit('resolve', false)">保存我的文字为新版本</button><button @click="$emit('resolve', true)">采用另一份内容</button></div></div>
      <section v-if="excerpt" class="pinned"><div class="pinned-title"><h3>固定参考摘录</h3><button class="link" @click="$emit('unpin')">移除</button></div><b>{{ excerpt.title }}</b><p class="original">{{ excerpt.text }}</p><button class="link" @click="$emit('full-source', excerpt.resultId)">查看完整资料</button></section>
      <details class="versions" @toggle="($event.target as HTMLDetailsElement).open && $emit('versions')"><summary>查看已保存版本</summary><div v-for="version in versions" :key="version.revision"><b>版本{{ version.revision }} · {{ researchDate(version.saved_at) }}</b><p>{{ version.text }}</p><button class="link" @click="$emit('restore', version.text)">预览恢复为新版本</button></div><p v-if="!versions.length" class="intro">暂无其他可读取版本。</p></details>
      <p v-if="saveState === 'error'" class="footnote">暂未保存的文字请先复制保留，再重试保存。</p>
    </div>
  </aside>
</template>
<script setup lang="ts">
import { computed, nextTick, ref, watch } from 'vue'
import type { ResearchResult, ResearchSources, SavedText } from '@/utils/expertResearch'
import { researchDate } from '@/utils/expertResearch'
import type { ReferenceExcerpt } from './useResearchWorkspace'
const props = defineProps<{ panel: 'sources' | 'opinion' | null; sources: ResearchSources | null; sourceResult: ResearchResult | null; sourceLoading: boolean; sourceError: string; sourceTarget?: string; text: string; saveState: string; savedAt?: string; saveError: string; conflict: SavedText | null; excerpt: ReferenceExcerpt | null; versions: SavedText[] }>()
defineEmits<{ panel: [value: 'sources' | 'opinion']; close: []; pin: [title: string, text: string]; unpin: []; 'full-source': [resultId: string]; 'update:text': [text: string]; save: []; resolve: [useRemote: boolean]; versions: []; restore: [text: string] }>()
const editor = ref<HTMLTextAreaElement>(), selection = ref({ start: 0, end: 0, scroll: 0 })
const stateLabel = computed(() => (({ saved: props.savedAt ? `已保存 · ${researchDate(props.savedAt)}` : '已保存', dirty: '有修改，等待保存', saving: '正在保存', error: '暂未保存', conflict: '存在另一份已保存内容' } as Record<string, string>)[props.saveState] || '保存状态待确认'))
const sourceContent = ref<HTMLElement>()
watch(() => [props.sourceTarget, props.sources, props.sourceLoading], async () => { if (props.sourceLoading || !props.sourceTarget) return; await nextTick(); const element = Array.from(sourceContent.value?.querySelectorAll<HTMLElement>('[data-source-target]') || []).find(el => el.dataset.sourceTarget === props.sourceTarget); if (element && sourceContent.value) sourceContent.value.scrollTop += element.getBoundingClientRect().top - sourceContent.value.getBoundingClientRect().top - 12 })
function rememberSelection() { if (editor.value) selection.value = { start: editor.value.selectionStart, end: editor.value.selectionEnd, scroll: editor.value.scrollTop } }
watch(() => props.panel, async panel => { if (panel === 'opinion') { await nextTick(); if (editor.value) { editor.value.setSelectionRange(selection.value.start, selection.value.end); editor.value.scrollTop = selection.value.scroll } } else rememberSelection() })
</script>
<style scoped>
.auxiliary-panel{width:360px;min-width:360px;background:#fff;border-left:1px solid #e6e7ef;display:flex;flex-direction:column;min-height:0;height:100%;z-index:20}.auxiliary-panel header{display:flex;align-items:center;justify-content:space-between;padding:17px 18px;border-bottom:1px solid #eaeaf0;gap:10px}.auxiliary-panel nav{display:flex;gap:17px}.auxiliary-panel nav button{border:0;border-bottom:2px solid transparent;background:none;padding:4px 0 8px;color:#777e8e;font:inherit;font-size:14px;cursor:pointer}.auxiliary-panel nav button.active{border-color:#725caf;color:#584396}.close{border:0;background:none;color:#858b98;font-size:12px;cursor:pointer}.panel-content{overflow:auto;padding:20px;min-height:0;font-size:14px;line-height:1.8;flex:1}.intro,.footnote{font-size:12px;color:#7b8394;line-height:1.9;margin-top:0}.source-scope{font-size:12px;color:#757382;background:#f8f7fb;padding:12px;border-radius:7px}.panel-content section{margin:22px 0}.panel-content h3{font-size:14px;color:#41465a;font-weight:600;margin:0 0 10px}.panel-content article{border-bottom:1px solid #eeeef4;padding:12px 0;font-size:12px;overflow-wrap:anywhere}.original{white-space:pre-wrap;font-size:13px;line-height:1.9;overflow-wrap:anywhere}.file-name{font-size:12px;overflow-wrap:anywhere;color:#7e8592}details{margin:14px 0;font-size:13px}summary{cursor:pointer;color:#555970}.link{border:0;background:none;padding:4px 0;color:#6a579e;font:inherit;font-size:12px;cursor:pointer}.save-state{font-size:12px;color:#75856f;display:flex;gap:12px;align-items:center;margin-bottom:10px}.warning{background:#fff8e9;color:#856934;padding:10px;border-radius:5px;font-size:12px}.opinion-content>textarea,.conflict textarea{width:100%;box-sizing:border-box;border:1px solid #dedde7;border-radius:7px;padding:13px;font:inherit;font-size:15px;line-height:1.9;resize:vertical;color:#374052;min-height:230px}.conflict{margin:14px 0;padding:12px;background:#fff7e7;border:1px solid #efdbb4;border-radius:7px;font-size:12px}.conflict textarea{min-height:140px;font-size:13px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.actions button{font:inherit;background:#fff;border:1px solid #dfd2b7;padding:7px;border-radius:5px;cursor:pointer}.pinned{background:#f8f7fc;border-left:3px solid #ac9cce;padding:14px}.pinned-title{display:flex;justify-content:space-between}.pinned>b{font-size:12px;color:#736a84}.pinned .original{max-height:230px;overflow:auto;font-size:12px}.versions>div{padding:12px 0;border-bottom:1px solid #eaeaf0;font-size:12px}.versions>div p{white-space:pre-wrap;max-height:180px;overflow:auto}.footnote{margin-top:22px}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}button:focus-visible,textarea:focus-visible,summary:focus-visible{outline:2px solid #8a76b8;outline-offset:3px}.auxiliary-panel small{display:block;color:#8c8a99;font-size:11px}
.intro,.footnote,.file-name{color:#667085}.auxiliary-panel nav button,.close,.auxiliary-panel small{color:#6f687a}.auxiliary-panel small{font-size:12px}
.auxiliary-panel{border-color:#e2e8f0;color:#334155}.auxiliary-panel nav button.active{border-color:#4f46e5;color:#4f46e5}.auxiliary-panel header{padding:12px 18px}.auxiliary-panel nav button,.close{min-height:36px;font-size:14px}.close{padding:6px 8px;border:1px solid #e2e8f0;border-radius:6px;color:#475569}.panel-content{font-size:15px}.intro,.footnote,.source-scope,.save-state{font-size:13px;color:#64748b}.panel-content h3{font-size:16px;color:#1e293b}.panel-content article,.original{font-size:14px}.link{font-size:14px;color:#4f46e5;min-height:32px}.source-scope,.pinned{background:#f8fafc}.pinned{border-color:#a5b4fc}.opinion-content>textarea{border-color:#cbd5e1;color:#1e293b}.save-state:not(.warning){color:#0f766e}.warning{color:#92400e;background:#fffbeb}summary{color:#475569}button:focus-visible,textarea:focus-visible,summary:focus-visible{outline-color:#4f46e5}
</style>
