<template><section class="issues"><h3>原问题中待明确的事项</h3><p v-if="error" role="alert">{{ error }}</p><article v-for="issue in visibleItems" :key="issue.issueId"><b>{{ issue.title || issue.summary || issue.issueId }}</b><p v-if="issue.reason || issue.neededEvidence && !issue.title?.includes(String(issue.neededEvidence))">{{ issue.reason }} {{ issue.neededEvidence }}</p><small>资料准备：{{ stateLabel(issue.preparationState,'待准备') }} · 问题解决：{{ stateLabel(issue.resolutionState,'待重新核验') }}</small><div><el-button @click="openSource(issue)">补充依据引用</el-button><el-button @click="event(issue,'deferred')">暂缓</el-button><el-button @click="event(issue,'reopened')">重新打开</el-button><el-button @click="$emit('recheck',issue.originalTurnId)">准备重新核验原问题</el-button></div></article><el-pagination v-if="items.length>10" v-model:current-page="page" :page-size="10" :total="items.length" layout="total, prev, pager, next" /><p v-if="!items.length&&!error">暂无保存的待明确事项。</p><el-dialog v-model="sourceVisible" title="补充依据" width="min(620px,94vw)" append-to-body><p>保存资料引用供原问题重新核验，补充资料不会自动把未知改为满足。</p><label>资料名称 *<el-input v-model="source.name" placeholder="例如：2026届毕业学分核查确认单" /></label><label>资料版本 *<el-input v-model="source.version" placeholder="年份或版本号" /></label><label>来源定位 *<el-input v-model="source.locator" placeholder="文件路径、链接、页码或条款" /></label><label>补充说明<el-input v-model="source.note" type="textarea" :rows="3" placeholder="说明这份资料能够补充什么依据" /></label><p v-if="sourceError" role="alert">{{ sourceError }}</p><template #footer><el-button @click="sourceVisible=false">取消</el-button><el-button type="primary" :loading="saving" :disabled="!source.name.trim()||!source.version.trim()||!source.locator.trim()" @click="saveSource">保存依据引用</el-button></template></el-dialog></section></template>
<script setup lang="ts">
import {computed,ref,watch} from 'vue';import {ElMessageBox} from 'element-plus';import {expertResourcesApi as api} from '@/api/aiDecision/expertResources';import type {ResearchIssue} from '@/types/expertResources'
const page=ref(1)
const visibleItems=computed(()=>items.value.slice((page.value-1)*10,page.value*10))
const sourceVisible=ref(false),source=ref({name:'',version:'',locator:'',note:''}),sourceIssue=ref<ResearchIssue|null>(null),sourceError=ref(''),saving=ref(false)
const stateLabel=(state:string|undefined,fallback:string)=>({missing:'待补充',submitted:'已提交依据',confirmed:'已确认',published:'规则已发布',rejected:'需修正',deferred:'暂缓',open:'待重新核验',resolved:'已核验解决'}[state||'']||fallback)
const props=defineProps<{researchId:string;refresh?:number}>();defineEmits<{recheck:[turnId?:string]}>();const items=ref<ResearchIssue[]>([]),error=ref('');let generation=0
async function load(){const epoch=++generation;error.value='';try{const data=await api.issues(props.researchId);if(epoch===generation)items.value=data.items}catch(e){if(epoch===generation)error.value=`事项加载失败：${(e as Error).message}`}}
function openSource(issue:ResearchIssue){sourceIssue.value=issue;source.value={name:'',version:'',locator:'',note:''};sourceError.value='';sourceVisible.value=true}
async function saveSource(){if(!sourceIssue.value)return;saving.value=true;sourceError.value='';try{await api.issueEvent(props.researchId,sourceIssue.value.issueId,{revision:sourceIssue.value.revision,type:'source_added',sourceRef:{...source.value}});sourceVisible.value=false;await load()}catch(e){sourceError.value=(e as Error).message}finally{saving.value=false}}
async function event(issue:ResearchIssue,type:'source_added'|'deferred'|'reopened'){try{const value=await ElMessageBox.prompt('填写本次操作原因','维护原问题事项',{inputType:'textarea'});await api.issueEvent(props.researchId,issue.issueId,{revision:issue.revision,type,reason:value.value});await load()}catch(e){if(e==='cancel'||e==='close')return;error.value=(e as Error).message}}
watch(()=>[props.researchId,props.refresh],()=>{items.value=[];page.value=1;void load()},{immediate:true})
</script><style scoped>.issues{font-size:13px;line-height:1.8;color:#526176}.issues article{padding:14px 0;border-bottom:1px solid #e2e8f0}.issues article>div{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.issues .el-button{margin:0}p{overflow-wrap:anywhere}label{display:flex;flex-direction:column;gap:8px;margin:16px 0}</style>
