<template>
  <div class="overview">
    <section class="overview-section"><h2>{{ kind==='experts'?'用途与当前能力':kind==='skills'?'用途与处理过程':'服务用途' }}</h2><p class="purpose">{{ content.summary || '尚未填写用途说明，请在草稿中补齐。' }}</p>
      <template v-if="kind==='experts'"><h3>已开放业务任务</h3><ul v-if="availableTasks.length" class="capabilities"><li v-for="task in availableTasks" :key="task.taskId"><b>{{ task.title }}</b><small>需要：{{ requiredInputs(task) }} · 返回：{{ resultLabel(task.resultKind) }}</small></li></ul><p v-else class="muted">当前没有已开放业务任务。模型问答按实际接通状态开放。</p><details v-if="waitingTasks.length" class="waiting-tasks"><summary>待建设任务与缺项（{{ waitingTasks.length }}）</summary><ul class="capabilities"><li v-for="task in waitingTasks" :key="task.taskId"><b>{{ task.title }}</b><span class="warning">{{ task.reason||'尚未开放' }}</span><small>需要：{{ requiredInputs(task) }} · 返回：{{ resultLabel(task.resultKind) }}</small></li></ul></details></template>
      <template v-if="kind==='skills'"><p v-if="content.purpose" class="paragraph">{{ content.purpose }}</p><h3>处理步骤</h3><ol class="reading-list"><li v-for="(step,index) in content.steps||[]" :key="index">{{ describeContent(step) }}</li></ol><p v-if="!content.steps?.length" class="muted">尚未登记处理步骤。</p><details v-if="content.instructions"><summary>补充执行说明</summary><p class="paragraph">{{ content.instructions }}</p></details></template>
    </section>
    <template v-if="kind==='experts'"><section class="overview-section" v-for="block in expertBlocks" :key="block.title"><h2>{{ block.title }}</h2><ul class="reading-list"><li v-for="(line,index) in block.lines" :key="index">{{ line }}</li></ul><p v-if="!block.lines.length" class="muted">尚未填写。</p></section><details v-if="content.instructions" class="overview-section"><summary>处理与结果说明要求</summary><ol v-if="instructionLines.length>1" class="reading-list"><li v-for="(line,index) in instructionLines" :key="index">{{ line }}</li></ol><p v-else class="paragraph">{{ content.instructions }}</p><p class="muted">确定性方法按已登记算法执行；文字说明不会自动修改计算。模型人设在实际接通的模型运行中生效。</p></details><section v-if="content.welcomeMessage" class="overview-section"><h2>会话欢迎语</h2><p class="paragraph">{{ content.welcomeMessage }}</p></section></template>
    <section v-if="kind==='skills'" class="overview-section"><h2>规则与计算口径</h2><StructuredRules :model-value="content.rules||[]" /></section>
    <section v-if="content.missingEvidence?.length" class="overview-section missing"><h2>待补资料与依据</h2><ul class="reading-list"><li v-for="item in content.missingEvidence" :key="item">{{ item }}</li></ul></section>
    <section v-if="kind==='skills'" class="overview-section"><h2>执行方式</h2><p>{{ content.execution?.handler==='unavailable'?'尚无可运行实现':content.execution?.mode||'使用已登记业务方法' }}</p><details><summary>查看技术方法与来源</summary><code>{{ content.execution?.handler||'按业务任务登记执行' }}</code><ul class="reading-list"><li v-for="(reference,index) in content.references||[]" :key="index">{{ describeContent(reference) }}</li></ul><pre v-for="(example,index) in content.examples||[]" :key="index">{{ JSON.stringify(example,null,2) }}</pre></details></section>
  </div>
</template>
<script setup lang="ts">
import {computed} from 'vue'
import type {BusinessTask,ResourceContent,ResourceKind} from '@/types/expertResources'
import StructuredRules from './StructuredRules.vue'
import {describeContent,schemaFieldLabel} from './presentation'
const props=withDefaults(defineProps<{kind:ResourceKind;content:ResourceContent;tasks?:BusinessTask[]}>(),{tasks:()=>[]})
const instructionLines=computed(()=>String(props.content.instructions||'').split(/[\r\n]+|[①②③④⑤⑥⑦⑧⑨⑩]/).map(line=>line.trim()).filter(Boolean))
const availableTasks=computed(()=>props.tasks.filter(task=>task.available)),waitingTasks=computed(()=>props.tasks.filter(task=>!task.available))
const expertBlocks=computed(()=>[{title:'具体职责',lines:props.content.responsibilities||[]},{title:'适用边界',lines:props.content.boundaries||[]},{title:'示例问题',lines:props.tasks.length?props.tasks.filter(task=>task.available).map(task=>task.title):props.content.starterQuestions||[]}])
function requiredInputs(task:BusinessTask){return (task.inputSchema.required||[]).map(key=>schemaFieldLabel(key,task.inputSchema.properties?.[key],true)).join('、')||'按当前授权范围；具体条件见任务'}
function resultLabel(kind:string){return ({facts:'事实与数据依据',rule_check:'限定条件核验',scenario:'明示假设的条件影响'} as Record<string,string>)[kind]||'任务结果与依据'}
</script>
<style scoped>.overview-section{border:1px solid #dfe5ed;border-radius:8px;background:#fff;padding:20px;margin:18px 0;line-height:1.8}.overview-section h2{font-size:16px;margin:0 0 12px;color:#263c5c}.overview-section h3{font-size:14px;margin:20px 0 10px}.purpose{font-size:15px;margin:0;white-space:pre-wrap;overflow-wrap:anywhere}.paragraph{white-space:pre-wrap;overflow-wrap:anywhere;margin:10px 0}.reading-list{list-style:disc!important;padding-left:22px!important;margin:0}.reading-list li{display:list-item!important;margin:8px 0;white-space:pre-wrap;overflow-wrap:anywhere}ol.reading-list{list-style:decimal!important}.muted{font-size:13px;color:#64748b}.capabilities{list-style:none;padding:0;margin:0}.capabilities li{border-top:1px solid #e4e9ef;padding:12px 0}.capabilities span,.capabilities small{display:block;font-size:13px;color:#64748b}.capabilities .warning{color:#8b631d}.missing{background:#fff9ed}.waiting-tasks{margin-top:16px;font-size:13px}.overview-section summary{cursor:pointer;color:#344b77}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;background:#f5f7fb;padding:12px}summary:focus-visible{outline:2px solid #344b77;outline-offset:3px}</style>
