<template>
<section class="evidence"><details @toggle="onToggle"><summary>{{ title }}</summary><p>源查询 {{ item.sourceRows ?? item.sourceRowCount ?? item.totalRows ?? '未知' }} 条；已保存 {{ item.retainedRows ?? item.retainedRowCount ?? '未知' }} 条。{{ item.retentionComplete ? '本次输入留存完整' : '留存完整性未确认' }}。来源业务覆盖需另看覆盖说明。</p><el-button :loading="loading" @click="load">读取本次保存内容</el-button><p v-if="error" role="alert">{{ error }}</p><template v-if="page"><p>共 {{ page.totalRows }} 条，当前 {{ page.returnedRows }} 条 · {{ page.retentionComplete?'保存完整':'部分保存' }}</p><div class="scroll"><table><thead><tr><th v-for="key in keys" :key="key">{{ columnLabels[key] || key }}</th></tr></thead><tbody><tr v-for="(row,i) in page.rows" :key="i"><td v-for="key in keys" :key="key">{{ evidenceCell(row,key) }}</td></tr></tbody></table></div><div class="paging"><el-button :disabled="offset===0||loading" @click="offset=Math.max(0,offset-20);load()">上一页</el-button><span>{{ page.totalRows?`${offset+1}—${offset+page.returnedRows}`:'0 条' }}</span><el-button :disabled="offset+page.returnedRows>=page.totalRows||loading" @click="offset+=20;load()">下一页</el-button></div></template></details></section>
</template>
<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {expertResourcesApi as api} from '@/api/aiDecision/expertResources'
import type {RetainedEvidence} from '@/types/expertResources'
const props=defineProps<{resultId:string;item:Record<string,any>;publicationId?:string;presetId?:string}>()
const evidenceTitles:Record<string,string>={'program-source-courses':'来源方案的课程安排','program-target-courses':'对照方案的课程安排','course-aggregate':'课程首修与未通过记录'}
const title=computed(()=>props.item.title||props.item.name||evidenceTitles[props.item.evidenceId]||'本次保存的数据依据')
const columnLabels:Record<string,string>={course_id:'课程编号',course_name:'课程名称',compulsory:'原必修标记',module:'课程模块',credits:'课程目录学分',recorded_plan_credits:'方案字段原值',credit_check:'学分字段核对',requirement_type:'要求类型',source_rows:'来源记录数',suggested_term:'建议学期',total_hours:'总学时',updated_at:'数据更新时间',first_attempts:'首修人次',first_pass:'首修通过人次',first_pass_pct:'首修通过率（%）',failures:'未通过次数',students:'本聚合行学生数',semester_id:'学期编号',college_id:'开课院系编号',college_name:'开课院系',rule_version:'规则版本',rate_reason:'比例未知或冲突原因',aggregate_state:'聚合核对状态',calculated_at:'数据计算时间',makeup_attempts:'补考人次',makeup_pass:'补考通过人次',retake_attempts:'重修人次',retake_pass:'重修通过人次',organization_id:'开课院系编号'}
const page=ref<RetainedEvidence|null>(null),offset=ref(0),loading=ref(false),error=ref('');let request=0
const keys=computed(()=>{const keys=[...new Set(page.value?.rows.flatMap(row=>Object.keys(row))||[])];const preferred=['course_name','course_id','first_pass_pct','first_attempts','first_pass','failures','rate_reason'];return [...preferred.filter(key=>keys.includes(key)),...keys.filter(key=>!preferred.includes(key))]})
function evidenceCell(row:Record<string,unknown>,key:string){const value=row[key];if(key==='rate_reason'&&!value)return row.first_pass_pct==null?'原因未记录':'—';if(key==='aggregate_state')return ({known:'可核',unknown:'未知',conflict:'冲突'} as Record<string,string>)[String(value)]||String(value);if(value==null)return '未知';if(['calculated_at','updated_at'].includes(key)&&typeof value==='string')return Number.isNaN(new Date(value).getTime())?value:new Date(value).toLocaleString('zh-CN',{hour12:false,timeZone:'Asia/Shanghai'});return typeof value==='object'?JSON.stringify(value):String(value)}
async function load(){const id=++request;loading.value=true;error.value='';try{const value=props.publicationId?await api.publicationEvidence(props.publicationId,props.item.evidenceId,offset.value):props.presetId?await api.presetExecutionEvidence(props.presetId,props.resultId,props.item.evidenceId,offset.value):await api.evidence(props.resultId,props.item.evidenceId,offset.value);if(id===request)page.value=value}catch(e){if(id===request)error.value=(e as Error).message}finally{if(id===request)loading.value=false}}
function onToggle(event:Event){if((event.target as HTMLDetailsElement).open&&!page.value&&!loading.value)void load()}
watch(()=>[props.resultId,props.item.evidenceId,props.publicationId,props.presetId],()=>{request++;page.value=null;offset.value=0;error.value='';loading.value=false})
</script>
<style scoped>.evidence{border:1px solid #dfe6ef;border-radius:6px;padding:14px;margin:12px 0;font-size:13px;color:#526176}summary{cursor:pointer}.scroll{overflow:auto;max-height:400px}table{border-collapse:collapse;width:100%}th,td{white-space:nowrap;padding:8px;border-bottom:1px solid #e2e8f0;text-align:left}.paging{display:flex;align-items:center;gap:15px;margin-top:12px}p{line-height:1.8}</style>
