<template>
<section class="rule-maintenance"><h3>适用规则与确认依据</h3><p>填写规则适用范围、要求与来源。候选内容经确认和真实案例验证后才可发布。</p><div class="actions"><el-button @click="load">刷新规则</el-button><el-button @click="open()">提交候选规则</el-button></div><p v-if="error" role="alert">{{ error }}</p>
<article v-for="rule in related" :key="rule.ruleId+rule.version"><b>{{ rule.payload.note || rule.payload.name || rule.ruleId }} · {{ rule.version }}</b><el-tag>{{ labels[state(rule)] || state(rule) }}</el-tag><p>{{ scopeLabel(rule) }}</p><p v-for="(source,index) in rule.payload.sources || []" :key="index">来源：{{ source.name }} · {{ source.version }} · {{ source.locator }}</p><p>业务确认：{{ rule.confirmation?.businessConfirmer || (rule.confirmation?'已记录':'尚无有效记录') }}</p><div class="actions"><el-button v-if="!['published','withdrawn'].includes(state(rule))" @click="open(rule)">修改候选</el-button><el-button v-else @click="open(rule,true)">建立新版本</el-button><el-button v-if="canImport && !['published','withdrawn'].includes(state(rule))" @click="openConfirmation(rule)">导入外部确认依据</el-button><el-button :disabled="['published','withdrawn'].includes(state(rule))" @click="action(rule,'test')">运行案例验证</el-button><el-button :disabled="state(rule)!=='confirmed'" @click="action(rule,'publish')">发布规则</el-button><el-button v-if="state(rule)==='published'" @click="action(rule,'withdraw')">撤回规则</el-button></div></article><p v-if="!related.length">尚无关联规则。业务说明不能替代正式规则。</p>
<el-dialog v-model="visible" class="policy-rule-dialog" top="5vh" title="正式政策与条件规则 · 候选" width="min(860px,95vw)" append-to-body><p>明确适用范围与独立条件；填写规则不会自动获得政策确认或执行资格。</p><el-switch v-model="advanced" active-text="高级结构编辑" @change="switchEditor" />
<el-input v-if="advanced" v-model="payloadText" type="textarea" :rows="20" />
<template v-else><div class="form-grid"><label class="full">规则名称 *<el-input v-model="form.note" :placeholder="`填写${domains.find(d=>d.id===form.domain)?.label||'本业务'}的正式规则名称`" /></label><label>规则编码 *<el-input v-model="form.ruleId" :disabled="!!editing" placeholder="英文字母、数字、短横线" /></label><label>版本 *<el-input v-model="form.version" :disabled="!!editing" placeholder="1.0.0" /></label><label>规则类别 *<el-select v-model="form.domain" :disabled="!!editing"><el-option v-for="domain in domains" :key="domain.id" :value="domain.id" :label="domain.label" /></el-select></label><label>适用年份<el-input v-model="form.years" placeholder="例如：2026，多个年份用逗号分隔" /></label><label>适用院系<el-select v-model="form.organizations" multiple filterable clearable :loading="optionsLoading" placeholder="选择授权院系"><el-option v-for="college in options.colleges" :key="college.id" :value="String(college.id)" :label="college.name" /></el-select></label><label>适用培养方案<el-select v-model="form.programs" multiple filterable clearable :loading="optionsLoading" placeholder="选择具体培养方案"><el-option v-for="plan in options.plans" :key="plan.id" :value="String(plan.id)" :label="`${plan.name} · ${plan.grade || ''}级`" /></el-select></label><label class="full">适用年级<el-input v-model="form.cohorts" placeholder="例如：2022，多个年级用逗号分隔" /></label></div><p>至少明确一个适用范围；年份、院系、培养方案与年级同时填写时共同限定。</p>
<h4>需要核验的条件</h4><article v-for="(condition,index) in form.conditions" :key="index" class="condition-form"><div class="form-grid"><label>条件名称 / 编码 *<el-input v-model="condition.conditionId" placeholder="例如：required-math" /></label><label>归属类别 *<el-select v-model="condition.category"><el-option v-for="domain in domains" :key="domain.id" :value="domain.id" :label="domain.label" /></el-select></label><label>要求类型 *<el-select v-model="condition.type"><el-option value="course_completion" label="指定课程完成" /><el-option value="credit_pool" label="独立课程池最低学分" /></el-select></label><label v-if="condition.type==='course_completion'">课程编号 *<el-input v-model="condition.courseId" placeholder="填写规则来源对应的课程编号" /></label><template v-else><label>课程池内课程编号 *<el-input v-model="condition.courseIdsText" placeholder="课程编号用逗号分隔，不默认包含所有课程" /></label><label>最低学分 *<el-input v-model="condition.minCredits" placeholder="例如：6 或 6.5" /></label></template></div><el-button @click="form.conditions.splice(index,1)">删除此条件</el-button></article><el-button @click="addCondition">＋ 添加核验条件</el-button><h4>规则原文来源</h4><div class="form-grid"><label>资料名称 *<el-input v-model="form.source.name" /></label><label>资料版本 *<el-input v-model="form.source.version" placeholder="年份或版本号" /></label><label class="full">来源定位 *<el-input v-model="form.source.locator" placeholder="文件路径、链接、页码或条款" /></label><label class="full">补充说明<el-input v-model="form.source.note" type="textarea" :rows="2" /></label></div></template><p v-if="dialogError" role="alert">{{ dialogError }}</p><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="busy" @click="save">保存候选</el-button></template></el-dialog>
<el-dialog v-model="confirmVisible" title="导入真实外部确认记录" width="min(660px,94vw)" append-to-body><p>仅导入已发生且可核对的业务确认，系统保留导入操作人与实际确认人。</p><div class="form-grid"><label>实际业务确认人 *<el-input v-model="confirmation.businessConfirmer" /></label><label>确认时间 *<el-date-picker v-model="confirmation.confirmedAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" /></label><label class="full">确认依据名称 *<el-input v-model="confirmation.sourceRef.name" /></label><label>依据版本 *<el-input v-model="confirmation.sourceRef.version" /></label><label>依据定位 *<el-input v-model="confirmation.sourceRef.locator" /></label><label class="full">确认意见与范围 *<el-input v-model="confirmation.note" type="textarea" :rows="4" /></label></div><p v-if="dialogError">{{ dialogError }}</p><template #footer><el-button @click="confirmVisible=false">取消</el-button><el-button type="primary" :loading="busy" @click="saveConfirmation">导入确认记录</el-button></template></el-dialog>
</section></template>
<script setup lang="ts">
import {computed,onMounted,ref,watch} from 'vue';import {ElMessageBox} from 'element-plus';import {expertResourcesApi as api} from '@/api/aiDecision/expertResources';import type {ExpertRule,ResourceOptions} from '@/types/expertResources'
const props=defineProps<{skillId:string;allowedDomains:string[]}>();const rules=ref<ExpertRule[]>([]),error=ref(''),canImport=ref(false),visible=ref(false),advanced=ref(false),payloadText=ref(''),editing=ref<ExpertRule|null>(null),original=ref<Record<string,any>>({}),busy=ref(false),dialogError=ref(''),optionsLoading=ref(false),options=ref<ResourceOptions>({plans:[],semesters:[],colleges:[]})
const allDomains=[{id:'graduation',label:'毕业要求'},{id:'degree',label:'学位要求'},{id:'transfer',label:'转专业条件'},{id:'recommendation',label:'推免条件'},{id:'support',label:'支撑条件'}]
const domains=computed(()=>allDomains.filter(domain=>props.allowedDomains.includes(domain.id)))
const blankCondition=()=>({conditionId:'',category:props.allowedDomains[0]||'',type:'course_completion',courseId:'',courseIdsText:'',minCredits:''})
const blankForm=()=>({ruleId:'',version:'1.0.0',note:'',domain:props.allowedDomains[0]||'',years:'',organizations:[] as string[],programs:[] as string[],cohorts:'',conditions:[blankCondition()],source:{name:'',version:'',locator:'',note:''}})
const form=ref(blankForm()),confirmVisible=ref(false),confirmRule=ref<ExpertRule|null>(null),confirmation=ref({mode:'external',businessConfirmer:'',confirmedAt:'',note:'',sourceRef:{name:'',version:'',locator:''}})
const labels:Record<string,string>={draft:'候选',confirmed:'已确认',published:'已发布',withdrawn:'已撤回'}
const state=(rule:ExpertRule)=>rule.state||rule.status
const related=computed(()=>rules.value.filter(r=>r.payload.skillIds?.includes(props.skillId)||r.payload.skillId===props.skillId));let generation=0
const split=(value:string)=>value.split(/[,，;；\s]+/).map(v=>v.trim()).filter(Boolean)
function scopeLabel(rule:ExpertRule){const scope=rule.payload.applicability||{};return [scope.years?.length?`年份 ${scope.years.join('、')}`:'',scope.organizations?.length?`院系 ${scope.organizations.map((id:string)=>options.value.colleges.find(c=>String(c.id)===String(id))?.name||id).join('、')}`:'',scope.programs?.length?`培养方案 ${scope.programs.map((id:string)=>options.value.plans.find(p=>String(p.id)===String(id))?.name||id).join('、')}`:'',scope.cohorts?.length?`年级 ${scope.cohorts.join('、')}`:''].filter(Boolean).join(' · ')}
async function load(){const epoch=++generation;error.value='';try{const data=await api.rules();if(epoch!==generation)return;rules.value=data.items;canImport.value=data.canImportConfirmation===true}catch(e){if(epoch===generation)error.value=`规则加载失败：${(e as Error).message}`}}
async function loadOptions(){optionsLoading.value=true;try{options.value=await api.options()}catch(e){dialogError.value=`范围选项未加载：${(e as Error).message}`}finally{optionsLoading.value=false}}
function open(rule?:ExpertRule,newVersion=false){editing.value=newVersion?null:rule||null;original.value=rule?JSON.parse(JSON.stringify(rule.payload)):{};form.value=blankForm();if(rule){const p=rule.payload,a=p.applicability||{},source=p.sources?.[0]||{};form.value={...blankForm(),ruleId:p.ruleId||rule.ruleId,version:p.version||rule.version,note:p.note||p.name||'',domain:p.domain,years:(a.years||[]).join(','),organizations:(a.organizations||[]).map(String),programs:(a.programs||[]).map(String),cohorts:(a.cohorts||[]).join(','),conditions:(p.conditions||[]).map((c:any)=>({...blankCondition(),...c,courseIdsText:(c.courseIds||[]).join(','),minCredits:String(c.minCredits??'')})),source:{name:source.name||'',version:source.version||'',locator:source.locator||'',note:source.note||''}};if(newVersion){const parts=form.value.version.split('.').map(Number);form.value.version=`${parts[0]}.${parts[1]+1}.0`}}advanced.value=form.value.conditions.some(c=>!['credit_pool','course_completion'].includes(c.type));payloadText.value=JSON.stringify(original.value,null,2);dialogError.value='';visible.value=true;void loadOptions()}
function addCondition(){form.value.conditions.push({...blankCondition(),category:form.value.domain})}
function toPayload(){const f=form.value;const applicability:Record<string,string[]>={};for(const[k,v]of Object.entries({years:split(f.years),organizations:f.organizations,programs:f.programs,cohorts:split(f.cohorts)}))if(v.length)applicability[k]=v;return {...original.value,ruleId:f.ruleId.trim(),version:f.version.trim(),note:f.note.trim(),domain:f.domain,skillIds:[...new Set([...(original.value.skillIds||[]),props.skillId])],applicability,conditions:f.conditions.map(c=>{const {courseIdsText:_text,...fields}=c;const condition:Record<string,any>={...fields,conditionId:c.conditionId.trim(),category:c.category,type:c.type,...(c.type==='credit_pool'?{courseIds:split(c.courseIdsText),minCredits:c.minCredits.trim()}:{courseId:c.courseId.trim()})};if(c.type==='credit_pool')delete condition.courseId;else{delete condition.courseIds;delete condition.minCredits}return condition}),sources:[{...(original.value.sources?.[0]||{}),...f.source},...(original.value.sources||[]).slice(1)]}}
function switchEditor(value:unknown){if(value)payloadText.value=JSON.stringify(toPayload(),null,2);else{try{const payload=JSON.parse(payloadText.value);original.value=payload;const temporary={ruleId:payload.ruleId,version:payload.version,payload} as ExpertRule;const keep=editing.value;open(temporary);editing.value=keep}catch(e){advanced.value=true;dialogError.value='高级结构不是有效JSON，请修正后切回表单'}}}
function validateForm(){const f=form.value;if(!f.note.trim()||!f.ruleId.trim()||!f.version.trim())throw new Error('请填写规则名称、编码和版本');if(!split(f.years).length&&!f.organizations.length&&!f.programs.length&&!split(f.cohorts).length)throw new Error('至少填写一个明确适用范围');if(!f.source.name.trim()||!f.source.version.trim()||!f.source.locator.trim())throw new Error('请填写来源名称、版本与定位');if(!f.conditions.length)throw new Error('至少添加一项条件');for(const c of f.conditions){if(!c.conditionId.trim())throw new Error('请填写每项条件名称或编码');if(c.type==='course_completion'&&!c.courseId.trim())throw new Error('课程完成条件必须填写具体课程编号');if(c.type==='credit_pool'&&(!split(c.courseIdsText).length||!/^\d+(\.\d+)?$/.test(c.minCredits)||Number(c.minCredits)<=0))throw new Error('学分条件需要明确课程池和正数最低学分')}}
async function save(){busy.value=true;dialogError.value='';try{if(!advanced.value)validateForm();const payload=advanced.value?JSON.parse(payloadText.value):toPayload();if(!props.allowedDomains.includes(payload?.domain))throw new Error('规则类别与本技能适用业务不一致');if(!payload||Array.isArray(payload)||typeof payload!=='object')throw new Error('规则应为JSON对象');if(editing.value)await api.saveRule(editing.value.ruleId,editing.value.version,editing.value.revision,payload);else await api.createRule(payload);visible.value=false;await load()}catch(e){dialogError.value=(e as Error).message}finally{busy.value=false}}
function openConfirmation(rule:ExpertRule){confirmRule.value=rule;confirmation.value={mode:'external',businessConfirmer:'',confirmedAt:'',note:'',sourceRef:{name:'',version:'',locator:''}};dialogError.value='';confirmVisible.value=true}
async function saveConfirmation(){if(!confirmRule.value)return;busy.value=true;dialogError.value='';try{const c=confirmation.value;if(!c.businessConfirmer.trim()||!c.confirmedAt||!c.note.trim()||!c.sourceRef.name.trim()||!c.sourceRef.version.trim()||!c.sourceRef.locator.trim())throw new Error('请补齐实际确认人、时间、确认意见和依据定位');await api.ruleAction(confirmRule.value.ruleId,confirmRule.value.version,'confirm',{revision:confirmRule.value.revision,accepted:true,confirmation:c});confirmVisible.value=false;await load()}catch(e){dialogError.value=(e as Error).message}finally{busy.value=false}}
async function action(rule:ExpertRule,type:'test'|'publish'|'withdraw'){try{const body:Record<string,unknown>={revision:rule.revision};if(type==='withdraw'){const value=await ElMessageBox.prompt('说明撤回原因','撤回规则');body.reason=value.value}else await ElMessageBox.confirm(type==='test'?'服务端将执行固定适用案例，并保存真实运行记录。':'发布固定当前规则版本，服务端会校验业务确认与实际案例。',type==='test'?'运行规则验证':'发布规则');await api.ruleAction(rule.ruleId,rule.version,type,body);await load()}catch(e){if(e==='cancel'||e==='close')return;error.value=(e as Error).message}}
watch(()=>props.skillId,()=>{rules.value=[];void load()});onMounted(()=>void load())
</script><style scoped>:global(.policy-rule-dialog .el-dialog__body){max-height:70vh;overflow:auto}.rule-maintenance{line-height:1.8;color:#526176;font-size:13px}.rule-maintenance article{border-top:1px solid #e2e8f0;padding:16px 0}.rule-maintenance .el-tag{margin-left:12px}.actions{display:flex;gap:10px;flex-wrap:wrap}.actions .el-button{margin:0}p{overflow-wrap:anywhere}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:18px 0}.form-grid label{display:flex;flex-direction:column;gap:8px}.full{grid-column:1/-1}.condition-form{background:#f7f9fc;padding:14px!important;border:1px solid #e2e8f0;border-radius:6px;margin:12px 0}@media(max-width:640px){.form-grid{grid-template-columns:1fr}}</style>
