<template><section class="schema-box"><h3>{{ title }}</h3><p v-if="schema?.description">{{ schema.description }}</p><div v-for="[key,field] in fields.slice(0,expanded?fields.length:8)" :key="key" class="schema-row"><div><b>{{ schemaFieldLabel(key,field,schema?.required?.includes(key)) }}</b><span v-if="schema?.required?.includes(key)" class="required">必填</span><span>{{ typeLabel(field.type) }}</span></div><code>{{ key }}</code><p>{{ fieldDescription(key,field) }}</p><small v-if="field.default!==undefined">默认值：{{ JSON.stringify(field.default) }}</small><small v-if="field.enum?.length">允许值：{{ field.enum.join('、') }}</small><details v-if="field.properties||field.items?.properties"><summary>展开子字段</summary><dl><template v-for="[childKey,child] in Object.entries(field.properties||field.items?.properties||{})" :key="childKey"><dt>{{ child.title||schemaLabels[childKey]||childKey }} <code>{{ childKey }}</code></dt><dd>{{ child.description||schemaDescriptions[childKey]||typeLabel(child.type) }}</dd></template></dl></details></div><el-button v-if="fields.length>8" text @click="expanded=!expanded">{{ expanded?'收起详细字段':`查看全部 ${fields.length} 个字段` }}</el-button><p v-if="!fields.length" class="quiet">{{ schema ? '按约定的结构返回，详见结构定义。' : '尚未登记字段说明。' }}</p><details v-if="schema"><summary>高级：查看完整 JSON 契约</summary><pre>{{ JSON.stringify(schema,null,2) }}</pre></details></section></template>
<script setup lang="ts">
import type {ResourceSchema} from '@/types/expertResources'
import {computed,ref} from 'vue'
import {schemaLabels,schemaDescriptions,schemaFieldLabel} from './presentation'
const props=defineProps<{title:string;schema?:ResourceSchema}>(),expanded=ref(false)
const fieldOrder=['summary','status','scope','facts','data','coverage','conditions','issues','sources','limitations','missingEvidence','tables','evidence']
const priority=(key:string)=>{const index=fieldOrder.indexOf(key);return index<0?fieldOrder.length:index}
const fields=computed(()=>Object.entries(props.schema?.properties||{}).sort(([a],[b])=>Number(props.schema?.required?.includes(b))-Number(props.schema?.required?.includes(a))||priority(a)-priority(b)))
function fieldDescription(key:string,field:ResourceSchema){if(key==='semester_id'&&props.schema?.required?.includes(key)&&field.description==='从当前数据选项选择的学期ID；未指定时由返回结果明确实际范围。')return '从当前数据选项选择学期ID；本工具必须指定学期，不自动继承旧筛选。';return field.description||schemaDescriptions[key]||'尚未登记字段含义，请核对技术契约。'}
function typeLabel(type?:string|string[]):string {if(Array.isArray(type))return type.map(typeLabel).join(' / ');return ({string:'文本',integer:'整数',number:'数值',array:'列表',object:'结构化内容',boolean:'是 / 否',null:'可为空'} as Record<string,string>)[type||'']||'按字段契约'}
</script>
<style scoped>.schema-box{border:1px solid #e0e6ee;border-radius:6px;padding:16px;margin:14px 0;min-width:0}.schema-box h3{font-size:15px;font-weight:600;margin:0 0 12px;color:#304768}.schema-box p{font-size:13px;line-height:1.7;color:#64748b;margin:7px 0}.schema-row{border-top:1px solid #e7ecf2;padding:12px 0}.schema-row>div{display:flex;gap:10px;flex-wrap:wrap;align-items:center;font-size:13px}.schema-row b{font-weight:500}.schema-row code{font-size:11px;color:#748197}.required{font-size:11px;color:#9d642b}.schema-box details{font-size:12px;color:#526783;margin-top:10px}.schema-box summary{cursor:pointer}.schema-box pre{padding:12px;background:#f6f8fb;border-radius:4px;white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.6}.quiet{color:#6b778a}</style>
