"""Code-verified metric seeds for operational teaching-analysis modules.

This extension is derived from the current FastAPI aggregation logic and Vue
rendering sites for teaching operation, curriculum quality and faculty
assurance.  It deliberately keeps similarly labelled values separate whenever
their source table, denominator, or grain differs.  Interface-only fields are
registered only when they are inputs to a visible metric and are identified as
such in their usage descriptions.
"""
from __future__ import annotations


def _page(
    module_path: str,
    feature_name: str,
    source_ref: str,
    *,
    usage_type: str = "table",
    occurrence: str | None = None,
    description: str = "",
) -> dict:
    return {
        "module_path": module_path,
        "feature_name": feature_name,
        "feature_description": description or f"“{feature_name}”指标使用位置。",
        "usage_type": usage_type,
        "occurrence_key": occurrence or f"{usage_type}:{feature_name}",
        "source_ref": source_ref,
    }


def _metric(
    metric_id: str,
    domain: str,
    name: str,
    formula: str,
    description: str,
    boundary: str,
    grain: str,
    data_source: str,
    source_ref: str,
    pages: list[dict],
    *,
    unit: str = "个",
) -> dict:
    return {
        "metric_id": metric_id,
        "metric_code": metric_id,
        "technical_kpi_id": metric_id.lower().replace(".", "_").replace("-", "_"),
        "domain": domain,
        "name": name,
        "description": description,
        "formula": formula,
        "boundary": boundary,
        "management_value": description,
        "definition_status": "published",
        "implementation_status": "verified",
        "data_source": data_source,
        "grain": grain,
        "update_cycle": "随教学业务数据同步",
        "version": "1.0",
        "source_kind": "formal",
        "source_ref": source_ref,
        "unit": unit,
        "pages": pages,
    }


def _rule(metric_id: str, rule_type: str, rule_id: str, role: str, description: str, source_ref: str) -> dict:
    return {
        "metric_id": metric_id,
        "rule_type": rule_type,
        "rule_id": rule_id,
        "role": role,
        "description": description,
        "source_ref": source_ref,
    }


OP_COURSES = "/admin/operation/courses"
OP_SCHEDULE = "/admin/operation/schedule-analysis"
OP_CLASSROOM = "/admin/operation/classroom"
OP_LOAD = "/admin/operation/teacher-load"
OP_CHANGES = "/admin/operation/schedule-changes"
OP_RESULTS = "/admin/operation/course-quality"
CURRICULUM = "/admin/curriculum"
CURRICULUM_PROGRESS = "/admin/curriculum?tab=progress"
CURRICULUM_GRADUATION = "/admin/curriculum?tab=graduation-readiness"
FACULTY = "/admin/faculty"

OP_API = "code/backend/api/routers/operation.py"
V2_API = "code/backend/api/routers/v2.py"
GROWTH_ETL = "code/backend/etl/v2_growth_builder.py"
FACULTY_API = "code/backend/api/routers/faculty.py"
OP_VIEW = "code/frontend/src/views/teaching-analysis/operation"
COURSES_VIEW = f"{OP_VIEW}/Courses.vue"
CLASSROOM_VIEW = f"{OP_VIEW}/Classroom.vue"
CURRICULUM_VIEW = "code/frontend/src/views/teaching-analysis/curriculum/index.vue"
FACULTY_VIEW = "code/frontend/src/views/teaching-analysis/faculty/index.vue"


_OPERATION_METRICS: tuple[dict, ...] = (
    # 教学运行分析：课程供给。
    _metric(
        "TA.OP.SUPPLY.LESSON_COUNT", "教学运行分析", "开课教学班数",
        "COUNT(agg_course_offering)",
        "统计当前筛选范围内的开课教学班规模。",
        "按开课聚合记录计数；不同于按 teaching_lesson 计算的排课教学班数。",
        "学院/课程属性/班额区间×学期", "agg_course_offering", f"{OP_API}#course_offering_summary",
        [_page(OP_COURSES, "开课教学班KPI", COURSES_VIEW, usage_type="kpi")],
    ),
    _metric(
        "TA.OP.SUPPLY.ENROLLED_VISITS", "教学运行分析", "修读人次",
        "SUM(agg_course_offering.enrolled)",
        "汇总开课教学班的选课人数，用于观察教学供给承载量。",
        "同一学生修读多门课程会重复计数，是人次而非去重学生数。",
        "学院/课程属性/班额区间×学期", "agg_course_offering.enrolled", f"{OP_API}#course_offering_summary",
        [_page(OP_COURSES, "修读人次KPI", COURSES_VIEW, usage_type="kpi")], unit="人次",
    ),
    _metric(
        "TA.OP.SUPPLY.AVG_CLASS_SIZE", "教学运行分析", "平均班额（课程供给）",
        "SUM(enrolled) / COUNT(agg_course_offering)",
        "以全部开课聚合记录为分母计算平均班额。",
        "包含 enrolled=0 的教学班；不得与排课策略中忽略零值的 AVG(NULLIF(enrolled,0)) 合并。",
        "筛选范围×学期", "agg_course_offering.enrolled", f"{OP_API}#course_offering_summary",
        [_page(OP_COURSES, "平均班额KPI", COURSES_VIEW, usage_type="kpi")], unit="人/班",
    ),
    _metric(
        "TA.OP.SUPPLY.COURSE_TEACHER_COUNT", "教学运行分析", "开课教师数（课程供给）",
        "COUNT(DISTINCT primary_teacher_id)",
        "按开课聚合表主讲教师字段去重统计开课教师。",
        "只统计 primary_teacher_id；不包含共同授课教师绑定。",
        "筛选范围×学期", "agg_course_offering.primary_teacher_id", f"{OP_API}#course_offering_summary",
        [_page(OP_COURSES, "开课教师KPI", COURSES_VIEW, usage_type="kpi")], unit="人",
    ),
    _metric(
        "TA.OP.SUPPLY.ATTENTION_SCORE", "教学运行分析", "课程供给关注得分",
        "平均班额分 + 开课教师不足分 + 教学班规模分 + 修读人次分",
        "将班额、教师、教学班和修读人次组合为课程关注排序分值。",
        "仅用于启发式排序；阈值见规则绑定，不是正式质量评价。",
        "课程×学期", "agg_course_offering", f"{OP_API}#course_offering_summary",
        [_page(OP_COURSES, "关注课程排序", COURSES_VIEW, usage_type="sort")], unit="分",
    ),
    _metric(
        "TA.OP.SUPPLY.ATTENTION_COURSE_COUNT", "教学运行分析", "关注课程数",
        "COUNT(DISTINCT course_id WHERE attention_score > 0)",
        "统计触发任一课程供给关注条件的课程数。",
        "以接口计算后的 attention_score 为准；不是规则处置数量。",
        "筛选范围×学期", "agg_course_offering", f"{OP_API}#course_offering_summary",
        [_page(OP_COURSES, "关注课程KPI", COURSES_VIEW, usage_type="kpi")],
    ),
    _metric(
        "TA.OP.SUPPLY.COLLEGE_LESSON_COUNT", "教学运行分析", "学院开课教学班数",
        "COUNT(agg_course_offering) GROUP BY college",
        "展示各开课学院承担的教学班数量。",
        "学院取开课归属学院，不代表学生所属学院。",
        "学院×学期", "agg_course_offering", f"{OP_API}#course_offering_summary",
        [_page(OP_COURSES, "学院供给表-教学班", COURSES_VIEW)],
    ),
    _metric(
        "TA.OP.SUPPLY.COLLEGE_LESSON_SHARE", "教学运行分析", "学院教学班占比",
        "学院开课教学班数 / 全部开课教学班数 × 100%",
        "衡量学院开课教学班数在当前范围中的占比。",
        "分母随当前权限和筛选范围变化。",
        "学院×学期", "agg_course_offering", f"{OP_API}#course_offering_summary",
        [_page(OP_COURSES, "学院供给表-占比", COURSES_VIEW)], unit="%",
    ),
    _metric(
        "TA.OP.SUPPLY.NATURE_COURSE_COUNT", "教学运行分析", "课程性质课程数",
        "COUNT(DISTINCT course_id) GROUP BY course_nature",
        "按课程性质统计去重课程数。",
        "课程性质为空时归入接口约定的未分类项。",
        "课程性质×学期", "agg_course_offering.course_nature", f"{OP_API}#course_offering_summary",
        [_page(OP_COURSES, "课程性质分布-课程数", COURSES_VIEW, usage_type="chart")],
    ),
    _metric(
        "TA.OP.SUPPLY.NATURE_COURSE_SHARE", "教学运行分析", "课程性质课程占比",
        "课程性质去重课程数 / 全部去重课程数 × 100%",
        "展示不同课程性质的课程构成。",
        "课程跨教学班去重；分母不是教学班数。",
        "课程性质×学期", "agg_course_offering.course_id", f"{OP_API}#course_offering_summary",
        [_page(OP_COURSES, "课程性质分布-占比", COURSES_VIEW, usage_type="tooltip")], unit="%",
    ),
    _metric(
        "TA.OP.SUPPLY.SIZE_LESSON_COUNT", "教学运行分析", "班额区间教学班数",
        "COUNT(agg_course_offering) GROUP BY class_size_band",
        "按后端班额分档统计教学班数。",
        "分档由 enrolled 判定；页面“超大班>120”与实际边界存在已登记差异。",
        "班额区间×学期", "agg_course_offering.enrolled", f"{OP_API}#course_offering_summary",
        [_page(OP_COURSES, "班额结构-教学班数", COURSES_VIEW, usage_type="chart")],
    ),
    _metric(
        "TA.OP.SUPPLY.SIZE_LESSON_SHARE", "教学运行分析", "班额区间教学班占比",
        "班额区间教学班数 / 全部教学班数 × 100%",
        "展示各班额区间在开课教学班中的构成。",
        "分母为当前筛选范围内全部开课聚合记录。",
        "班额区间×学期", "agg_course_offering.enrolled", f"{OP_API}#course_offering_summary",
        [_page(OP_COURSES, "班额结构-占比", COURSES_VIEW, usage_type="tooltip")], unit="%",
    ),
    _metric(
        "TA.OP.SUPPLY.EXCLUDED_TEACHERS", "教学运行分析", "异常教师排除数（课程供给）",
        "COUNT(DISTINCT primary_teacher_id WHERE 教师启发式异常)",
        "记录课程供给统计中因教师标识异常而排除的教师数。",
        "接口返回的数据质量说明项，当前页面不单独展示。",
        "筛选范围×学期", "agg_course_offering.primary_teacher_id", f"{OP_API}#course_offering_summary",
        [_page(OP_COURSES, "接口返回-异常教师排除数", f"{OP_API}#course_offering_summary", usage_type="hidden column", description="接口返回但当前页面未展示的数据质量字段。")], unit="人",
    ),
    _metric(
        "TA.OP.SUPPLY.EXCLUDED_LESSONS", "教学运行分析", "异常教师关联教学班排除数",
        "COUNT(agg_course_offering WHERE primary_teacher_id 被判为异常)",
        "记录因异常教师标识而从课程供给统计中排除的教学班数。",
        "接口返回的数据质量说明项，当前页面不单独展示。",
        "筛选范围×学期", "agg_course_offering.primary_teacher_id", f"{OP_API}#course_offering_summary",
        [_page(OP_COURSES, "接口返回-异常教学班排除数", f"{OP_API}#course_offering_summary", usage_type="hidden column", description="接口返回但当前页面未展示的数据质量字段。")],
    ),

    # 教学运行分析：排课策略。
    _metric(
        "TA.OP.SCHEDULE.LESSON_COUNT", "教学运行分析", "排课教学班数",
        "COUNT(DISTINCT teaching_lesson.id)",
        "统计排课明细覆盖的教学班数量。",
        "来源为 teaching_lesson，不等同于课程供给页 agg_course_offering 记录数。",
        "筛选范围×学期", "teaching_lesson", f"{OP_API}#schedule_strategy_summary",
        [_page(OP_SCHEDULE, "教学班KPI", f"{OP_VIEW}/ScheduleAnalysis.vue", usage_type="kpi")],
    ),
    _metric(
        "TA.OP.SCHEDULE.MEETING_COUNT", "教学运行分析", "排课节次记录数",
        "COUNT(lesson_meeting)",
        "统计排课 meeting 明细记录总数。",
        "按 meeting 记录计数，不按连续节次拆分。",
        "筛选范围×学期", "lesson_meeting", f"{OP_API}#schedule_strategy_summary",
        [_page(OP_SCHEDULE, "排课节次KPI", f"{OP_VIEW}/ScheduleAnalysis.vue", usage_type="kpi")], unit="条",
    ),
    _metric(
        "TA.OP.SCHEDULE.CELL_MEETING_COUNT", "教学运行分析", "标准化周次节次量",
        "Σ meeting_weeks × meeting_period_length",
        "将每条排课记录展开为周次与节次单元，用作时段结构分母。",
        "由周次集合和节次跨度推导；不是数据库 meeting 行数。",
        "筛选范围×学期", "lesson_meeting.weeks/periods", f"{OP_API}#schedule_strategy_summary",
        [_page(OP_SCHEDULE, "节次结构总量", f"{OP_VIEW}/ScheduleAnalysis.vue", usage_type="tooltip")], unit="周节次",
    ),
    _metric(
        "TA.OP.SCHEDULE.PEAK_MEETING_COUNT", "教学运行分析", "高峰周次节次量",
        "Σ cell WHERE period in 高峰节次集合",
        "统计落入后端高峰节次集合的标准化周次节次量。",
        "高峰节次集合由接口规则固定，不是用户可配置口径。",
        "筛选范围×学期", "lesson_meeting.periods", f"{OP_API}#schedule_strategy_summary",
        [_page(OP_SCHEDULE, "高峰占比计算分子", f"{OP_API}#schedule_strategy_summary", usage_type="hidden column", description="作为页面高峰占比的接口计算分子，未单独展示。")], unit="周节次",
    ),
    _metric(
        "TA.OP.SCHEDULE.PEAK_SHARE", "教学运行分析", "高峰时段占比",
        "高峰周次节次量 / 标准化周次节次量 × 100%",
        "观察排课向高峰节次集中的程度。",
        "分子分母都使用标准化周次节次量。",
        "筛选范围×学期", "lesson_meeting", f"{OP_API}#schedule_strategy_summary",
        [_page(OP_SCHEDULE, "高峰时段占比KPI", f"{OP_VIEW}/ScheduleAnalysis.vue", usage_type="kpi")], unit="%",
    ),
    _metric(
        "TA.OP.SCHEDULE.EVENING_MEETINGS", "教学运行分析", "晚间排课记录数",
        "COUNT(lesson_meeting WHERE period_start >= 9)",
        "统计起始节次达到晚间边界的排课记录数。",
        "按 meeting 记录计数，而非标准化周次节次量。",
        "筛选范围×学期", "lesson_meeting", f"{OP_API}#schedule_strategy_summary",
        [_page(OP_SCHEDULE, "晚间排课KPI", f"{OP_VIEW}/ScheduleAnalysis.vue", usage_type="kpi")], unit="条",
    ),
    _metric(
        "TA.OP.SCHEDULE.EVENING_SHARE", "教学运行分析", "晚间排课占比",
        "晚间排课记录数 / 排课节次记录数 × 100%",
        "观察晚间排课记录在全部排课记录中的占比。",
        "按记录口径计算，不得与周次节次占比混用。",
        "筛选范围×学期", "lesson_meeting", f"{OP_API}#schedule_strategy_summary",
        [_page(OP_SCHEDULE, "晚间排课占比", f"{OP_VIEW}/ScheduleAnalysis.vue", usage_type="tooltip")], unit="%",
    ),
    _metric(
        "TA.OP.SCHEDULE.FOCUS_COURSE_COUNT", "教学运行分析", "重点关注课程数",
        "COUNT(DISTINCT course_id WHERE course_name 命中重点课程关键词)",
        "统计名称命中重点课程关键词规则的去重课程数。",
        "关键词匹配是当前实现的识别办法，不代表正式课程分类。",
        "筛选范围×学期", "teaching_lesson.course_name", f"{OP_API}#schedule_strategy_summary",
        [_page(OP_SCHEDULE, "重点课程KPI", f"{OP_VIEW}/ScheduleAnalysis.vue", usage_type="kpi")],
    ),
    _metric(
        "TA.OP.SCHEDULE.FOCUS_LESSON_COUNT", "教学运行分析", "重点课程教学班数",
        "COUNT(DISTINCT teaching_lesson.id WHERE 课程命中重点关键词)",
        "统计重点关注课程对应的教学班数。",
        "课程由名称关键词识别。",
        "筛选范围×学期", "teaching_lesson", f"{OP_API}#schedule_strategy_summary",
        [_page(OP_SCHEDULE, "重点课程教学班", f"{OP_VIEW}/ScheduleAnalysis.vue")],
    ),
    _metric(
        "TA.OP.SCHEDULE.FOCUS_MEETING_COUNT", "教学运行分析", "重点课程排课记录数",
        "COUNT(lesson_meeting WHERE 所属课程命中重点关键词)",
        "统计重点关注课程的排课 meeting 数量。",
        "按 meeting 记录计数。",
        "筛选范围×学期", "lesson_meeting", f"{OP_API}#schedule_strategy_summary",
        [_page(OP_SCHEDULE, "重点课程排课记录", f"{OP_VIEW}/ScheduleAnalysis.vue")], unit="条",
    ),
    _metric(
        "TA.OP.SCHEDULE.FOCUS_STUDENT_VISITS", "教学运行分析", "重点课程修读人次",
        "SUM(teaching_lesson.enrolled WHERE 课程命中重点关键词)",
        "汇总重点关注课程教学班的修读人次。",
        "同一学生跨课程重复计数。",
        "筛选范围×学期", "teaching_lesson.enrolled", f"{OP_API}#schedule_strategy_summary",
        [_page(OP_SCHEDULE, "重点课程修读人次", f"{OP_VIEW}/ScheduleAnalysis.vue")], unit="人次",
    ),
    _metric(
        "TA.OP.SCHEDULE.FOCUS_PEAK_SHARE", "教学运行分析", "重点课程高峰占比",
        "重点课程高峰周次节次量 / 重点课程标准化周次节次量 × 100%",
        "观察重点关注课程在高峰节次的集中程度。",
        "仅统计关键词识别出的重点课程。",
        "筛选范围×学期", "lesson_meeting", f"{OP_API}#schedule_strategy_summary",
        [_page(OP_SCHEDULE, "重点课程高峰占比", f"{OP_VIEW}/ScheduleAnalysis.vue")], unit="%",
    ),
    _metric(
        "TA.OP.SCHEDULE.FOCUS_EVENING_SHARE", "教学运行分析", "重点课程晚间排课占比",
        "重点课程晚间 meeting 数 / 重点课程 meeting 数 × 100%",
        "观察重点关注课程的晚间排课比例。",
        "分子分母均按 meeting 记录计数。",
        "筛选范围×学期", "lesson_meeting", f"{OP_API}#schedule_strategy_summary",
        [_page(OP_SCHEDULE, "重点课程晚间占比", f"{OP_VIEW}/ScheduleAnalysis.vue")], unit="%",
    ),
    _metric(
        "TA.OP.SCHEDULE.COURSE_TEACHER_COUNT", "教学运行分析", "授课教师数（排课策略）",
        "COUNT(DISTINCT lesson_teacher.teacher_id)",
        "统计课程教学班绑定的去重授课教师数。",
        "来源为 lesson_teacher，包含绑定教师；不得与课程供给页主讲教师数合并。",
        "课程×学期", "lesson_teacher", f"{OP_API}#schedule_strategy_summary",
        [_page(OP_SCHEDULE, "课程明细-教师数", f"{OP_VIEW}/ScheduleAnalysis.vue")], unit="人",
    ),
    _metric(
        "TA.OP.SCHEDULE.COURSE_AVG_CLASS_SIZE", "教学运行分析", "平均班额（排课策略）",
        "AVG(NULLIF(teaching_lesson.enrolled, 0))",
        "按课程计算非零教学班的平均班额。",
        "enrolled=0 的教学班不进入平均值；不得与课程供给平均班额合并。",
        "课程×学期", "teaching_lesson.enrolled", f"{OP_API}#schedule_strategy_summary",
        [_page(OP_SCHEDULE, "课程明细-平均班额", f"{OP_VIEW}/ScheduleAnalysis.vue")], unit="人/班",
    ),
    _metric(
        "TA.OP.SCHEDULE.COURSE_WEEKDAY_COVERAGE", "教学运行分析", "课程上课日覆盖数",
        "COUNT(DISTINCT weekday WHERE 课程存在排课)",
        "统计课程排课覆盖的星期数。",
        "只统计可解析的星期字段。",
        "课程×学期", "lesson_meeting.weekday", f"{OP_API}#schedule_strategy_summary",
        [_page(OP_SCHEDULE, "课程明细-上课日", f"{OP_VIEW}/ScheduleAnalysis.vue", usage_type="tooltip")], unit="天",
    ),

    # 教学运行分析：教室运行。
    _metric(
        "TA.OP.CLASSROOM.OCCUPANCY_RECORDS", "教学运行分析", "教室占用记录数",
        "COUNT(classroom_occupancy)",
        "统计当前范围内的教室占用明细记录。",
        "按占用记录行计数，不代表教室数量或课时数。",
        "筛选范围×学期", "classroom_occupancy", f"{OP_API}#classroom_summary",
        [_page(OP_CLASSROOM, "占用记录KPI", CLASSROOM_VIEW, usage_type="kpi")], unit="条",
    ),
    _metric(
        "TA.OP.CLASSROOM.OBSERVED_ROOMS", "教学运行分析", "观测教室数",
        "COUNT(DISTINCT classroom_id)",
        "统计占用数据中实际出现的去重教室数。",
        "不是学校全部可用教室数。",
        "筛选范围×学期", "classroom_occupancy.classroom_id", f"{OP_API}#classroom_summary",
        [_page(OP_CLASSROOM, "观测教室KPI", CLASSROOM_VIEW, usage_type="kpi")], unit="间",
    ),
    _metric(
        "TA.OP.CLASSROOM.OBSERVED_DATES", "教学运行分析", "观测日期数",
        "COUNT(DISTINCT occupied_date)",
        "统计占用数据覆盖的去重日期数。",
        "只反映有记录的日期覆盖，不代表完整教学日历。",
        "筛选范围×学期", "classroom_occupancy.occupied_date", f"{OP_API}#classroom_summary",
        [_page(OP_CLASSROOM, "观测日期KPI", CLASSROOM_VIEW, usage_type="kpi")], unit="天",
    ),
    _metric(
        "TA.OP.CLASSROOM.OVERLAP_COUNT", "教学运行分析", "教室冲突数",
        "COUNT(occupancy WHERE overlap/conflict flag)",
        "统计教室占用时段存在重叠冲突的记录数。",
        "依赖当前占用明细的冲突判定字段。",
        "筛选范围×学期", "classroom_occupancy", f"{OP_API}#classroom_summary",
        [_page(OP_CLASSROOM, "冲突数KPI", CLASSROOM_VIEW, usage_type="kpi")],
    ),
    _metric(
        "TA.OP.CLASSROOM.PENDING_MAPPING_COUNT", "教学运行分析", "待映射场地记录数",
        "COUNT(occupancy WHERE classroom mapping missing)",
        "统计未能映射到标准教室维表的占用记录。",
        "用于数据质量核查，不等于排课冲突。",
        "筛选范围×学期", "classroom_occupancy", f"{OP_API}#classroom_summary",
        [_page(OP_CLASSROOM, "待映射KPI", CLASSROOM_VIEW, usage_type="kpi")], unit="条",
    ),
    _metric(
        "TA.OP.CLASSROOM.EVENING_COUNT", "教学运行分析", "晚间教室占用记录数",
        "COUNT(occupancy WHERE period_start >= 9)",
        "统计晚间时段的教室占用记录。",
        "按记录计数，不展开周次或连续节次。",
        "筛选范围×学期", "classroom_occupancy", f"{OP_API}#classroom_summary",
        [_page(OP_CLASSROOM, "晚间占用KPI", CLASSROOM_VIEW, usage_type="kpi")], unit="条",
    ),
    _metric(
        "TA.OP.CLASSROOM.OCCUPIED_ROOM_DAYS", "教学运行分析", "已占用教室日数",
        "COUNT(DISTINCT classroom_id, occupied_date)",
        "统计实际出现占用记录的教室与日期组合数。",
        "不含无占用记录的教室日。",
        "筛选范围×学期", "classroom_occupancy", f"{OP_API}#classroom_summary",
        [_page(OP_CLASSROOM, "教室日负载计算分子", f"{OP_API}#classroom_summary", usage_type="hidden column", description="用于接口计算观测教室日负载，当前页面未单独展示。")], unit="教室日",
    ),
    _metric(
        "TA.OP.CLASSROOM.OBSERVED_OPPORTUNITIES", "教学运行分析", "观测教室日机会数",
        "观测教室数 × 观测日期数",
        "构造当前有记录教室与有记录日期的笛卡尔观测机会数。",
        "不是正式可供使用教室时段容量，仅为观测基数。",
        "筛选范围×学期", "classroom_occupancy", f"{OP_API}#classroom_summary",
        [_page(OP_CLASSROOM, "教室日负载计算分母", f"{OP_API}#classroom_summary", usage_type="hidden column", description="用于接口计算观测教室日负载，当前页面未单独展示。")], unit="教室日",
    ),
    _metric(
        "TA.OP.CLASSROOM.PERIOD_OBSERVED_LOAD", "教学运行分析", "时段观测负载",
        "星期×节次占用教室日数 / (全部观测教室数 × 该星期实际观测日期数) × 100%",
        "描述指定星期与节次网格中已观测教室发生占用的比例。",
        "缺少全量可用教室、开放日和可用节次，不能解释为正式教室利用率。",
        "星期×节次×学期", "fact_room_occupancy / fact_room_occupancy_period", f"{OP_API}#classroom_occupancy",
        [_page(OP_CLASSROOM, "占用时序热力图", f"{OP_VIEW}/Classroom.vue", usage_type="chart")], unit="%",
    ),
    _metric(
        "TA.OP.CLASSROOM.PEAK_LOAD", "教学运行分析", "最高时段观测负载",
        "MAX(星期×节次时段观测负载)",
        "展示全部星期与节次网格中的最高观测占用比例。",
        "是观测网格最大值，不是高峰容量利用率。",
        "筛选范围×学期", "fact_room_occupancy / fact_room_occupancy_period", f"{OP_API}#classroom_occupancy",
        [_page(OP_CLASSROOM, "最高时段负载KPI", f"{OP_VIEW}/Classroom.vue", usage_type="kpi")], unit="%",
    ),
    _metric(
        "TA.OP.CLASSROOM.OCCUPIED_ROOM_SLOTS", "教学运行分析", "占用教室时段数",
        "COUNT(DISTINCT classroom_id, occupied_date, period)",
        "按教室、日期和节次去重统计占用时段。",
        "只统计已有占用记录中的时段。",
        "楼宇×日期/时段×学期", "classroom_occupancy", f"{OP_API}#classroom_summary",
        [_page(OP_CLASSROOM, "楼宇负载-占用时段", CLASSROOM_VIEW)], unit="教室时段",
    ),
    _metric(
        "TA.OP.CLASSROOM.BUILDING_LOAD", "教学运行分析", "楼宇观测负载",
        "楼宇占用教室日数 / (楼宇观测教室数 × 全部观测日期数) × 100%",
        "比较不同楼宇在观测数据中的占用负载。",
        "观测口径不含正式容量分母，不能作为正式楼宇利用率。",
        "楼宇×学期", "classroom_occupancy", f"{OP_API}#classroom_summary",
        [_page(OP_CLASSROOM, "楼宇负载表", CLASSROOM_VIEW)], unit="%",
    ),
    _metric(
        "TA.OP.CLASSROOM.ACTIVITY_COUNT", "教学运行分析", "活动类型占用记录数",
        "COUNT(DISTINCT occupancy_id) GROUP BY activity_type",
        "按活动类型统计去重教室占用事件数量。",
        "同一占用事件跨多个节次只计一次。",
        "活动类型×学期", "fact_room_occupancy", f"{OP_API}#classroom_occupancy",
        [_page(OP_CLASSROOM, "占用活动构成", f"{OP_VIEW}/Classroom.vue", usage_type="chart")], unit="条",
    ),

    # 教学运行分析：教师工作量。
    _metric(
        "TA.OP.LOAD.ACTIVE_TEACHERS", "教学运行分析", "有工作量教师数",
        "COUNT(DISTINCT teacher_id WHERE agg_teacher_load 有有效记录)",
        "统计教师工作量聚合表中当前范围内的去重教师数。",
        "使用工作量页的异常教师清洗口径；不同于师资保障页教师任务来源。",
        "筛选范围×学期", "agg_teacher_load", f"{OP_API}#teacher_load_summary",
        [_page(OP_LOAD, "教师数KPI", f"{OP_VIEW}/TeacherLoad.vue", usage_type="kpi")], unit="人",
    ),
    _metric(
        "TA.OP.LOAD.TOTAL_HOURS", "教学运行分析", "总工作量学时",
        "SUM(agg_teacher_load.total_hours)",
        "汇总当前范围教师工作量学时。",
        "依赖上游 total_hours 口径，页面不再重新折算。",
        "筛选范围×学期", "agg_teacher_load.total_hours", f"{OP_API}#teacher_load_summary",
        [_page(OP_LOAD, "总学时KPI", f"{OP_VIEW}/TeacherLoad.vue", usage_type="kpi")], unit="学时",
    ),
    _metric(
        "TA.OP.LOAD.AVG_HOURS", "教学运行分析", "教师平均工作量",
        "总工作量学时 / 有工作量教师数",
        "观察当前范围教师人均工作量学时。",
        "分母仅包含工作量聚合表中的有效教师。",
        "筛选范围×学期", "agg_teacher_load", f"{OP_API}#teacher_load_summary",
        [_page(OP_LOAD, "平均学时KPI", f"{OP_VIEW}/TeacherLoad.vue", usage_type="kpi")], unit="学时/人",
    ),
    _metric(
        "TA.OP.LOAD.MEDIAN_HOURS", "教学运行分析", "教师工作量中位数",
        "MEDIAN(total_hours)",
        "展示教师工作量分布中位水平。",
        "按当前总体、学院或职称筛选范围分别计算。",
        "统计范围×学期", "agg_teacher_load.total_hours", f"{OP_API}#teacher_load_summary",
        [_page(OP_LOAD, "工作量中位数KPI", f"{OP_VIEW}/TeacherLoad.vue", usage_type="kpi"), _page(OP_LOAD, "学院/职称工作量中位数", f"{OP_VIEW}/TeacherLoad.vue")], unit="学时",
    ),
    _metric(
        "TA.OP.LOAD.P90_HOURS", "教学运行分析", "教师工作量P90",
        "PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY total_hours)",
        "展示教师工作量分布第90百分位，并参与高工作量复核队列。",
        "按当前总体、学院或职称筛选范围分别计算；是相对阈值而非正式超载线。",
        "统计范围×学期", "agg_teacher_load.total_hours", f"{OP_API}#teacher_load_summary",
        [_page(OP_LOAD, "工作量P90 KPI", f"{OP_VIEW}/TeacherLoad.vue", usage_type="kpi"), _page(OP_LOAD, "学院/职称工作量P90", f"{OP_VIEW}/TeacherLoad.vue")], unit="学时",
    ),
    _metric(
        "TA.OP.LOAD.AVG_COURSES", "教学运行分析", "教师平均承担课程数",
        "AVG(agg_teacher_load.course_count)",
        "观察教师平均承担课程门数。",
        "按工作量聚合记录计算；按总体、学院或职称范围分别汇总。",
        "统计范围×学期", "agg_teacher_load.course_count", f"{OP_API}#teacher_load_summary",
        [_page(OP_LOAD, "平均课程数KPI", f"{OP_VIEW}/TeacherLoad.vue", usage_type="kpi"), _page(OP_LOAD, "学院/职称平均课程数", f"{OP_VIEW}/TeacherLoad.vue")], unit="门/人",
    ),
    _metric(
        "TA.OP.LOAD.AVG_CLASSES", "教学运行分析", "教师平均承担教学班数",
        "AVG(agg_teacher_load.class_count)",
        "观察教师平均承担教学班数量。",
        "按有效工作量教师记录求平均。",
        "筛选范围×学期", "agg_teacher_load.class_count", f"{OP_API}#teacher_load_summary",
        [_page(OP_LOAD, "平均教学班数KPI", f"{OP_VIEW}/TeacherLoad.vue", usage_type="kpi")], unit="班/人",
    ),
    _metric(
        "TA.OP.LOAD.STUDENT_VISITS", "教学运行分析", "教师承担修读人次",
        "agg_teacher_load.student_count",
        "展示单名教师承担课程对应的修读人次。",
        "接口字段名 student_count，实际为上游聚合人次，不保证学生去重。",
        "教师×学期", "agg_teacher_load.student_count", f"{OP_API}#teacher_load_summary",
        [_page(OP_LOAD, "教师明细-修读人次", f"{OP_VIEW}/TeacherLoad.vue")], unit="人次",
    ),
    _metric(
        "TA.OP.LOAD.AVG_CLASS_SIZE", "教学运行分析", "教师平均班额",
        "teacher.student_count / teacher.class_count",
        "估算单名教师承担教学班的平均修读规模。",
        "分子为工作量表 student_count 聚合值，非去重学生数。",
        "教师×学期", "agg_teacher_load", f"{OP_API}#teacher_load_summary",
        [_page(OP_LOAD, "教师明细-平均班额", f"{OP_VIEW}/TeacherLoad.vue")], unit="人/班",
    ),
    _metric(
        "TA.OP.LOAD.EXCLUDED_TEACHERS", "教学运行分析", "异常教师排除数（工作量）",
        "COUNT(DISTINCT teacher_id WHERE 教师启发式异常)",
        "记录工作量统计前排除的异常教师标识数量。",
        "接口返回的数据质量说明项，当前页面不单独展示。",
        "筛选范围×学期", "agg_teacher_load.teacher_id", f"{OP_API}#teacher_load_summary",
        [_page(OP_LOAD, "接口返回-异常教师排除数", f"{OP_API}#teacher_load_summary", usage_type="hidden column", description="接口返回但当前页面未展示的数据质量字段。")], unit="人",
    ),
    _metric(
        "TA.OP.LOAD.COLLEGE_RELATIVE_LEVEL", "教学运行分析", "学院相对负荷水平",
        "学院P90学时 / 当前范围学院P90最大值 × 100%",
        "将学院P90学时相对当前范围最大值归一化，用于页面排序与关注提示。",
        "是相对位置而非正式超载线；前3名及相对值大于60%的提示由前端生成。",
        "学院×学期", "agg_teacher_load.total_hours", f"{OP_API}#teacher_load_summary",
        [_page(OP_LOAD, "学院相对负荷进度", f"{OP_VIEW}/TeacherLoad.vue"), _page(OP_LOAD, "学院关注排序", f"{OP_VIEW}/TeacherLoad.vue", usage_type="sort")], unit="%",
    ),

    # 教学运行分析：调停课。
    _metric(
        "TA.OP.CHANGE.EVENT_COUNT", "教学运行分析", "调停课事件数",
        "COUNT(schedule_change_event)",
        "统计当前范围内全部调课与停课事件。",
        "按事件记录计数，同一教学班可发生多次。",
        "筛选范围×学期", "schedule_change_event", f"{OP_API}#schedule_change_summary",
        [_page(OP_CHANGES, "事件总数KPI", f"{OP_VIEW}/ScheduleChanges.vue", usage_type="kpi")], unit="次",
    ),
    _metric(
        "TA.OP.CHANGE.CHANGE_COUNT", "教学运行分析", "调课事件数",
        "COUNT(event WHERE type=调课)",
        "统计调课类型事件数量。",
        "类型按当前事件表标准化结果判定。",
        "筛选范围×学期", "schedule_change_event.event_type", f"{OP_API}#schedule_change_summary",
        [_page(OP_CHANGES, "调课事件KPI", f"{OP_VIEW}/ScheduleChanges.vue", usage_type="kpi")], unit="次",
    ),
    _metric(
        "TA.OP.CHANGE.STOP_COUNT", "教学运行分析", "停课事件数",
        "COUNT(event WHERE type=停课)",
        "统计停课类型事件数量。",
        "类型按当前事件表标准化结果判定。",
        "筛选范围×学期", "schedule_change_event.event_type", f"{OP_API}#schedule_change_summary",
        [_page(OP_CHANGES, "停课事件KPI", f"{OP_VIEW}/ScheduleChanges.vue", usage_type="kpi")], unit="次",
    ),
    _metric(
        "TA.OP.CHANGE.STOP_SHARE", "教学运行分析", "停课事件占比",
        "停课事件数 / 调停课事件数 × 100%",
        "观察调停课事件中停课事件的构成。",
        "分母为当前筛选范围全部调停课事件。",
        "筛选范围×学期", "schedule_change_event", f"{OP_API}#schedule_change_summary",
        [_page(OP_CHANGES, "停课占比", f"{OP_VIEW}/ScheduleChanges.vue", usage_type="tooltip")], unit="%",
    ),
    _metric(
        "TA.OP.CHANGE.AFFECTED_VISITS", "教学运行分析", "调停课影响修读人次",
        "SUM(event.affected_students)",
        "汇总调停课事件记录的影响学生人次。",
        "同一学生受多次事件影响会重复计数。",
        "筛选范围×学期", "schedule_change_event.affected_students", f"{OP_API}#schedule_change_summary",
        [_page(OP_CHANGES, "影响人次KPI", f"{OP_VIEW}/ScheduleChanges.vue", usage_type="kpi")], unit="人次",
    ),
    _metric(
        "TA.OP.CHANGE.TEACHER_COUNT", "教学运行分析", "涉及教师数",
        "COUNT(DISTINCT teacher_id)",
        "统计发生调停课事件的去重教师数。",
        "依赖事件教师标识；缺失教师不计入。",
        "筛选范围×学期", "schedule_change_event.teacher_id", f"{OP_API}#schedule_change_summary",
        [_page(OP_CHANGES, "涉及教师KPI", f"{OP_VIEW}/ScheduleChanges.vue", usage_type="kpi")], unit="人",
    ),
    _metric(
        "TA.OP.CHANGE.REASON_COVERAGE", "教学运行分析", "调停课原因覆盖率",
        "有非空原因事件数 / 全部调停课事件数 × 100%",
        "衡量调停课事件原因字段的填写覆盖程度。",
        "只判断原因非空，不代表原因真实、完整或已分类。",
        "筛选范围×学期", "schedule_change_event.reason", f"{OP_API}#schedule_change_summary",
        [_page(OP_CHANGES, "原因覆盖率KPI", f"{OP_VIEW}/ScheduleChanges.vue", usage_type="kpi")], unit="%",
    ),
    _metric(
        "TA.OP.CHANGE.COLLEGE_VALID_LESSONS", "教学运行分析", "学院有效开课教学班数（调停课）",
        "COUNT(DISTINCT teaching_lesson.id WHERE 有有效排课)",
        "作为学院调停课发生率的分母。",
        "分母来自有效开课教学班，不是学院课程数。",
        "学院×学期", "teaching_lesson", f"{OP_API}#schedule_change_summary",
        [_page(OP_CHANGES, "学院发生率分母", f"{OP_VIEW}/ScheduleChanges.vue", usage_type="tooltip")],
    ),
    _metric(
        "TA.OP.CHANGE.COLLEGE_EVENT_COUNT", "教学运行分析", "学院调停课事件数",
        "COUNT(schedule_change_event) GROUP BY lesson_college",
        "按教学班归属学院统计调停课事件数。",
        "事件按教学班归属学院分组。",
        "学院×学期", "schedule_change_event", f"{OP_API}#schedule_change_summary",
        [_page(OP_CHANGES, "学院事件表-事件数", f"{OP_VIEW}/ScheduleChanges.vue")], unit="次",
    ),
    _metric(
        "TA.OP.CHANGE.COLLEGE_EVENT_RATE", "教学运行分析", "学院调停课发生率",
        "学院调停课事件数 / 学院有效开课教学班数 × 100%",
        "比较学院调停课事件相对开课教学班规模的发生程度。",
        "事件可多次发生，因此该值不是发生过事件的教学班比例，理论上可超过100%。",
        "学院×学期", "schedule_change_event / teaching_lesson", f"{OP_API}#schedule_change_summary",
        [_page(OP_CHANGES, "学院事件表-发生率", f"{OP_VIEW}/ScheduleChanges.vue")], unit="%",
    ),
    _metric(
        "TA.OP.CHANGE.REASON_EVENT_COUNT", "教学运行分析", "原因分类事件数",
        "COUNT(event) GROUP BY reason semantic category",
        "按原因关键词语义分类统计调停课事件。",
        "一条事件按当前规则归入单一原因类别；未命中归其他。",
        "原因类别×学期", "schedule_change_event.reason", f"{OP_API}#schedule_change_summary",
        [_page(OP_CHANGES, "原因分布-事件数", f"{OP_VIEW}/ScheduleChanges.vue", usage_type="chart")], unit="次",
    ),
    _metric(
        "TA.OP.CHANGE.REASON_EVENT_SHARE", "教学运行分析", "原因分类事件占比",
        "原因分类事件数 / 全部调停课事件数 × 100%",
        "展示调停课原因语义类别构成。",
        "原因为空或未命中关键词时归入其他类别。",
        "原因类别×学期", "schedule_change_event.reason", f"{OP_API}#schedule_change_summary",
        [_page(OP_CHANGES, "原因分布-占比", f"{OP_VIEW}/ScheduleChanges.vue", usage_type="tooltip")], unit="%",
    ),
    _metric(
        "TA.OP.CHANGE.FREQUENT_TEACHER_EVENTS", "教学运行分析", "教师调停课次数",
        "COUNT(event) GROUP BY teacher_id",
        "统计单名教师发生的调停课事件次数，用于频发教师清单。",
        "频发阈值为事件数大于等于3；教师原因抽屉存在已登记范围缺陷。",
        "教师×学期", "schedule_change_event.teacher_id", f"{OP_API}#schedule_change_summary",
        [_page(OP_CHANGES, "频发教师清单", f"{OP_VIEW}/ScheduleChanges.vue"), _page(OP_CHANGES, "教师原因抽屉", f"{OP_VIEW}/ScheduleChanges.vue", usage_type="drilldown")], unit="次",
    ),
    _metric(
        "TA.OP.CHANGE.MONTHLY_EVENTS", "教学运行分析", "月度调停课事件数",
        "COUNT(event) GROUP BY calendar_month",
        "按自然月展示调停课事件趋势。",
        "月份由事件日期解析；日期缺失记录不进入有效月份。",
        "月份×学期", "schedule_change_event.event_date", f"{OP_API}#schedule_change_summary",
        [_page(OP_CHANGES, "月度事件趋势", f"{OP_VIEW}/ScheduleChanges.vue", usage_type="chart")], unit="次",
    ),

    # 教学运行分析：课程结果质量。
    _metric(
        "TA.OP.RESULT.OBSERVED_COURSES", "教学运行分析", "观测课程数",
        "COUNT(DISTINCT course_id WHERE 存在有效成绩尝试)",
        "统计当前范围具有有效课程成绩记录的课程数。",
        "只覆盖进入课程结果聚合的课程。",
        "筛选范围×学期", "fact_grade / agg_course_pass_stat", f"{OP_API}#course_result_quality",
        [_page(OP_RESULTS, "观测课程KPI", f"{OP_VIEW}/CourseQuality.vue", usage_type="kpi")], unit="门",
    ),
    _metric(
        "TA.OP.RESULT.ALL_ATTEMPTS", "教学运行分析", "全部有效成绩尝试数",
        "COUNT(valid grade attempt)",
        "统计课程结果质量范围内的全部有效考试尝试。",
        "学生同课程的首考、补考、重修尝试可分别计数。",
        "课程×学期/阶段", "fact_grade", f"{OP_API}#course_result_quality",
        [_page(OP_RESULTS, "总成绩人次KPI", f"{OP_VIEW}/CourseQuality.vue", usage_type="kpi")], unit="人次",
    ),
    _metric(
        "TA.OP.RESULT.FAIL_ATTEMPTS", "教学运行分析", "未通过成绩尝试数",
        "COUNT(valid grade attempt WHERE passed=false)",
        "统计全部有效成绩尝试中的未通过人次。",
        "按考试尝试计数，不按学生或课程去重。",
        "课程×学期/阶段", "fact_grade", f"{OP_API}#course_result_quality",
        [_page(OP_RESULTS, "未通过人次KPI", f"{OP_VIEW}/CourseQuality.vue", usage_type="kpi")], unit="人次",
    ),
    _metric(
        "TA.OP.RESULT.OVERALL_FAIL_RATE", "教学运行分析", "全部尝试未通过率",
        "未通过成绩尝试数 / 全部有效成绩尝试数 × 100%",
        "衡量当前范围全部有效成绩尝试的未通过比例。",
        "包含首考、补考和重修等阶段，不等同于接口行字段 fail_rate 的首考未通过率。",
        "筛选范围×学期", "fact_grade", f"{OP_API}#course_result_quality",
        [_page(OP_RESULTS, "整体未通过率KPI", f"{OP_VIEW}/CourseQuality.vue", usage_type="kpi")], unit="%",
    ),
    _metric(
        "TA.OP.RESULT.STUDENT_TERM_COUNT", "教学运行分析", "学生学期观测数",
        "COUNT(DISTINCT student_id, semester)",
        "统计课程质量分析覆盖的学生与学期组合数。",
        "是学生学期组合，不是去重学生数。",
        "筛选范围", "fact_grade", f"{OP_API}#course_result_quality",
        [_page(OP_RESULTS, "学生学期观测KPI", f"{OP_VIEW}/CourseQuality.vue", usage_type="kpi")], unit="学生学期",
    ),
    _metric(
        "TA.OP.RESULT.FIRST_ATTEMPTS", "教学运行分析", "首考有效尝试数",
        "COUNT(valid grade attempt WHERE stage=first)",
        "作为首考通过率和首考未通过率的共同分母。",
        "按首考成绩尝试计数，不按学生去重。",
        "课程×学期", "agg_course_pass_stat.first_total", f"{OP_API}#course_result_quality",
        [_page(OP_RESULTS, "课程表-首考样本", f"{OP_VIEW}/CourseQuality.vue", usage_type="tooltip")], unit="人次",
    ),
    _metric(
        "TA.OP.RESULT.FIRST_PASS_ATTEMPTS", "教学运行分析", "首考通过人次",
        "COUNT(valid grade attempt WHERE stage=first AND passed=true)",
        "作为课程首考通过率的分子。",
        "按首考成绩尝试计数。",
        "课程×学期", "agg_course_pass_stat.first_pass", f"{OP_API}#course_result_quality",
        [_page(OP_RESULTS, "首考通过率计算分子", f"{OP_API}#course_result_quality", usage_type="hidden column", description="接口计算稳定指标C-05/C-18的分子，当前页面未单列。")], unit="人次",
    ),
    _metric(
        "TA.OP.RESULT.FIRST_FAIL_RATE", "教学运行分析", "课程首考未通过率",
        "(首考有效尝试数 - 首考通过人次) / 首考有效尝试数 × 100%",
        "展示课程首考阶段的未通过比例。",
        "接口课程行字段名为 fail_rate；不得与页面总体全部尝试未通过率合并。",
        "课程×学期", "agg_course_pass_stat", f"{OP_API}#course_result_quality",
        [_page(OP_RESULTS, "课程表-未通过率", f"{OP_VIEW}/CourseQuality.vue")], unit="%",
    ),
    _metric(
        "TA.OP.RESULT.MAKEUP_ATTEMPTS", "教学运行分析", "补考有效尝试数",
        "COUNT(valid grade attempt WHERE stage=makeup)",
        "作为补考通过率的分母。",
        "仅统计被识别为补考阶段的有效尝试。",
        "课程×学期", "agg_course_pass_stat.makeup_total", f"{OP_API}#course_result_quality",
        [_page(OP_RESULTS, "课程表-补考样本", f"{OP_VIEW}/CourseQuality.vue", usage_type="tooltip")], unit="人次",
    ),
    _metric(
        "TA.OP.RESULT.MAKEUP_PASS_ATTEMPTS", "教学运行分析", "补考通过人次",
        "COUNT(valid grade attempt WHERE stage=makeup AND passed=true)",
        "作为补考通过率的分子。",
        "按补考成绩尝试计数。",
        "课程×学期", "agg_course_pass_stat.makeup_pass", f"{OP_API}#course_result_quality",
        [_page(OP_RESULTS, "补考通过率计算分子", f"{OP_API}#course_result_quality", usage_type="hidden column", description="接口计算稳定指标G-13的分子，当前页面未单列。")], unit="人次",
    ),
    _metric(
        "TA.OP.RESULT.RETAKE_ATTEMPTS", "教学运行分析", "重修有效尝试数",
        "COUNT(valid grade attempt WHERE stage=retake)",
        "统计课程重修阶段的有效成绩尝试，亦作为重修通过率分母。",
        "课程明细的重修压力标记使用该样本量；当前样本范围存在已登记问题。",
        "课程×学期", "agg_course_pass_stat.retake_total", f"{OP_API}#course_result_quality",
        [_page(OP_RESULTS, "重修人次KPI", f"{OP_VIEW}/CourseQuality.vue", usage_type="kpi"), _page(OP_RESULTS, "课程表-重修样本", f"{OP_VIEW}/CourseQuality.vue", usage_type="tooltip")], unit="人次",
    ),
    _metric(
        "TA.OP.RESULT.RETAKE_PASS_ATTEMPTS", "教学运行分析", "重修通过人次",
        "COUNT(valid grade attempt WHERE stage=retake AND passed=true)",
        "作为重修通过率的分子。",
        "按重修成绩尝试计数。",
        "课程×学期", "agg_course_pass_stat.retake_pass", f"{OP_API}#course_result_quality",
        [_page(OP_RESULTS, "重修通过率计算分子", f"{OP_API}#course_result_quality", usage_type="hidden column", description="接口计算稳定指标G-16的分子，当前页面未单列。")], unit="人次",
    ),
    _metric(
        "TA.OP.RESULT.VOLATILITY", "教学运行分析", "课程首考未通过率波动",
        "MAX(term_first_fail_rate) - MIN(term_first_fail_rate)",
        "衡量课程跨学期首考未通过率的最大波动幅度。",
        "仅在可比且满足最小样本要求的学期序列上解释。",
        "课程×观测学期窗", "agg_course_pass_stat", f"{OP_API}#course_result_quality",
        [_page(OP_RESULTS, "课程表-波动", f"{OP_VIEW}/CourseQuality.vue"), _page(OP_RESULTS, "趋势下钻", f"{OP_VIEW}/CourseQuality.vue", usage_type="drilldown")], unit="百分点",
    ),
    _metric(
        "TA.OP.RESULT.PERSISTENT_HIGH_COUNT", "教学运行分析", "持续高未通过课程数",
        "COUNT(course WHERE 最近连续学期首考未通过率满足持续高位规则)",
        "统计跨学期持续高未通过的课程数量。",
        "依赖最小样本、连续学期和未通过率阈值规则。",
        "筛选范围×观测学期窗", "agg_course_pass_stat", f"{OP_API}#course_result_quality",
        [_page(OP_RESULTS, "持续高未通过KPI", f"{OP_VIEW}/CourseQuality.vue", usage_type="kpi")], unit="门",
    ),
    _metric(
        "TA.OP.RESULT.VOLATILE_COUNT", "教学运行分析", "波动课程数",
        "COUNT(course WHERE volatility > 15 percentage points)",
        "统计首考未通过率跨学期波动达到阈值的课程数。",
        "只有满足可比学期样本条件的课程进入判定。",
        "筛选范围×观测学期窗", "agg_course_pass_stat", f"{OP_API}#course_result_quality",
        [_page(OP_RESULTS, "波动课程KPI", f"{OP_VIEW}/CourseQuality.vue", usage_type="kpi")], unit="门",
    ),
    _metric(
        "TA.OP.RESULT.WIDE_IMPACT_COUNT", "教学运行分析", "广泛影响课程数",
        "COUNT(course WHERE 观察期累计未通过成绩尝试数 >= 50)",
        "统计观察期累计未通过达到50人次的课程。",
        "累计值包含当前接口汇总范围内各考试阶段；是关注标签，不是正式课程质量结论。",
        "筛选范围×学期", "agg_course_pass_stat", f"{OP_API}#course_result_quality",
        [_page(OP_RESULTS, "广泛影响标签", f"{OP_VIEW}/CourseQuality.vue")], unit="门",
    ),
    _metric(
        "TA.OP.RESULT.TERM_UNIQUE_STUDENTS", "教学运行分析", "课程学期去重学生数",
        "COUNT(DISTINCT student_id) GROUP BY course, semester",
        "在课程趋势下钻中展示各学期覆盖学生数。",
        "仅统计具有有效成绩尝试的学生。",
        "课程×学期", "fact_grade", f"{OP_API}#course_result_quality",
        [_page(OP_RESULTS, "课程趋势-学生数", f"{OP_VIEW}/CourseQuality.vue", usage_type="drilldown")], unit="人",
    ),
    _metric(
        "TA.OP.RESULT.TERM_AVG_SCORE", "教学运行分析", "课程学期平均成绩",
        "AVG(valid numeric score) GROUP BY course, semester",
        "在课程趋势下钻中展示各学期有效数值成绩均值。",
        "排除不能解析为数值的成绩；不按学分加权。",
        "课程×学期", "fact_grade.score", f"{OP_API}#course_result_quality",
        [_page(OP_RESULTS, "课程趋势-平均成绩", f"{OP_VIEW}/CourseQuality.vue", usage_type="drilldown")], unit="分",
    ),
)


_CURRICULUM_METRICS: tuple[dict, ...] = (
    _metric(
        "TA.CURR.PLAN.TOTAL_COUNT", "培养质量分析", "培养方案总数",
        "COUNT(training_plan)",
        "统计当前授权和筛选范围内的培养方案数量。",
        "按方案记录计数；历史版本是否并存取决于上游方案数据。",
        "培养方案×版本", "training_plan", f"{V2_API}#curriculum_quality_overview",
        [_page(CURRICULUM, "培养方案总数KPI", CURRICULUM_VIEW, usage_type="kpi")], unit="份",
    ),
    _metric(
        "TA.CURR.PLAN.REVIEWABLE_COUNT", "培养质量分析", "可核查培养方案数",
        "COUNT(plan WHERE plan_student_mapping 可形成核查总体)",
        "统计具备学生绑定或可形成进度核查范围的培养方案。",
        "以当前绑定数据可核查性为准，不代表方案已通过业务审核。",
        "筛选范围", "training_plan / plan_student_mapping", f"{V2_API}#curriculum_quality_overview",
        [_page(CURRICULUM, "可核查方案KPI", CURRICULUM_VIEW, usage_type="kpi")], unit="份",
    ),
    _metric(
        "TA.CURR.BINDING.APPLICABLE_STUDENTS", "培养质量分析", "方案适用学生数",
        "COUNT(DISTINCT active student matching plan grade/major scope)",
        "统计按年级、专业等条件应适用培养方案的去重学生数。",
        "总体口径来自方案适用范围推导，不以已有绑定记录为分母。",
        "培养方案/学生群体×学期", "dim_student / training_plan", f"{V2_API}#curriculum_quality_overview",
        [_page(CURRICULUM, "方案适用学生数", CURRICULUM_VIEW, usage_type="tooltip")], unit="人",
    ),
    _metric(
        "TA.CURR.BINDING.MATCHED_STUDENTS", "培养质量分析", "方案已匹配学生数",
        "COUNT(DISTINCT applicable student WHERE effective plan binding exists)",
        "统计适用学生中存在有效培养方案绑定的学生数。",
        "只统计当前有效绑定；不含待核查或外部来源占位记录。",
        "培养方案/学生群体×学期", "plan_student_mapping", f"{V2_API}#curriculum_quality_overview",
        [_page(CURRICULUM, "已匹配学生数", CURRICULUM_VIEW, usage_type="tooltip")], unit="人",
    ),
    _metric(
        "TA.CURR.BINDING.REVIEW_STUDENTS", "培养质量分析", "方案绑定待核查学生数",
        "COUNT(DISTINCT applicable student WHERE binding status requires review)",
        "统计适用方案绑定仍需人工核查的学生数。",
        "状态由当前方案绑定构建逻辑产生，不代表学生学业风险。",
        "培养方案/学生群体×学期", "plan_student_mapping", f"{V2_API}#curriculum_quality_overview",
        [_page(CURRICULUM, "绑定待核查人数", CURRICULUM_VIEW, usage_type="table")], unit="人",
    ),
    _metric(
        "TA.CURR.BINDING.OUTSIDE_SOURCE_STUDENTS", "培养质量分析", "外部来源绑定学生数",
        "COUNT(DISTINCT student WHERE binding source is outside inferred scope)",
        "统计方案绑定来源不在当前自动适用推导范围内的学生。",
        "用于识别历史导入或外部来源绑定，不直接判为错误。",
        "培养方案/学生群体×学期", "plan_student_mapping", f"{V2_API}#curriculum_quality_overview",
        [_page(CURRICULUM, "外部来源绑定人数", CURRICULUM_VIEW, usage_type="table")], unit="人",
    ),
    _metric(
        "TA.CURR.BINDING.OVERALL_RATE", "培养质量分析", "总体方案绑定率",
        "方案已匹配学生数 / 方案适用学生数 × 100%",
        "衡量当前范围内应适用方案学生的有效绑定覆盖。",
        "分母是推导出的适用学生总体；不得与分组表的已有映射记录分母合并。",
        "筛选范围×学期", "dim_student / plan_student_mapping", f"{V2_API}#curriculum_quality_overview",
        [_page(CURRICULUM, "总体绑定率KPI", CURRICULUM_VIEW, usage_type="kpi")], unit="%",
    ),
    _metric(
        "TA.CURR.BINDING.GROUP_RATE", "培养质量分析", "分组方案绑定率",
        "分组matched映射记录数 / 分组plan_student_mapping记录数 × 100%",
        "在方案分组表中展示已有绑定记录内部的匹配状态占比。",
        "分母仅为已有映射记录，与总体绑定率的适用学生分母不同。",
        "方案/年级/专业分组×学期", "plan_student_mapping", f"{V2_API}#curriculum_quality_overview",
        [_page(CURRICULUM, "方案分组表-绑定率", CURRICULUM_VIEW, usage_type="table")], unit="%",
    ),
    _metric(
        "TA.CURR.ACTION_STUDENTS", "培养质量分析", "需处置学生数",
        "COUNT(DISTINCT student_id WHERE binding_status='matched' AND failed_required_courses>0)",
        "统计培养进度或毕业准备状态达到需处置条件的学生。",
        "由当前方案规则和进度状态推导，不等同于正式学业预警人数。",
        "筛选范围×学期", "student_curriculum_progress", f"{V2_API}#curriculum_quality_overview",
        [_page(CURRICULUM, "需处置学生KPI", CURRICULUM_VIEW, usage_type="kpi"), _page(CURRICULUM_PROGRESS, "进度表-处置状态", CURRICULUM_VIEW)], unit="人",
    ),
    _metric(
        "TA.CURR.VERIFICATION_STUDENTS", "培养质量分析", "需核验学生数",
        "COUNT(DISTINCT student_id WHERE binding_status='matched' AND due_candidate_courses>0)",
        "统计数据或规则覆盖不足、需要进一步核验的学生。",
        "培养总览与毕业课程核查分别计算；毕业课程核查当前恒为0的问题已登记。",
        "筛选范围×学期", "student_curriculum_progress", f"{V2_API}#curriculum_quality_overview",
        [_page(CURRICULUM, "需核验学生KPI", CURRICULUM_VIEW, usage_type="kpi"), _page(CURRICULUM_GRADUATION, "毕业课程核查-需核验", CURRICULUM_VIEW)], unit="人",
    ),
    _metric(
        "TA.CURR.MODULE.RULE_COVERAGE", "培养质量分析", "模块规则覆盖率",
        "可评估模块数 / 培养方案模块总数 × 100%",
        "衡量培养方案模块是否具备可执行目标或课程规则。",
        "总体和学生明细可按各自模块集合计算；未配置规则模块不进入可评估数。",
        "培养方案/学生×学期", "training_plan_module", f"{V2_API}#curriculum_quality_overview",
        [_page(CURRICULUM, "模块规则覆盖率KPI", CURRICULUM_VIEW, usage_type="kpi"), _page(CURRICULUM_PROGRESS, "学生模块规则覆盖率", CURRICULUM_VIEW, usage_type="tooltip")], unit="%",
    ),
    _metric(
        "TA.CURR.BOTTLENECK.ACTION_COUNT", "培养质量分析", "行动类瓶颈数",
        "COUNT(module/course bottleneck WHERE status=action)",
        "统计培养方案中达到行动优先级的瓶颈项。",
        "瓶颈项可来自模块进度或课程保障；按接口项目计数。",
        "筛选范围×学期", "curriculum bottleneck aggregation", f"{V2_API}#curriculum_quality_overview",
        [_page(CURRICULUM, "行动类瓶颈KPI", CURRICULUM_VIEW, usage_type="kpi")], unit="项",
    ),
    _metric(
        "TA.CURR.BOTTLENECK.VERIFICATION_COUNT", "培养质量分析", "核验类瓶颈数",
        "COUNT(module/course bottleneck WHERE status=verification)",
        "统计因证据或规则不足进入核验优先级的瓶颈项。",
        "按接口瓶颈项目计数，不按学生去重。",
        "筛选范围×学期", "curriculum bottleneck aggregation", f"{V2_API}#curriculum_quality_overview",
        [_page(CURRICULUM, "核验类瓶颈KPI", CURRICULUM_VIEW, usage_type="kpi")], unit="项",
    ),
    _metric(
        "TA.CURR.BOTTLENECK.AFFECTED_MAJORS", "培养质量分析", "瓶颈影响专业数",
        "COUNT(DISTINCT major_id among bottleneck items)",
        "统计培养瓶颈清单涉及的去重专业数。",
        "只覆盖当前筛选与授权范围内的瓶颈项。",
        "筛选范围×学期", "curriculum bottleneck aggregation", f"{V2_API}#curriculum_quality_overview",
        [_page(CURRICULUM, "瓶颈影响专业KPI", CURRICULUM_VIEW, usage_type="kpi")], unit="个",
    ),
    _metric(
        "TA.CURR.PROGRESS.COVERED_STUDENTS", "培养质量分析", "培养进度覆盖学生数",
        "COUNT(DISTINCT student WHERE effective plan binding exists and progress is built)",
        "统计能够形成培养进度分析的去重学生数。",
        "须具有有效方案绑定并完成进度构建。",
        "筛选范围×学期", "student_curriculum_progress", f"{V2_API}#curriculum_progress",
        [_page(CURRICULUM_PROGRESS, "进度覆盖学生KPI", CURRICULUM_VIEW, usage_type="kpi")], unit="人",
    ),
    _metric(
        "TA.CURR.PROGRESS.ALL_MODULES_MET", "培养质量分析", "全部模块达标学生数",
        "COUNT(DISTINCT student WHERE every assessable module is met)",
        "统计所有可评估培养模块均达到要求的学生数。",
        "仅对可评估模块判断；无可评估模块不能直接解释为达标。",
        "筛选范围×学期", "student_curriculum_progress", f"{V2_API}#curriculum_progress",
        [_page(CURRICULUM_PROGRESS, "全部模块达标KPI", CURRICULUM_VIEW, usage_type="kpi")], unit="人",
    ),
    _metric(
        "TA.CURR.PROGRESS.CURRENT_TERM", "培养质量分析", "学生当前培养学期",
        "max(1, academic_year_offset × 2 + term_index)",
        "按学生入学年与当前学期推导其培养进度学期序号。",
        "依赖学期编码和入学年可解析；最低回退为第1学期。",
        "学生×学期", "dim_student / dim_semester", f"{GROWTH_ETL}#curriculum_progress",
        [_page(CURRICULUM_PROGRESS, "学生进度表-当前学期", CURRICULUM_VIEW)], unit="学期",
    ),
    _metric(
        "TA.CURR.PROGRESS.EARNED_CREDITS", "培养质量分析", "学生已获学分",
        "SUM(course_credit WHERE student has passing result)",
        "汇总学生已通过课程取得的学分。",
        "按通过结果和课程学分聚合；缺失学分课程不贡献学分。",
        "学生×学期", "fact_grade / dim_course.credit", f"{GROWTH_ETL}#curriculum_progress",
        [_page(CURRICULUM_PROGRESS, "学生进度表-已获学分", CURRICULUM_VIEW)], unit="学分",
    ),
    _metric(
        "TA.CURR.PROGRESS.MODULE_COUNT", "培养质量分析", "培养方案模块数",
        "COUNT(training_plan_module)",
        "统计学生适用培养方案包含的模块数量。",
        "按方案模块记录计数。",
        "学生/培养方案×学期", "training_plan_module", f"{V2_API}#curriculum_progress",
        [_page(CURRICULUM_PROGRESS, "学生进度表-模块数", CURRICULUM_VIEW, usage_type="tooltip")], unit="个",
    ),
    _metric(
        "TA.CURR.PROGRESS.ASSESSABLE_MODULE_COUNT", "培养质量分析", "可评估模块数",
        "COUNT(module WHERE credit target or course rule exists)",
        "统计具有可执行目标或课程规则、可以判定完成状态的模块数。",
        "纯说明性且无规则模块不进入。",
        "学生/培养方案×学期", "training_plan_module", f"{V2_API}#curriculum_progress",
        [_page(CURRICULUM_PROGRESS, "学生进度表-可评估模块数", CURRICULUM_VIEW, usage_type="tooltip")], unit="个",
    ),
    _metric(
        "TA.CURR.PROGRESS.COMPLETED_MODULE_COUNT", "培养质量分析", "已完成模块数",
        "COUNT(module WHERE is_assessable=1 AND is_complete=1；is_complete按可信最低学分、最低课程数/选修最低门数或全部必修课程规则判定)",
        "统计学生已经满足完成条件的培养模块数。",
        "模块完成条件受学分目标、必修课程和替代规则共同影响。",
        "学生×学期", "student_curriculum_progress", f"{V2_API}#curriculum_progress",
        [_page(CURRICULUM_PROGRESS, "学生进度表-已完成模块", CURRICULUM_VIEW)], unit="个",
    ),
    _metric(
        "TA.CURR.PROGRESS.FAILED_REQUIRED_COURSES", "培养质量分析", "必修未通过课程数",
        "COUNT(DISTINCT required course WHERE student has no passing result)",
        "统计学生适用方案中尚未通过的必修课程数。",
        "课程替代关系是否满足须按当前替代规则判定。",
        "学生×学期", "training_plan_course / fact_grade", f"{V2_API}#curriculum_progress",
        [_page(CURRICULUM_PROGRESS, "学生进度表-必修未通过", CURRICULUM_VIEW)], unit="门",
    ),
    _metric(
        "TA.CURR.PROGRESS.DUE_CANDIDATE_COURSES", "培养质量分析", "应修候选课程数",
        "COUNT(DISTINCT plan course WHERE recommended_term <= current_term and unmet)",
        "统计按建议学期已到应修时间但尚未满足的候选课程。",
        "只对可解析建议学期且未由替代课程满足的课程计数。",
        "学生×学期", "training_plan_course / fact_grade", f"{V2_API}#curriculum_progress",
        [_page(CURRICULUM_PROGRESS, "学生进度表-应修候选", CURRICULUM_VIEW, usage_type="tooltip")], unit="门",
    ),
    _metric(
        "TA.CURR.MODULE.TARGET_CREDITS", "培养质量分析", "模块目标学分",
        "training_plan_module.required_credits",
        "展示培养模块规定的目标学分。",
        "目标学分缺失时模块可能转由课程规则评估。",
        "学生×模块×学期", "training_plan_module.required_credits", f"{V2_API}#curriculum_progress",
        [_page(CURRICULUM_PROGRESS, "模块详情-目标学分", CURRICULUM_VIEW, usage_type="drilldown")], unit="学分",
    ),
    _metric(
        "TA.CURR.MODULE.ACHIEVED_CREDITS", "培养质量分析", "模块已获学分",
        "SUM(passed course credit assigned to module)",
        "汇总学生在指定培养模块下已经取得的学分。",
        "课程需能映射到该模块且具有可用学分。",
        "学生×模块×学期", "fact_grade / training_plan_course", f"{V2_API}#curriculum_progress",
        [_page(CURRICULUM_PROGRESS, "模块详情-已获学分", CURRICULUM_VIEW, usage_type="drilldown")], unit="学分",
    ),
    _metric(
        "TA.CURR.MODULE.COMPLETED_COURSES", "培养质量分析", "模块已完成课程数",
        "COUNT(DISTINCT module course WHERE student has passing result or valid substitution)",
        "统计学生在模块下已满足的课程数量。",
        "有效替代课程可满足原课程要求，按规则去重。",
        "学生×模块×学期", "training_plan_course / fact_grade", f"{V2_API}#curriculum_progress",
        [_page(CURRICULUM_PROGRESS, "模块详情-已完成课程", CURRICULUM_VIEW, usage_type="drilldown")], unit="门",
    ),
    _metric(
        "TA.CURR.GRADUATION.PLAN_COUNT", "培养质量分析", "毕业核查培养方案数",
        "COUNT(DISTINCT plan_id in graduation readiness scope)",
        "统计毕业准备核查覆盖的培养方案数量。",
        "只统计进入毕业准备核查范围的方案。",
        "筛选范围×学期", "training_plan", f"{V2_API}#graduation_readiness",
        [_page(CURRICULUM_GRADUATION, "毕业核查方案KPI", CURRICULUM_VIEW, usage_type="kpi")], unit="份",
    ),
    _metric(
        "TA.CURR.GRADUATION.EVIDENCE_COMPLETE_STUDENTS", "培养质量分析", "毕业证据完整学生数",
        "COUNT(DISTINCT student_id WHERE evidence_status NOT IN ('explicit_gap','candidate'))；即当前可评价模块中既无必修课程明确未通过，也无建议学期已过但缺少结果记录",
        "统计毕业准备证据链满足当前完整性规则的学生。",
        "是证据完整性，不代表已满足全部毕业条件。",
        "筛选范围×学期", "graduation_readiness_evidence", f"{V2_API}#graduation_readiness",
        [_page(CURRICULUM_GRADUATION, "证据完整学生KPI", CURRICULUM_VIEW, usage_type="kpi")], unit="人",
    ),
    _metric(
        "TA.CURR.GRADUATION.HIGH_GRADE_ACTION", "培养质量分析", "高年级需行动学生数",
        "COUNT(DISTINCT student_id WHERE entry_grade<=毕业年级阈值 AND readiness_status='action_required')",
        "统计高年级学生中毕业准备状态达到行动条件的人数。",
        "年级边界和行动条件由当前毕业准备规则确定。",
        "筛选范围×学期", "graduation_readiness", f"{V2_API}#graduation_readiness",
        [_page(CURRICULUM_GRADUATION, "高年级行动KPI", CURRICULUM_VIEW, usage_type="kpi")], unit="人",
    ),
    _metric(
        "TA.CURR.GRADUATION.COMPLETION_RATE", "培养质量分析", "毕业要求完成率",
        "已满足毕业要求项数 / 可评估毕业要求项数 × 100%",
        "展示学生毕业准备要求的完成程度。",
        "仅对有规则且可评估的要求计入分母；不是毕业资格审批结论。",
        "学生×学期", "graduation_readiness", f"{V2_API}#graduation_readiness",
        [_page(CURRICULUM_GRADUATION, "学生毕业完成率", CURRICULUM_VIEW)], unit="%",
    ),
    _metric(
        "TA.CURR.GRADUATION.COURSE_FAILED_STUDENTS", "培养质量分析", "毕业课程未通过学生数",
        "COUNT(DISTINCT student WHERE required graduation course is unmet)",
        "按课程统计尚未满足毕业课程要求的学生数。",
        "考虑当前课程通过与替代关系；按学生去重。",
        "课程×学期", "training_plan_course / fact_grade", f"{V2_API}#graduation_readiness",
        [_page(CURRICULUM_GRADUATION, "课程保障表-未通过学生", CURRICULUM_VIEW)], unit="人",
    ),
    _metric(
        "TA.CURR.GRADUATION.COURSE_AFFECTED_MAJORS", "培养质量分析", "毕业课程影响专业数",
        "COUNT(DISTINCT major_id WHERE course is required and unmet)",
        "按课程统计存在未满足要求学生的专业数量。",
        "仅覆盖当前授权范围内的培养方案与学生。",
        "课程×学期", "training_plan_course / dim_student", f"{V2_API}#graduation_readiness",
        [_page(CURRICULUM_GRADUATION, "课程保障表-影响专业", CURRICULUM_VIEW)], unit="个",
    ),
    _metric(
        "TA.CURR.GRADUATION.HISTORY_LESSON_COUNT", "培养质量分析", "课程历史开课教学班数",
        "COUNT(DISTINCT teaching_lesson.id in lookback semesters)",
        "展示毕业相关课程在历史观察窗内的开课教学班数。",
        "历史观察窗由接口参数确定；不是当前学期教学班数。",
        "课程×历史学期窗", "teaching_lesson", f"{V2_API}#graduation_readiness",
        [_page(CURRICULUM_GRADUATION, "课程保障表-历史教学班", CURRICULUM_VIEW, usage_type="tooltip")], unit="班",
    ),
    _metric(
        "TA.CURR.GRADUATION.HISTORY_TEACHER_COUNT", "培养质量分析", "课程历史授课教师数",
        "COUNT(DISTINCT lesson_teacher.teacher_id in lookback semesters)",
        "展示毕业相关课程在历史观察窗内的授课教师覆盖。",
        "按教师绑定去重；历史窗由接口参数确定。",
        "课程×历史学期窗", "lesson_teacher", f"{V2_API}#graduation_readiness",
        [_page(CURRICULUM_GRADUATION, "课程保障表-历史教师", CURRICULUM_VIEW, usage_type="tooltip")], unit="人",
    ),
    _metric(
        "TA.CURR.GRADUATION.SUBSTITUTION_COUNT", "培养质量分析", "课程替代关系数",
        "COUNT(course_substitution WHERE target course matches)",
        "统计毕业相关课程配置的有效替代课程关系数量。",
        "按替代关系记录计数，不等于已使用替代的学生数。",
        "课程×方案", "course_substitution", f"{V2_API}#graduation_readiness",
        [_page(CURRICULUM_GRADUATION, "课程保障表-替代关系", CURRICULUM_VIEW, usage_type="tooltip")], unit="条",
    ),
    _metric(
        "TA.CURR.GRADUATION.SUBSTITUTION_STUDENTS", "培养质量分析", "替代课程满足学生数",
        "COUNT(DISTINCT student WHERE requirement is met by valid substitute course)",
        "统计通过有效替代课程满足原毕业课程要求的学生数。",
        "按学生去重，须命中当前有效替代关系。",
        "课程×学期", "course_substitution / fact_grade", f"{V2_API}#graduation_readiness",
        [_page(CURRICULUM_GRADUATION, "课程保障表-替代满足学生", CURRICULUM_VIEW, usage_type="tooltip")], unit="人",
    ),
    _metric(
        "TA.CURR.GRADUATION.OFFERING_CAPACITY", "培养质量分析", "课程开课容量",
        "SUM(teaching_lesson.capacity in target semester)",
        "汇总毕业相关课程目标学期的教学班容量。",
        "容量缺失或未开课时不生成可用容量；不等于选课人数。",
        "课程×学期", "teaching_lesson.capacity", f"{V2_API}#graduation_readiness",
        [_page(CURRICULUM_GRADUATION, "课程保障表-开课容量", CURRICULUM_VIEW)], unit="人",
    ),
    _metric(
        "TA.CURR.GRADUATION.OFFERING_ENROLLED", "培养质量分析", "课程已选人次",
        "SUM(teaching_lesson.enrolled in target semester)",
        "汇总毕业相关课程目标学期教学班的已选人次。",
        "按教学班人次汇总，不按学生去重。",
        "课程×学期", "teaching_lesson.enrolled", f"{V2_API}#graduation_readiness",
        [_page(CURRICULUM_GRADUATION, "课程保障表-已选人次", CURRICULUM_VIEW)], unit="人次",
    ),
    _metric(
        "TA.CURR.GRADUATION.NO_OFFERING_STUDENTS", "培养质量分析", "无开课保障学生数",
        "COUNT(DISTINCT unmet student WHERE no target-course offering is available)",
        "统计尚需课程但当前没有对应开课保障的学生。",
        "替代课程是否可用需另按替代关系判断。",
        "课程×学期", "graduation_readiness / teaching_lesson", f"{V2_API}#graduation_readiness",
        [_page(CURRICULUM_GRADUATION, "课程保障表-无开课学生", CURRICULUM_VIEW)], unit="人",
    ),
    _metric(
        "TA.CURR.GRADUATION.NO_OFFERING_WITH_SUBSTITUTION", "培养质量分析", "无开课但有替代路径学生数",
        "COUNT(DISTINCT no-offering student WHERE valid substitute course exists)",
        "统计原课程无开课但存在有效替代课程路径的学生。",
        "仅说明存在替代路径，不保证替代课程当前有容量。",
        "课程×学期", "course_substitution / teaching_lesson", f"{V2_API}#graduation_readiness",
        [_page(CURRICULUM_GRADUATION, "课程保障表-替代路径", CURRICULUM_VIEW, usage_type="tooltip")], unit="人",
    ),
)


_FACULTY_METRICS: tuple[dict, ...] = (
    _metric(
        "TA.FAC.ACTIVE_STAFF_COUNT", "师资保障分析", "有效师资总数",
        "COUNT(DISTINCT active teacher in faculty master scope)",
        "统计师资保障页当前范围内的有效教师总体，作为参与率分母。",
        "来自师资主数据有效范围；不等同于已承担教学任务教师数。",
        "筛选范围×学期", "dim_teacher", f"{FACULTY_API}#faculty_overview",
        [_page(FACULTY, "有效师资总数KPI", FACULTY_VIEW, usage_type="kpi")], unit="人",
    ),
    _metric(
        "TA.FAC.TEACHING_PARTICIPATION_RATE", "师资保障分析", "师资教学参与率",
        "承担教学任务教师数 / 有效师资总数 × 100%",
        "衡量有效师资中实际承担教学任务的比例。",
        "页面分别展示分子与分母；二者来源范围需一致后才能直接相除，当前存在已登记风险。",
        "筛选范围×学期", "dim_teacher / lesson_teacher", f"{FACULTY_API}#faculty_overview",
        [_page(FACULTY, "教学参与率说明", FACULTY_VIEW, usage_type="tooltip")], unit="%",
    ),
    _metric(
        "TA.FAC.TITLE_COVERAGE", "师资保障分析", "职称信息覆盖率",
        "有已知职称授课教师数 / 授课教师数 × 100%",
        "衡量参与教学教师的职称字段完整程度。",
        "分母为当前课程任务中的授课教师，不是全部师资。",
        "筛选范围×学期", "dim_teacher.title / lesson_teacher", f"{FACULTY_API}#faculty_overview",
        [_page(FACULTY, "职称覆盖率KPI", FACULTY_VIEW, usage_type="kpi")], unit="%",
    ),
    _metric(
        "TA.FAC.AGE_COVERAGE", "师资保障分析", "年龄信息覆盖率",
        "有可解析年龄/出生年份授课教师数 / 授课教师数 × 100%",
        "衡量参与教学教师年龄信息的可用程度。",
        "当前后端状态判定与页面证据文案存在冲突，已登记问题。",
        "筛选范围×学期", "dim_teacher.birth_date / lesson_teacher", f"{FACULTY_API}#faculty_overview",
        [_page(FACULTY, "年龄覆盖率KPI", FACULTY_VIEW, usage_type="kpi")], unit="%",
    ),
    _metric(
        "TA.FAC.COURSE_LESSON_COUNT", "师资保障分析", "课程教学班数（师资保障）",
        "COUNT(DISTINCT teaching_lesson.id) GROUP BY course",
        "统计师资结构分析中课程对应的教学班数量。",
        "只覆盖进入师资任务构建的教学班。",
        "课程×学期", "teaching_lesson", f"{FACULTY_API}#faculty_overview",
        [_page(FACULTY, "课程师资表-教学班数", FACULTY_VIEW)], unit="班",
    ),
    _metric(
        "TA.FAC.COURSE_ENROLLED_VISITS", "师资保障分析", "课程修读人次（师资保障）",
        "SUM(teaching_lesson.enrolled) GROUP BY course",
        "汇总师资结构分析课程的教学班修读人次。",
        "同一学生跨教学班或课程可重复计数。",
        "课程×学期", "teaching_lesson.enrolled", f"{FACULTY_API}#faculty_overview",
        [_page(FACULTY, "课程师资表-修读人次", FACULTY_VIEW)], unit="人次",
    ),
    _metric(
        "TA.FAC.COURSE_TEACHER_COUNT", "师资保障分析", "课程授课教师数（师资保障）",
        "COUNT(DISTINCT lesson_teacher.teacher_id) GROUP BY course",
        "统计课程全部教学班绑定的去重授课教师数。",
        "来源为 lesson_teacher；不同于课程供给主讲教师数。",
        "课程×学期", "lesson_teacher", f"{FACULTY_API}#faculty_overview",
        [_page(FACULTY, "课程师资表-教师数", FACULTY_VIEW)], unit="人",
    ),
    _metric(
        "TA.FAC.COURSE_KNOWN_TITLE_TEACHERS", "师资保障分析", "课程已知职称教师数",
        "COUNT(DISTINCT course teacher WHERE normalized title is known)",
        "统计课程授课团队中职称可识别的教师数。",
        "未知或空职称不计入。",
        "课程×学期", "dim_teacher.title / lesson_teacher", f"{FACULTY_API}#faculty_overview",
        [_page(FACULTY, "课程师资表-职称已知数", FACULTY_VIEW, usage_type="tooltip")], unit="人",
    ),
    _metric(
        "TA.FAC.COURSE_TITLE_COMPLETENESS", "师资保障分析", "课程团队职称完整率",
        "课程已知职称教师数 / 课程授课教师数 × 100%",
        "衡量课程授课团队职称信息完整程度。",
        "仅评价数据完整性，不评价职称结构优劣。",
        "课程×学期", "dim_teacher.title / lesson_teacher", f"{FACULTY_API}#faculty_overview",
        [_page(FACULTY, "课程师资表-职称完整率", FACULTY_VIEW)], unit="%",
    ),
    _metric(
        "TA.FAC.COURSE_MAX_LESSON_SHARE", "师资保障分析", "课程单教师最大教学班占比",
        "MAX(teacher lesson_count) / course lesson_count × 100%",
        "衡量课程教学班在单名教师上的最高集中程度。",
        "按教师教学班数计算，不代表工作量学时占比。",
        "课程×学期", "lesson_teacher / teaching_lesson", f"{FACULTY_API}#faculty_overview",
        [_page(FACULTY, "课程师资表-教学班集中度", FACULTY_VIEW)], unit="%",
    ),
    _metric(
        "TA.FAC.COURSE_MAX_ENROLLED_SHARE", "师资保障分析", "课程单教师最大修读人次占比",
        "MAX(teacher enrolled_visits) / course enrolled_visits × 100%",
        "衡量课程修读规模在单名教师上的最高集中程度。",
        "按教师关联教学班修读人次聚合，不按学生去重。",
        "课程×学期", "lesson_teacher / teaching_lesson.enrolled", f"{FACULTY_API}#faculty_overview",
        [_page(FACULTY, "课程师资表-人次集中度", FACULTY_VIEW)], unit="%",
    ),
    _metric(
        "TA.FAC.COURSE_CONTINUITY_OBSERVATIONS", "师资保障分析", "课程师资连续性观测学期数",
        "COUNT(DISTINCT semester in course teaching history)",
        "统计课程师资连续性规则能够观察到的历史学期数量。",
        "受历史数据覆盖范围限制；观测不足不等于师资不连续。",
        "课程×历史学期窗", "lesson_teacher / teaching_lesson", f"{FACULTY_API}#faculty_overview",
        [_page(FACULTY, "课程师资表-连续性证据", FACULTY_VIEW, usage_type="tooltip")], unit="学期",
    ),
    _metric(
        "TA.FAC.IMPORTANT_COURSE_FLAG", "师资保障分析", "重点课程识别",
        "课程必修标志=1，或课程名称、课程性质、课程类别任一字段包含必修、主干、核心、基础、思想、政治、体育、数学、英语等重点关键词时，判定为重点课程",
        "在当前查询条件和授权课程范围内，判断每门课程是否满足师资保障分析的重点课程识别条件。",
        "满足任一条件即命中；关键词匹配属于当前原型规则，正式生产规则及词表仍需学校确认。",
        "课程×学期", "dim_course / teaching_lesson", f"{FACULTY_API}#_is_important_course",
        [_page(
            FACULTY, "课程核查分类-重点课程识别", FACULTY_VIEW,
            usage_type="calculation", occurrence="classification:importantCourse",
            description="作为优先复核课程分类的输入条件，不单独形成教师评价结论。",
        )], unit="是/否",
    ),
    _metric(
        "TA.FAC.PRIORITY_REVIEW_COURSES", "师资保障分析", "优先复核课程数",
        "COUNT(DISTINCT course WHERE faculty classification=priority_review)",
        "统计触发师资结构优先复核分类的课程。",
        "分类由当前结构、集中度、连续性及数据完整性规则按优先级产生。",
        "筛选范围×学期", "faculty course classification", f"{FACULTY_API}#faculty_overview",
        [_page(FACULTY, "优先复核课程KPI", FACULTY_VIEW, usage_type="kpi")], unit="门",
    ),
    _metric(
        "TA.FAC.DATA_CANDIDATE_COURSES", "师资保障分析", "数据候选课程数",
        "COUNT(DISTINCT course WHERE data completeness is insufficient for structure judgement)",
        "统计因教师、职称或年龄等证据不足而进入数据候选分类的课程。",
        "数据不足时不直接作结构异常结论。",
        "筛选范围×学期", "faculty course classification", f"{FACULTY_API}#faculty_overview",
        [_page(FACULTY, "数据候选课程KPI", FACULTY_VIEW, usage_type="kpi")], unit="门",
    ),
    _metric(
        "TA.FAC.EVALUABLE_COURSES", "师资保障分析", "师资结构可评价课程数",
        "COUNT(DISTINCT course WHERE minimum faculty evidence is met)",
        "统计满足当前师资结构评价最低证据要求的课程。",
        "最低证据要求由教师数、职称完整性等规则决定。",
        "筛选范围×学期", "faculty course classification", f"{FACULTY_API}#faculty_overview",
        [_page(FACULTY, "可评价课程KPI", FACULTY_VIEW, usage_type="kpi")], unit="门",
    ),
    _metric(
        "TA.FAC.COLLEGE_REVIEW_RATE", "师资保障分析", "学院优先复核课程占比",
        "学院优先复核课程数 / 学院课程数 × 100%",
        "比较各学院师资结构优先复核课程的构成。",
        "分母为进入师资保障分析的学院课程数。",
        "学院×学期", "faculty course classification", f"{FACULTY_API}#faculty_overview",
        [_page(FACULTY, "学院师资保障表-复核率", FACULTY_VIEW)], unit="%",
    ),
    _metric(
        "TA.FAC.TEAM_MEMBER_LESSONS", "师资保障分析", "团队成员承担教学班数",
        "COUNT(DISTINCT lesson_id) GROUP BY course, teacher",
        "在课程师资团队下钻中展示单名教师承担的教学班数。",
        "按课程内教师绑定去重。",
        "课程×教师×学期", "lesson_teacher", f"{FACULTY_API}#faculty_course_detail",
        [_page(FACULTY, "团队成员明细-教学班", FACULTY_VIEW, usage_type="drilldown")], unit="班",
    ),
    _metric(
        "TA.FAC.TEAM_MEMBER_VISITS", "师资保障分析", "团队成员承担修读人次",
        "SUM(lesson.enrolled for teacher-bound lessons)",
        "在课程师资团队下钻中展示单名教师关联教学班的修读人次。",
        "共同授课时同一教学班人次可被多个教师分别承接，不宜跨教师直接相加解释为课程总人次。",
        "课程×教师×学期", "lesson_teacher / teaching_lesson.enrolled", f"{FACULTY_API}#faculty_course_detail",
        [_page(FACULTY, "团队成员明细-修读人次", FACULTY_VIEW, usage_type="drilldown")], unit="人次",
    ),
    _metric(
        "TA.FAC.TEAM_MEMBER_LESSON_SHARE", "师资保障分析", "团队成员教学班占比",
        "团队成员承担教学班数 / 课程教学班数 × 100%",
        "展示教师在课程教学班分工中的占比。",
        "共同授课绑定可能导致所有成员占比之和超过100%。",
        "课程×教师×学期", "lesson_teacher / teaching_lesson", f"{FACULTY_API}#faculty_course_detail",
        [_page(FACULTY, "团队成员明细-教学班占比", FACULTY_VIEW, usage_type="drilldown")], unit="%",
    ),
    _metric(
        "TA.FAC.TEACHER.CURRENT_COURSES", "师资保障分析", "教师当前承担课程数",
        "COUNT(DISTINCT course_id) GROUP BY teacher",
        "在教师下钻中展示教师当前学期承担的去重课程数。",
        "以 lesson_teacher 绑定为准。",
        "教师×学期", "lesson_teacher", f"{FACULTY_API}#faculty_teacher_detail",
        [_page(FACULTY, "教师明细-课程数", FACULTY_VIEW, usage_type="drilldown")], unit="门",
    ),
    _metric(
        "TA.FAC.TEACHER.CURRENT_LESSONS", "师资保障分析", "教师当前承担教学班数",
        "COUNT(DISTINCT lesson_id) GROUP BY teacher",
        "在教师下钻中展示教师当前学期承担的教学班数。",
        "以 lesson_teacher 绑定为准。",
        "教师×学期", "lesson_teacher", f"{FACULTY_API}#faculty_teacher_detail",
        [_page(FACULTY, "教师明细-教学班数", FACULTY_VIEW, usage_type="drilldown")], unit="班",
    ),
    _metric(
        "TA.FAC.TEACHER.CURRENT_VISITS", "师资保障分析", "教师当前承担修读人次",
        "SUM(bound lesson enrolled) GROUP BY teacher",
        "在教师下钻中展示当前学期关联教学班修读人次。",
        "共同授课场景会在教师之间重复承接课程人次。",
        "教师×学期", "lesson_teacher / teaching_lesson.enrolled", f"{FACULTY_API}#faculty_teacher_detail",
        [_page(FACULTY, "教师明细-修读人次", FACULTY_VIEW, usage_type="drilldown")], unit="人次",
    ),
    _metric(
        "TA.FAC.TEACHER.CURRENT_HOURS", "师资保障分析", "教师当前教学学时",
        "SUM(teaching hours associated with teacher tasks)",
        "在教师下钻中展示当前学期教学任务学时。",
        "按师资保障接口任务口径计算，不与工作量页 agg_teacher_load.total_hours 自动合并。",
        "教师×学期", "teacher teaching task", f"{FACULTY_API}#faculty_teacher_detail",
        [_page(FACULTY, "教师明细-教学学时", FACULTY_VIEW, usage_type="drilldown")], unit="学时",
    ),
)


EXTRA_VERIFIED_METRICS: tuple[dict, ...] = (
    *_OPERATION_METRICS,
    *_CURRICULUM_METRICS,
    *_FACULTY_METRICS,
)


VERIFIED_ALIASES: tuple[dict, ...] = (
    {"metric_id": "T-01", "alias": "已关联课程", "alias_type": "display", "source_ref": f"{OP_VIEW}/Courses.vue"},
    {"metric_id": "TA.OP.SUPPLY.LESSON_COUNT", "alias": "教学班数", "alias_type": "ambiguous_display", "source_ref": f"{OP_VIEW}/Courses.vue"},
    {"metric_id": "TA.OP.SCHEDULE.LESSON_COUNT", "alias": "教学班数", "alias_type": "ambiguous_display", "source_ref": f"{OP_VIEW}/ScheduleAnalysis.vue"},
    {"metric_id": "TA.OP.SUPPLY.AVG_CLASS_SIZE", "alias": "平均班额", "alias_type": "ambiguous_display", "source_ref": f"{OP_VIEW}/Courses.vue"},
    {"metric_id": "TA.OP.SCHEDULE.COURSE_AVG_CLASS_SIZE", "alias": "平均班额", "alias_type": "ambiguous_display", "source_ref": f"{OP_VIEW}/ScheduleAnalysis.vue"},
    {"metric_id": "TA.OP.LOAD.AVG_CLASS_SIZE", "alias": "平均班额", "alias_type": "ambiguous_display", "source_ref": f"{OP_VIEW}/TeacherLoad.vue"},
    {"metric_id": "TA.OP.SUPPLY.COURSE_TEACHER_COUNT", "alias": "开课教师数", "alias_type": "scope_specific", "source_ref": f"{OP_VIEW}/Courses.vue"},
    {"metric_id": "TA.OP.SCHEDULE.COURSE_TEACHER_COUNT", "alias": "授课教师数", "alias_type": "scope_specific", "source_ref": f"{OP_VIEW}/ScheduleAnalysis.vue"},
    {"metric_id": "TA.FAC.COURSE_TEACHER_COUNT", "alias": "授课教师数", "alias_type": "scope_specific", "source_ref": FACULTY_VIEW},
    {"metric_id": "TA.OP.CLASSROOM.PERIOD_OBSERVED_LOAD", "alias": "观测利用率", "alias_type": "legacy_or_inexact", "source_ref": f"{OP_API}#classroom_occupancy"},
    {"metric_id": "TA.OP.CLASSROOM.BUILDING_LOAD", "alias": "楼宇负载", "alias_type": "display", "source_ref": f"{OP_VIEW}/Classroom.vue"},
    {"metric_id": "TA.OP.LOAD.ACTIVE_TEACHERS", "alias": "有效授课教师", "alias_type": "display", "source_ref": f"{OP_VIEW}/TeacherLoad.vue"},
    {"metric_id": "TA.OP.LOAD.P90_HOURS", "alias": "P90学时", "alias_type": "display", "source_ref": f"{OP_VIEW}/TeacherLoad.vue"},
    {"metric_id": "TA.OP.CHANGE.EVENT_COUNT", "alias": "调停课记录", "alias_type": "display", "source_ref": f"{OP_VIEW}/ScheduleChanges.vue"},
    {"metric_id": "TA.OP.RESULT.OVERALL_FAIL_RATE", "alias": "整体未通过率", "alias_type": "display", "source_ref": f"{OP_VIEW}/CourseQuality.vue"},
    {"metric_id": "TA.OP.RESULT.FIRST_FAIL_RATE", "alias": "fail_rate", "alias_type": "technical_deprecated", "source_ref": f"{V2_API}#course_result_quality"},
    {"metric_id": "TA.OP.RESULT.FIRST_FAIL_RATE", "alias": "未通过率", "alias_type": "ambiguous_display", "source_ref": f"{OP_VIEW}/CourseQuality.vue"},
    {"metric_id": "TA.OP.RESULT.PERSISTENT_HIGH_COUNT", "alias": "连续高未通过课程", "alias_type": "display", "source_ref": f"{OP_VIEW}/CourseQuality.vue"},
    {"metric_id": "TA.OP.RESULT.VOLATILE_COUNT", "alias": "学期间变化较大课程", "alias_type": "display", "source_ref": f"{OP_VIEW}/CourseQuality.vue"},
    {"metric_id": "TA.CURR.BINDING.OVERALL_RATE", "alias": "方案绑定率", "alias_type": "ambiguous_display", "source_ref": CURRICULUM_VIEW},
    {"metric_id": "TA.CURR.BINDING.GROUP_RATE", "alias": "方案绑定率", "alias_type": "ambiguous_display", "source_ref": CURRICULUM_VIEW},
    {"metric_id": "TA.CURR.VERIFICATION_STUDENTS", "alias": "需核验学生", "alias_type": "display", "source_ref": CURRICULUM_VIEW},
    {"metric_id": "F-17", "alias": "授课教师总数/教职工总数", "alias_type": "paired_card", "source_ref": FACULTY_VIEW},
    {"metric_id": "F-10", "alias": "教师结构异常课程数", "alias_type": "display", "source_ref": FACULTY_VIEW},
    {"metric_id": "F-10", "alias": "结构核查指标", "alias_type": "business_synonym", "source_ref": FACULTY_VIEW},
    {"metric_id": "F-18", "alias": "连续单点授课教师数", "alias_type": "display", "source_ref": FACULTY_VIEW},
)


def _dependency(source: str, target: str, relation: str, description: str, source_ref: str) -> dict:
    return {
        "source_metric_id": source,
        "target_metric_id": target,
        "relation_type": relation,
        "description": description,
        "source_ref": source_ref,
    }


VERIFIED_DEPENDENCIES: tuple[dict, ...] = (
    _dependency("TA.OP.SUPPLY.AVG_CLASS_SIZE", "TA.OP.SUPPLY.ENROLLED_VISITS", "numerator", "修读人次是课程供给平均班额分子。", f"{OP_API}#courses"),
    _dependency("TA.OP.SUPPLY.AVG_CLASS_SIZE", "TA.OP.SUPPLY.LESSON_COUNT", "denominator", "开课教学班数是课程供给平均班额分母。", f"{OP_API}#courses"),
    _dependency("TA.OP.SUPPLY.ATTENTION_SCORE", "TA.OP.SUPPLY.AVG_CLASS_SIZE", "rule_input", "课程平均班额进入供给关注得分。", f"{OP_API}#_course_offering_rows"),
    _dependency("TA.OP.SUPPLY.ATTENTION_SCORE", "TA.OP.SUPPLY.COURSE_TEACHER_COUNT", "rule_input", "开课教师数进入单教师多班判断。", f"{OP_API}#_course_offering_rows"),
    _dependency("TA.OP.SUPPLY.ATTENTION_SCORE", "TA.OP.SUPPLY.LESSON_COUNT", "rule_input", "教学班数进入多班或单班判断。", f"{OP_API}#_course_offering_rows"),
    _dependency("TA.OP.SUPPLY.ATTENTION_SCORE", "TA.OP.SUPPLY.ENROLLED_VISITS", "rule_input", "修读人次进入单班集中供给判断。", f"{OP_API}#_course_offering_rows"),
    _dependency("TA.OP.SUPPLY.ATTENTION_COURSE_COUNT", "TA.OP.SUPPLY.ATTENTION_SCORE", "filter", "关注课程数统计得分大于0的课程。", f"{OP_API}#courses"),
    _dependency("TA.OP.SUPPLY.COLLEGE_LESSON_SHARE", "TA.OP.SUPPLY.COLLEGE_LESSON_COUNT", "numerator", "学院教学班数是学院占比分子。", f"{OP_API}#courses"),
    _dependency("TA.OP.SUPPLY.COLLEGE_LESSON_SHARE", "TA.OP.SUPPLY.LESSON_COUNT", "denominator", "全部开课教学班数是学院占比分母。", f"{OP_API}#courses"),
    _dependency("TA.OP.SUPPLY.NATURE_COURSE_SHARE", "TA.OP.SUPPLY.NATURE_COURSE_COUNT", "numerator", "课程性质去重课程数是构成比分子。", f"{OP_API}#courses"),
    _dependency("TA.OP.SUPPLY.NATURE_COURSE_SHARE", "T-01", "denominator", "全部去重开课课程数是课程性质构成比分母。", f"{OP_API}#courses"),
    _dependency("TA.OP.SUPPLY.SIZE_LESSON_SHARE", "TA.OP.SUPPLY.SIZE_LESSON_COUNT", "numerator", "班额区间教学班数是区间占比分子。", f"{OP_API}#courses"),
    _dependency("TA.OP.SUPPLY.SIZE_LESSON_SHARE", "TA.OP.SUPPLY.LESSON_COUNT", "denominator", "全部开课教学班数是班额占比分母。", f"{OP_API}#courses"),
    _dependency("TA.OP.SCHEDULE.PEAK_SHARE", "TA.OP.SCHEDULE.PEAK_MEETING_COUNT", "numerator", "高峰周次节次量是高峰占比分子。", f"{OP_API}#schedule_strategy"),
    _dependency("TA.OP.SCHEDULE.PEAK_SHARE", "TA.OP.SCHEDULE.CELL_MEETING_COUNT", "denominator", "全部标准化周次节次量是高峰占比分母。", f"{OP_API}#schedule_strategy"),
    _dependency("TA.OP.SCHEDULE.EVENING_SHARE", "TA.OP.SCHEDULE.EVENING_MEETINGS", "numerator", "晚间meeting数是晚间排课占比分子。", f"{OP_API}#schedule_strategy"),
    _dependency("TA.OP.SCHEDULE.EVENING_SHARE", "TA.OP.SCHEDULE.MEETING_COUNT", "denominator", "全部meeting数是晚间排课占比分母。", f"{OP_API}#schedule_strategy"),
    _dependency("TA.OP.CLASSROOM.PERIOD_OBSERVED_LOAD", "TA.OP.CLASSROOM.OCCUPIED_ROOM_DAYS", "numerator", "星期节次占用教室日是热力图观测负载分子。", f"{OP_API}#classroom_occupancy"),
    _dependency("TA.OP.CLASSROOM.PERIOD_OBSERVED_LOAD", "TA.OP.CLASSROOM.OBSERVED_OPPORTUNITIES", "denominator", "观测教室与对应星期日期构成热力图分母。", f"{OP_API}#classroom_occupancy"),
    _dependency("TA.OP.CLASSROOM.PEAK_LOAD", "TA.OP.CLASSROOM.PERIOD_OBSERVED_LOAD", "maximum", "最高时段负载取全部热力图网格最大值。", f"{OP_VIEW}/Classroom.vue"),
    _dependency("TA.OP.CLASSROOM.BUILDING_LOAD", "TA.OP.CLASSROOM.OCCUPIED_ROOM_SLOTS", "numerator", "楼宇占用教室日节次是楼宇负载分子。", f"{OP_API}#classroom_occupancy"),
    _dependency("TA.OP.LOAD.AVG_HOURS", "TA.OP.LOAD.TOTAL_HOURS", "numerator", "总学时是人均学时分子。", f"{OP_API}#teacher_load"),
    _dependency("TA.OP.LOAD.AVG_HOURS", "TA.OP.LOAD.ACTIVE_TEACHERS", "denominator", "有效授课教师数是人均学时分母。", f"{OP_API}#teacher_load"),
    _dependency("TA.OP.CHANGE.STOP_SHARE", "TA.OP.CHANGE.STOP_COUNT", "numerator", "停课事件数是停课占比分子。", f"{OP_API}#schedule_changes"),
    _dependency("TA.OP.CHANGE.STOP_SHARE", "TA.OP.CHANGE.EVENT_COUNT", "denominator", "全部调停课事件数是停课占比分母。", f"{OP_API}#schedule_changes"),
    _dependency("TA.OP.CHANGE.REASON_COVERAGE", "TA.OP.CHANGE.EVENT_COUNT", "denominator", "全部事件数是原因文本覆盖率分母。", f"{OP_API}#schedule_changes"),
    _dependency("TA.OP.CHANGE.COLLEGE_EVENT_RATE", "TA.OP.CHANGE.COLLEGE_EVENT_COUNT", "numerator", "学院调停课事件数是发生率分子。", f"{OP_API}#schedule_changes"),
    _dependency("TA.OP.CHANGE.COLLEGE_EVENT_RATE", "TA.OP.CHANGE.COLLEGE_VALID_LESSONS", "denominator", "学院有效开课教学班数是发生率分母。", f"{OP_API}#schedule_changes"),
    _dependency("TA.OP.CHANGE.REASON_EVENT_SHARE", "TA.OP.CHANGE.REASON_EVENT_COUNT", "numerator", "原因分类事件数是原因构成比分子。", f"{OP_API}#schedule_changes"),
    _dependency("TA.OP.CHANGE.REASON_EVENT_SHARE", "TA.OP.CHANGE.EVENT_COUNT", "denominator", "全部调停课事件数是原因构成比分母。", f"{OP_API}#schedule_changes"),
    _dependency("TA.OP.RESULT.OVERALL_FAIL_RATE", "TA.OP.RESULT.FAIL_ATTEMPTS", "numerator", "全部未通过尝试数是整体未通过率分子。", f"{V2_API}#course_result_quality"),
    _dependency("TA.OP.RESULT.OVERALL_FAIL_RATE", "TA.OP.RESULT.ALL_ATTEMPTS", "denominator", "全部有效尝试数是整体未通过率分母。", f"{V2_API}#course_result_quality"),
    _dependency("TA.OP.RESULT.FIRST_FAIL_RATE", "TA.OP.RESULT.FIRST_ATTEMPTS", "denominator", "首考有效尝试数是首考未通过率分母。", f"{V2_API}#course_result_quality"),
    _dependency("TA.OP.RESULT.FIRST_FAIL_RATE", "TA.OP.RESULT.FIRST_PASS_ATTEMPTS", "subtrahend", "首考未通过人次由首考尝试数减首考通过人次得到。", f"{V2_API}#course_result_quality"),
    _dependency("C-05", "TA.OP.RESULT.FIRST_PASS_ATTEMPTS", "numerator", "首考通过人次是课程首次通过率分子。", f"{V2_API}#course_result_quality"),
    _dependency("C-05", "TA.OP.RESULT.FIRST_ATTEMPTS", "denominator", "首考有效尝试数是课程首次通过率分母。", f"{V2_API}#course_result_quality"),
    _dependency("C-18", "TA.OP.RESULT.FIRST_PASS_ATTEMPTS", "numerator", "公共必修筛选后的首考通过人次是首次通过率分子。", f"{V2_API}#course_result_quality"),
    _dependency("C-18", "TA.OP.RESULT.FIRST_ATTEMPTS", "denominator", "公共必修筛选后的首考尝试数是首次通过率分母。", f"{V2_API}#course_result_quality"),
    _dependency("G-13", "TA.OP.RESULT.MAKEUP_PASS_ATTEMPTS", "numerator", "补考通过人次是补考通过率分子。", f"{V2_API}#course_result_quality"),
    _dependency("G-13", "TA.OP.RESULT.MAKEUP_ATTEMPTS", "denominator", "补考尝试数是补考通过率分母。", f"{V2_API}#course_result_quality"),
    _dependency("G-16", "TA.OP.RESULT.RETAKE_PASS_ATTEMPTS", "numerator", "重修通过人次是重修通过率分子。", f"{V2_API}#course_result_quality"),
    _dependency("G-16", "TA.OP.RESULT.RETAKE_ATTEMPTS", "denominator", "重修尝试数是重修通过率分母。", f"{V2_API}#course_result_quality"),
    _dependency("TA.OP.RESULT.VOLATILE_COUNT", "TA.OP.RESULT.VOLATILITY", "rule_input", "课程波动幅度进入波动课程计数。", f"{V2_API}#course_result_quality"),
    _dependency("TA.CURR.BINDING.OVERALL_RATE", "TA.CURR.BINDING.MATCHED_STUDENTS", "numerator", "已匹配学生数是总体绑定率分子。", f"{V2_API}#curriculum_quality_overview"),
    _dependency("TA.CURR.BINDING.OVERALL_RATE", "TA.CURR.BINDING.APPLICABLE_STUDENTS", "denominator", "应适用方案学生数是总体绑定率分母。", f"{V2_API}#curriculum_quality_overview"),
    _dependency("TA.CURR.MODULE.RULE_COVERAGE", "TA.CURR.PROGRESS.ASSESSABLE_MODULE_COUNT", "numerator", "可评估模块数是规则覆盖率分子。", f"{V2_API}#curriculum_progress"),
    _dependency("TA.CURR.MODULE.RULE_COVERAGE", "TA.CURR.PROGRESS.MODULE_COUNT", "denominator", "方案模块数是规则覆盖率分母。", f"{V2_API}#curriculum_progress"),
    _dependency("TA.CURR.PROGRESS.ALL_MODULES_MET", "TA.CURR.PROGRESS.COMPLETED_MODULE_COUNT", "rule_input", "完成模块数用于判定全部模块达标。", f"{V2_API}#curriculum_progress"),
    _dependency("TA.CURR.PROGRESS.ALL_MODULES_MET", "TA.CURR.PROGRESS.ASSESSABLE_MODULE_COUNT", "rule_input", "可评估模块数构成全部达标比较基数。", f"{V2_API}#curriculum_progress"),
    _dependency("TA.FAC.PRIORITY_REVIEW_COURSES", "TA.FAC.IMPORTANT_COURSE_FLAG", "rule_input", "重点课程识别结果是优先复核分类的必要输入之一。", f"{FACULTY_API}#_priority_classification"),
    _dependency("TA.FAC.TEACHING_PARTICIPATION_RATE", "F-01", "numerator", "稳定指标F-01授课教师总数是教学参与率分子。", f"{FACULTY_API}#_management_kpis"),
    _dependency("TA.FAC.TEACHING_PARTICIPATION_RATE", "TA.FAC.ACTIVE_STAFF_COUNT", "denominator", "有效师资总数是教学参与率分母。", f"{FACULTY_API}#_management_kpis"),
    _dependency("F-17", "TA.FAC.ACTIVE_STAFF_COUNT", "paired_value", "F-17卡片并列展示授课教师数与同范围有效师资总数。", f"{FACULTY_API}#_management_kpis"),
    _dependency("TA.FAC.COURSE_TITLE_COMPLETENESS", "TA.FAC.COURSE_KNOWN_TITLE_TEACHERS", "numerator", "课程已知职称教师数是完整率分子。", f"{FACULTY_API}#_faculty_analysis"),
    _dependency("TA.FAC.COURSE_TITLE_COMPLETENESS", "TA.FAC.COURSE_TEACHER_COUNT", "denominator", "课程授课教师数是完整率分母。", f"{FACULTY_API}#_faculty_analysis"),
    _dependency("TA.FAC.COLLEGE_REVIEW_RATE", "TA.FAC.PRIORITY_REVIEW_COURSES", "numerator", "学院范围优先复核课程数是复核率分子。", FACULTY_VIEW),
    _dependency("TA.FAC.TEAM_MEMBER_LESSON_SHARE", "TA.FAC.TEAM_MEMBER_LESSONS", "numerator", "团队成员承担教学班数是占比分子。", f"{FACULTY_API}#faculty_course_detail"),
    _dependency("TA.FAC.TEAM_MEMBER_LESSON_SHARE", "TA.FAC.COURSE_LESSON_COUNT", "denominator", "课程教学班数是团队成员占比分母。", f"{FACULTY_API}#faculty_course_detail"),
)


VERIFIED_RULE_BINDINGS: tuple[dict, ...] = (
    _rule("TA.OP.SUPPLY.ATTENTION_SCORE", "attention", "OP-SUPPLY-AVG-120", "input", "平均班额≥120计2分；80≤平均班额<120计1分。", f"{OP_API}#_course_offering_rows"),
    _rule("TA.OP.SUPPLY.ATTENTION_SCORE", "attention", "OP-SUPPLY-SINGLE-TEACHER", "input", "授课教师数=1且教学班数≥3时计2分。", f"{OP_API}#_course_offering_rows"),
    _rule("TA.OP.SUPPLY.ATTENTION_SCORE", "attention", "OP-SUPPLY-SINGLE-LESSON", "input", "教学班数=1且修读人次≥80时计2分。", f"{OP_API}#_course_offering_rows"),
    _rule("TA.OP.SUPPLY.SIZE_LESSON_COUNT", "classification", "OP-SIZE-BANDS", "output", "班额分档为[0,30)、[30,60)、[60,120)、[120,100000)。", f"{OP_API}#_SIZE_RANGE"),
    _rule("TA.OP.SUPPLY.EXCLUDED_TEACHERS", "data_quality", "OP-TEACHER-CLASS-CAP", "output", "单教师单学期教学班数>200判为异常并从正式统计排除。", f"{OP_API}#_TEACHER_CAP"),
    _rule("TA.OP.LOAD.EXCLUDED_TEACHERS", "data_quality", "OP-LOAD-ANOMALY", "output", "教学班数>200、学时>1000或课程数>20任一命中即判异常。", "code/backend/api/util.py#TEACHER_LOAD_ANOMALY_LIMITS"),
    _rule("TA.OP.LOAD.P90_HOURS", "review_queue", "OP-LOAD-P90-QUEUE", "threshold", "总学时不低于当前范围P90的教师进入复核队列，最多返回20人。", f"{OP_API}#teacher_load"),
    _rule("TA.OP.LOAD.COLLEGE_RELATIVE_LEVEL", "display_attention", "OP-LOAD-COLLEGE-ATTENTION", "threshold", "页面按P90排序前3标记优先关注，其余相对负荷>60%标记需关注。", f"{OP_VIEW}/TeacherLoad.vue"),
    _rule("TA.OP.CLASSROOM.BUILDING_LOAD", "display_attention", "OP-ROOM-BUILDING-FOCUS", "threshold", "楼宇观测负荷≥45%且占用记录≥100标记重点关注；负荷≥30%标记需关注。", f"{OP_VIEW}/Classroom.vue"),
    _rule("TA.OP.CLASSROOM.BUILDING_LOAD", "data_quality", "OP-ROOM-PENDING-MAPPING", "output", "楼宇名称为“待映射”时优先标记数据核验。", f"{OP_VIEW}/Classroom.vue"),
    _rule("TA.OP.CHANGE.FREQUENT_TEACHER_EVENTS", "attention", "OP-CHANGE-FREQUENT-TEACHER", "threshold", "教师调停课事件数≥3进入频发教师清单，按次数降序取前10。", f"{OP_API}#schedule_changes"),
    _rule("TA.OP.CHANGE.COLLEGE_EVENT_RATE", "display_attention", "OP-CHANGE-COLLEGE-ATTENTION", "threshold", "页面前3名标记优先关注，其余发生率≥3%标记需关注。", f"{OP_VIEW}/ScheduleChanges.vue"),
    _rule("TA.OP.RESULT.PERSISTENT_HIGH_COUNT", "course_attention", "OP-RESULT-PERSISTENT", "output", "至少2个观测学期且每学期首考未通过率均>15%时标记持续高未通过。", f"{V2_API}#course_result_quality"),
    _rule("TA.OP.RESULT.VOLATILE_COUNT", "course_attention", "OP-RESULT-VOLATILE", "output", "至少2个观测学期且最高与最低首考未通过率差>15个百分点时标记波动。", f"{V2_API}#course_result_quality"),
    _rule("TA.OP.RESULT.WIDE_IMPACT_COUNT", "course_attention", "OP-RESULT-WIDE-IMPACT", "output", "观察期累计未通过成绩尝试数≥50时标记广泛影响。", f"{V2_API}#course_result_quality"),
    _rule("TA.OP.RESULT.RETAKE_ATTEMPTS", "course_attention", "OP-RESULT-RETAKE-PRESSURE", "output", "观察期重修成绩尝试数≥30时标记重修压力。", f"{V2_API}#course_result_quality"),
    _rule("TA.CURR.PROGRESS.CURRENT_TERM", "derivation", "CURR-CURRENT-TERM", "output", "按入学学年差×2加当前学期序号推导，结果最低为1。", f"{GROWTH_ETL}#curriculum_progress"),
    _rule("TA.CURR.PROGRESS.FAILED_REQUIRED_COURSES", "curriculum_status", "CURR-REQUIRED-UNMET", "input", "必修课程无通过结果且未被有效替代课程满足时计为未通过。", f"{V2_API}#curriculum_progress"),
    _rule("TA.CURR.PROGRESS.DUE_CANDIDATE_COURSES", "curriculum_status", "CURR-DUE-COURSE", "input", "建议学期不晚于当前培养学期且要求未满足时计为应修候选。", f"{V2_API}#curriculum_progress"),
    _rule("TA.CURR.GRADUATION.NO_OFFERING_STUDENTS", "graduation_readiness", "CURR-NO-OFFERING", "output", "学生仍需毕业课程且目标学期无对应开课时进入无开课保障清单。", f"{V2_API}#graduation_readiness"),
    _rule("TA.FAC.IMPORTANT_COURSE_FLAG", "faculty_priority", "FAC-IMPORTANT", "output", "必修课或课程名称/性质/类别命中必修、主干、核心、基础、思想、政治、体育、数学、英语等关键词时判为重点保障课程。", f"{FACULTY_API}#_is_important_course"),
    _rule("TA.FAC.PRIORITY_REVIEW_COURSES", "faculty_priority", "FAC-IMPORTANT", "input", "优先复核分类引用重点课程识别结果；重点课程事实本身不会单独触发优先复核。", f"{FACULTY_API}#_priority_classification"),
    _rule("TA.FAC.PRIORITY_REVIEW_COURSES", "faculty_priority", "FAC-SCALE", "input", "教学班数≥4或修读人次≥100时满足规模条件。", f"{FACULTY_API}#_priority_classification"),
    _rule("TA.FAC.PRIORITY_REVIEW_COURSES", "faculty_priority", "FAC-HIGH-IMPACT-SINGLE", "output", "重点保障课程同时满足规模条件且仅1名教师时进入优先核查。", f"{FACULTY_API}#_priority_classification"),
    _rule("F-18", "faculty_continuity", "FAC-CONTINUOUS-SINGLE", "output", "同一教师在课程最近3次实际开课中至少2次作为唯一授课教师，按教师去重。", f"{FACULTY_API}#_continuous_single_teacher_ids"),
    _rule("TA.FAC.PRIORITY_REVIEW_COURSES", "faculty_priority", "FAC-HIGH-CONCENTRATION", "output", "同类同规模样本≥10、教学班数≥4、修读人次≥100，且最大教学班占比和最大人次占比均达到可比组P90时命中高集中。", f"{FACULTY_API}#_faculty_analysis"),
    _rule("F-10", "faculty_structure", "FAC-AGE-SIDE", "output", "年龄证据完整且授课教师全部位于≥55岁一侧或≤55岁一侧时命中年龄结构规则；55岁同时属于两侧。", f"{FACULTY_API}#_age_threshold_sides"),
    _rule("F-10", "faculty_structure", "FAC-JUNIOR-TITLE", "output", "职称证据完整且授课教师职称仅包含助教或讲师时命中职称结构规则。", f"{FACULTY_API}#_matches_structure_review"),
    _rule("TA.FAC.DATA_CANDIDATE_COURSES", "data_quality", "FAC-DATA-CANDIDATE", "output", "责任学院、授课教师、职称或异常任务证据不足时先归数据候选，不形成正式保障判断。", f"{FACULTY_API}#_faculty_analysis"),
    _rule("TA.FAC.PRIORITY_REVIEW_COURSES", "classification", "FAC-REVIEW-PRECEDENCE", "output", "互斥主分类优先级为数据候选、优先核查、结构核查、一般观察。", f"{FACULTY_API}#_priority_classification"),
    _rule("F-09", "evidence_gate", "FAC-TITLE-COVERAGE", "threshold", "职称信息覆盖率达到90%且存在已知职称教师时才输出正式高职称授课占比。", f"{FACULTY_API}#_management_kpis"),
    _rule("F-19", "evidence_gate", "FAC-AGE-COVERAGE", "threshold", "年龄证据不足时不输出正式青年教师授课占比；部分覆盖时状态为partial。", f"{FACULTY_API}#_management_kpis"),
)


VERIFIED_USAGE_POINTS: tuple[dict, ...] = (
    {"metric_id": "T-01", **_page(OP_COURSES, "已关联课程KPI", f"{OP_VIEW}/Courses.vue", usage_type="kpi", occurrence="kpi:linkedCourses")},
    {"metric_id": "T-01", **_page(OP_COURSES, "学院供给表-课程数", f"{OP_VIEW}/Courses.vue", occurrence="table:collegeCourseCount")},
    {"metric_id": "C-05", **_page(OP_RESULTS, "课程首次通过率", f"{OP_VIEW}/CourseQuality.vue", occurrence="table:firstPassRate")},
    {"metric_id": "C-05", **_page(OP_RESULTS, "学期变化-首次通过率", f"{OP_VIEW}/CourseQuality.vue", usage_type="drilldown", occurrence="drilldown:firstPassRate")},
    {"metric_id": "G-13", **_page(OP_RESULTS, "课程补考通过率", f"{OP_VIEW}/CourseQuality.vue", occurrence="table:makeupPassRate")},
    {"metric_id": "G-13", **_page(OP_RESULTS, "学期变化-补考通过率", f"{OP_VIEW}/CourseQuality.vue", usage_type="drilldown", occurrence="drilldown:makeupPassRate")},
    {"metric_id": "G-16", **_page(OP_RESULTS, "课程重修通过率", f"{OP_VIEW}/CourseQuality.vue", occurrence="table:retakePassRate")},
    {"metric_id": "G-16", **_page(OP_RESULTS, "学期变化-重修通过率", f"{OP_VIEW}/CourseQuality.vue", usage_type="drilldown", occurrence="drilldown:retakePassRate")},
    {"metric_id": "C-18", **_page(OP_RESULTS, "公共必修首次通过率", f"{OP_VIEW}/CourseQuality.vue", occurrence="table:publicRequiredFirstPassRate")},
    {"metric_id": "F-01", **_page(FACULTY, "授课教师总数卡片", FACULTY_VIEW, usage_type="kpi", occurrence="kpi:teachingTeacherCount")},
    {"metric_id": "F-01", **_page(FACULTY, "授课教师明细", FACULTY_VIEW, usage_type="drilldown", occurrence="drilldown:teachingTeachers")},
    {"metric_id": "F-09", **_page(FACULTY, "高职称教师授课占比", FACULTY_VIEW, usage_type="kpi", occurrence="kpi:seniorTitleRate")},
    {"metric_id": "F-09", **_page(FACULTY, "高职称教师明细", FACULTY_VIEW, usage_type="drilldown", occurrence="drilldown:seniorTitleTeachers")},
    {"metric_id": "F-10", **_page(FACULTY, "教师结构异常课程数", FACULTY_VIEW, usage_type="kpi", occurrence="kpi:structureException")},
    {"metric_id": "F-10", **_page(FACULTY, "学院结构核查课程", FACULTY_VIEW, occurrence="table:collegeStructureReview")},
    {"metric_id": "F-17", **_page(FACULTY, "授课教师/教职工总数卡片", FACULTY_VIEW, usage_type="kpi", occurrence="kpi:staffCoveragePair")},
    {"metric_id": "F-17", **_page(FACULTY, "授课教师与教职工明细", FACULTY_VIEW, usage_type="drilldown", occurrence="drilldown:staffCoverage")},
    {"metric_id": "F-18", **_page(FACULTY, "连续单点授课教师数", FACULTY_VIEW, usage_type="kpi", occurrence="kpi:continuousSingleTeacher")},
    {"metric_id": "F-18", **_page(FACULTY, "连续单点课程教师证据", FACULTY_VIEW, usage_type="drilldown", occurrence="drilldown:continuousSingleTeacher")},
    {"metric_id": "F-19", **_page(FACULTY, "青年教师授课占比", FACULTY_VIEW, usage_type="kpi", occurrence="kpi:youngTeacherRate")},
    {"metric_id": "F-19", **_page(FACULTY, "青年教师授课明细", FACULTY_VIEW, usage_type="drilldown", occurrence="drilldown:youngTeacher")},
)


VERIFIED_ISSUES: tuple[dict, ...] = (
    {"metric_id": "TA.OP.SUPPLY.SIZE_LESSON_COUNT", "issue_type": "display_boundary_mismatch", "severity": "error", "status": "open", "description": "页面与接口标签写“超大班>120”，实际SQL区间为 enrolled>=120；恰好120人的教学班会进入超大班。", "source_ref": f"{OP_API}#_SIZE_RANGE"},
    {"metric_id": "TA.OP.CLASSROOM.PERIOD_OBSERVED_LOAD", "issue_type": "denominator_boundary", "severity": "warning", "status": "open", "description": "当前分母只包含数据中出现过的教室和日期，缺少正式可用教室、开放日与容量全集；观测负载不能解释为正式教室利用率。", "source_ref": f"{OP_API}#classroom_occupancy"},
    {"metric_id": "TA.OP.LOAD.COLLEGE_RELATIVE_LEVEL", "issue_type": "missing_formal_policy", "severity": "warning", "status": "open", "description": "系统尚未配置学校正式工作量办法；P90、前3名和相对负荷仅用于安排核查顺序，不能认定达标、未达标或超负荷。", "source_ref": f"{OP_API}#teacher_load"},
    {"metric_id": "TA.OP.CHANGE.FREQUENT_TEACHER_EVENTS", "issue_type": "drilldown_scope_mismatch", "severity": "error", "status": "open", "description": "教师原因抽屉查询只按教师和单一学期取数，未完整复用页面学院、事件类型等筛选范围，可能展示超出当前结果集的原因记录。", "source_ref": f"{OP_API}#schedule_changes"},
    {"metric_id": "TA.OP.RESULT.FIRST_FAIL_RATE", "issue_type": "same_field_different_semantics", "severity": "error", "status": "open", "description": "course_result_quality课程行的 fail_rate 是首考未通过率，而趋势SQL同名 fail_rate 是该学期全部尝试未通过率；同字段名承载不同口径，必须拆分。", "source_ref": f"{V2_API}#course_result_quality"},
    {"metric_id": "TA.OP.RESULT.RETAKE_ATTEMPTS", "issue_type": "sample_scope_mismatch", "severity": "warning", "status": "open", "description": "页面累计重修记录汇总覆盖筛选范围全部课程，而关注课程表先应用最小成绩样本门槛；卡片与列表不是同一课程样本范围。", "source_ref": f"{V2_API}#course_result_quality"},
    {"metric_id": "TA.CURR.BINDING.OVERALL_RATE", "issue_type": "same_name_different_denominator", "severity": "error", "status": "open", "description": "总体方案绑定率以推导的适用学生为分母，分组表绑定率以已有plan_student_mapping记录为分母；两者名称接近但不可直接汇总或互换。", "source_ref": f"{V2_API}#curriculum_quality_overview"},
    {"metric_id": "TA.CURR.VERIFICATION_STUDENTS", "issue_type": "constant_zero_output", "severity": "error", "status": "open", "description": "毕业课程核查汇总中的 verification_students 当前构造路径固定返回0，不能据此认为没有需核验学生。", "source_ref": f"{V2_API}#graduation_readiness"},
    {"metric_id": "TA.FAC.TEACHING_PARTICIPATION_RATE", "issue_type": "non_divisible_display_pair", "severity": "error", "status": "open", "description": "“授课教师总数/教职工总数”卡片并列展示的分子与分母可能来自不同回退范围；当人员快照缺失时接口明确不计算参与率，不能由页面显示值直接相除。", "source_ref": f"{FACULTY_API}#_management_kpis"},
    {"metric_id": "TA.FAC.AGE_COVERAGE", "issue_type": "evidence_status_conflict", "severity": "warning", "status": "open", "description": "年龄证据的KPI状态、coverage值与页面证据就绪状态存在不一致路径；部分覆盖或回退来源下可能同时出现可用值与证据不足提示。", "source_ref": f"{FACULTY_API}#_management_kpis"},
    {"metric_id": "TA.FAC.IMPORTANT_COURSE_FLAG", "issue_type": "missing_formal_policy", "severity": "warning", "status": "open", "description": "重点课程当前按必修标志和内置关键词识别，正式课程范围及关键词词表尚需学校确认，不能把原型词表解释为正式制度。", "source_ref": f"{FACULTY_API}#_is_important_course"},
    {"metric_id": "F-10", "issue_type": "threshold_needs_confirmation", "severity": "warning", "status": "open", "description": "年龄结构规则把授课教师全部小于等于55岁的课程也列入结构核查，覆盖面可能过宽；55岁双侧边界来自当前实现，需学校确认后才能作为正式政策阈值。", "source_ref": f"{FACULTY_API}#_age_threshold_sides"},
    {"metric_id": "F-10", "issue_type": "evidence_source_mismatch", "severity": "error", "status": "open", "description": "结构职称规则当前直接使用教师维表职称，而高职称授课占比使用真实人员快照、正式人员主数据、真实教师维表的证据优先级；两项职称指标尚未完全同源。", "source_ref": f"{FACULTY_API}#_faculty_analysis"},
    {"metric_id": "F-19", "issue_type": "evidence_gate_mismatch", "severity": "error", "status": "open", "description": "文档边界要求年龄覆盖率低于90%不输出正式比例；当前代码只要存在至少1条年龄证据就计算比例并标记partial，正式比例与参考比例尚未严格区分。", "source_ref": f"{FACULTY_API}#_management_kpis"},
)
