"""Code-verified metric seeds for dashboard, alert and student-growth areas.

Only metrics and usages that are reachable in the current application are
registered here.  Thresholds and ranking weights are represented as rule
bindings rather than being embedded in metric formula text.
"""
from __future__ import annotations


def _page(
    module_path: str,
    feature_name: str,
    feature_description: str,
    usage_type: str,
    occurrence_key: str,
    source_ref: str,
) -> dict:
    return {
        "module_path": module_path,
        "feature_name": feature_name,
        "feature_description": feature_description,
        "usage_type": usage_type,
        "occurrence_key": occurrence_key,
        "source_ref": source_ref,
    }


def _metric(
    metric_id: str,
    technical_kpi_id: str,
    domain: str,
    name: str,
    description: str,
    formula: str,
    boundary: str,
    management_value: str,
    data_source: str,
    grain: str,
    update_cycle: str,
    version: str,
    source_ref: str,
    pages: tuple[dict, ...],
) -> dict:
    return {
        "metric_id": metric_id,
        "metric_code": metric_id,
        "technical_kpi_id": technical_kpi_id,
        "domain": domain,
        "name": name,
        "description": description,
        "formula": formula,
        "boundary": boundary,
        "management_value": management_value,
        "definition_status": "published",
        "implementation_status": "verified",
        "data_source": data_source,
        "grain": grain,
        "update_cycle": update_cycle,
        "version": version,
        "source_kind": "formal",
        "source_ref": source_ref,
        "pages": pages,
    }


DASHBOARD = "/admin/dashboard"
ALERT = "/admin/alert"
STUDENT = "/admin/students/analysis"


EXTRA_VERIFIED_METRICS: tuple[dict, ...] = (
    _metric(
        "O-02", "valid_result_student_count", "教学数据总览",
        "有效成绩学生数", "所选学期至少存在一条真实且结果明确成绩的去重学生数。",
        "COUNT(DISTINCT student_id)，其中成绩来源为真实数据且通过状态明确",
        "仅说明成绩类结论实际覆盖的人群；无成绩学生不进入成绩率分母。",
        "核查成绩数据覆盖规模，并作为当前挂科学生率等指标的分母。",
        "fact_grade / dim_student", "学生×学期×授权范围", "成绩发布后", "3.0",
        "code/backend/api/routers/dashboard.py#dashboard",
        (
            _page(DASHBOARD, "总览首页·成绩覆盖分子", "有效成绩覆盖率的分子与样本说明。", "supporting_value", "dashboard:coverage:valid-students", "code/backend/api/routers/dashboard.py#dashboard"),
            _page(DASHBOARD, "学院比较·有效成绩学生数", "学院有效成绩覆盖和挂科学生率的共同样本数。", "table_column", "dashboard:college:result-students", "code/backend/api/routers/dashboard.py#dashboard"),
        ),
    ),
    _metric(
        "O-03", "credit_weighted_average_score", "教学数据总览",
        "学分加权平均分", "在当前学期和授权范围内按课程学分加权的成绩平均值。",
        "Σ（有效百分制成绩×课程学分）÷Σ有效课程学分",
        "仅纳入真实、结果明确、成绩可数值化且学分大于0的记录。",
        "比较学院总体成绩水平，并与学生平均GPA交叉核查。",
        "fact_grade", "授权范围×学期", "成绩发布后", "3.0",
        "code/backend/api/routers/dashboard.py#dashboard",
        (_page(DASHBOARD, "总览首页·学院比较·学分加权平均分", "学院横向比较表中的平均分。", "table_column", "dashboard:college:avg-score", "code/backend/api/routers/dashboard.py#dashboard"),),
    ),
    _metric(
        "O-05", "average_student_gpa", "教学数据总览",
        "学生平均GPA", "先计算每名学生的学期学分加权GPA，再对有GPA学生求平均。",
        "AVG（每名学生Σ课程绩点×学分÷Σ计入GPA学分）",
        "每名学生在组织平均中只贡献一次；无有效GPA的学生不进入平均值。",
        "观察总体学业水平并支持学校、学院、专业和班级同口径比较。",
        "fact_grade / agg_student_term_growth", "授权范围×学期", "成绩发布后", "3.0",
        "code/backend/api/routers/dashboard.py#dashboard",
        (
            _page(DASHBOARD, "总览首页·管理摘要·学生平均GPA", "首屏管理摘要卡。", "kpi_card", "dashboard:summary:average-gpa", "code/frontend/src/views/teaching-analysis/dashboard/index.vue#managementSummary"),
            _page(DASHBOARD, "总览首页·学院比较·学生平均GPA", "学院比较、排名和偏离展示。", "table_column", "dashboard:college:average-gpa", "code/backend/api/routers/dashboard.py#dashboard"),
            _page(DASHBOARD, "总览下钻·GPA历史弹窗", "学校、学院和专业维度的逐学期变化。", "history_dialog", "dashboard:history:average-gpa", "code/backend/api/routers/dashboard.py#metric_history"),
            _page(STUDENT, "我的范围·本学期平均GPA", "辅导员、班主任和导师范围的学生GPA平均。", "kpi_card", "students:my-scope:average-gpa", "code/backend/api/routers/students.py#_scope_metrics"),
        ),
    ),
    _metric(
        "O-11", "course_attempt_fail_rate", "教学数据总览",
        "课程人次未通过率", "所选课程或范围内有效成绩记录中未通过记录所占比例。",
        "未通过有效成绩记录数÷全部有效成绩记录数×100%",
        "按记录人次统计，不等于未通过学生率或课程最终有效未通过率。",
        "识别未通过结果集中的课程并辅助确定核查顺序。",
        "fact_grade", "课程×学期×授权范围", "成绩发布后", "3.0",
        "code/backend/api/routers/dashboard.py#dashboard",
        (_page(DASHBOARD, "总览首页·重点课程·当前未通过率", "重点课程TOP10的未通过人次率。", "table_column", "dashboard:focus-course:attempt-fail-rate", "code/frontend/src/views/teaching-analysis/dashboard/index.vue#focusCourseCols"),),
    ),
    _metric(
        "O-14", "active_alert_student_rate", "教学数据总览",
        "当前有效预警学生率", "当前有效预警去重学生占同一授权范围有效在籍学生的比例。",
        "当前有效预警去重学生数÷当前权限范围内有效在籍学生数×100%",
        "规则版本、权限范围和查询条件必须一致；不等于待核查率。",
        "比较不同规模组织的当前预警覆盖。",
        "fact_alert / dim_student", "授权范围×统计时点", "预警重算后", "3.0",
        "code/backend/api/routers/dashboard.py#dashboard",
        (
            _page(DASHBOARD, "总览首页·管理摘要·当前有效预警学生率", "首屏管理摘要卡。", "kpi_card", "dashboard:summary:active-alert-rate", "code/frontend/src/views/teaching-analysis/dashboard/index.vue#managementSummary"),
            _page(DASHBOARD, "总览首页·学院比较·当前有效预警学生率", "学院比较和偏离展示。", "table_column", "dashboard:college:active-alert-rate", "code/backend/api/routers/dashboard.py#dashboard"),
            _page(DASHBOARD, "总览下钻·预警率历史弹窗", "可靠快照学期的有效预警学生率。", "history_dialog", "dashboard:history:active-alert-rate", "code/backend/api/routers/dashboard.py#metric_history"),
            _page(ALERT, "预警监控·当前预警学生率", "非班级关系身份的摘要卡。", "kpi_card", "alert:summary:student-rate", "code/backend/api/routers/alert_monitor.py#alert_summary"),
        ),
    ),
    _metric(
        "O-17", "college_metric_deviation", "教学数据总览",
        "学院横向偏离", "学院指标值相对同口径授权范围值的差异。",
        "学院同口径指标值－授权范围同口径指标值",
        "比率使用百分点，平均分和GPA使用原单位；仅用于确定核查优先级。",
        "识别偏离范围均值的学院及偏离方向。",
        "fact_grade / fact_alert / dim_student", "学院×指标×学期", "基础指标更新后", "3.0",
        "code/backend/api/routers/dashboard.py#dashboard",
        (_page(DASHBOARD, "总览首页·学院偏离与变化", "学院比较表的较范围均值列与排序。", "table_column", "dashboard:college:deviation", "code/frontend/src/views/teaching-analysis/dashboard/index.vue#collegeCols"),),
    ),
    _metric(
        "O-18", "comparable_term_change", "教学数据总览",
        "可比学期变化", "当前学期指标与上一可比学期同口径指标的差值。",
        "本期同口径指标值－上一可比学期同口径指标值",
        "无可靠相邻学期、范围或数据覆盖不可比时不计算。",
        "判断指标改善、恶化或结构变化。",
        "各指标事实表 / 历史学期在籍名单", "范围×指标×相邻学期", "基础指标更新后", "3.0",
        "code/backend/api/routers/dashboard.py#metric_history",
        (
            _page(DASHBOARD, "总览首页·管理摘要·较上学期", "管理摘要卡中的变化值。", "comparison", "dashboard:summary:term-change", "code/backend/api/routers/dashboard.py#dashboard"),
            _page(DASHBOARD, "总览下钻·历年学期变化", "历史弹窗明细与趋势变化。", "history_dialog", "dashboard:history:term-change", "code/backend/api/routers/dashboard.py#metric_history"),
        ),
    ),
    _metric(
        "O-19", "valid_result_coverage_rate", "教学数据总览",
        "有效成绩覆盖率", "所选学期有真实有效成绩的去重学生占同学期在籍范围的比例。",
        "有效成绩去重学生数÷同学期授权范围在籍学生数×100%",
        "每个学期使用本学期自己的在籍分母；覆盖不足时不能外推全部学生。",
        "先判断成绩类结论是否具有代表性。",
        "fact_grade / dim_student / 历史学期students", "授权范围×学期", "成绩和学籍同步后", "3.0",
        "code/backend/api/routers/dashboard.py#dashboard",
        (
            _page(DASHBOARD, "总览首页·管理摘要·有效成绩覆盖率", "首屏第一管理摘要卡。", "kpi_card", "dashboard:summary:coverage", "code/frontend/src/views/teaching-analysis/dashboard/index.vue#managementSummary"),
            _page(DASHBOARD, "总览首页·学院比较·有效成绩覆盖率", "学院比较表及覆盖率排序。", "table_column", "dashboard:college:coverage", "code/backend/api/routers/dashboard.py#dashboard"),
            _page(DASHBOARD, "总览下钻·覆盖率历史弹窗", "学校、学院和专业逐学期覆盖。", "history_dialog", "dashboard:history:coverage", "code/backend/api/routers/dashboard.py#metric_history"),
            _page(DASHBOARD, "专业详情·年级风险核查·有效成绩覆盖率", "年级折叠面板中的覆盖证据。", "detail_value", "dashboard:major:grade-coverage", "code/frontend/src/views/teaching-analysis/dashboard/MajorDetail.vue#grade-evidence"),
        ),
    ),
    _metric(
        "O-20", "focus_course_affected_student_count", "教学数据总览",
        "重点课程受影响学生数", "当前学期某课程至少存在一条明确未通过结果的去重学生数。",
        "COUNT(DISTINCT student_id WHERE course结果明确未通过)",
        "与未通过记录条数分开；同一学生在同一课程重复记录只计一人。",
        "按实际影响学生规模安排课程核查优先级。",
        "fact_grade", "课程×学期×授权范围", "成绩发布后", "3.0",
        "code/backend/api/routers/dashboard.py#dashboard",
        (_page(DASHBOARD, "总览首页·重点核查课程·影响学生", "重点课程TOP10核心排序字段。", "table_column", "dashboard:focus-course:affected-students", "code/frontend/src/views/teaching-analysis/dashboard/index.vue#focusCourseCols"),),
    ),
    _metric(
        "O-21", "focus_course_selection_reason", "教学数据总览",
        "重点课程入选依据", "综合影响学生规模、未通过率、学期变化和课程属性形成可读原因。",
        "先限定当前学期有效成绩样本数≥30且未通过人次>0的课程，再依次按受影响去重学生数降序、公共必修优先、较上期未通过率增幅降序、当前未通过率降序、课程名称升序排序，取前10门；入选原因披露影响人数、公共必修属性及未通过率变化",
        "仅用于核查优先级，不形成课程或教师质量评价。",
        "解释课程进入重点核查清单的原因。",
        "fact_grade / grade_attempt / dim_course", "课程×学期×授权范围", "成绩发布后", "3.0",
        "code/backend/api/routers/dashboard.py#dashboard",
        (
            _page(DASHBOARD, "总览首页·重点核查课程TOP10", "课程排序、入选原因和详情下钻。", "ranking", "dashboard:focus-course:ranking", "code/backend/api/routers/dashboard.py#dashboard"),
            _page(DASHBOARD, "总览首页·优先核查课程TOP1", "优先核查事项中的课程候选。", "priority_card", "dashboard:management-focus:course", "code/backend/api/routers/dashboard.py#_select_management_focus"),
        ),
    ),
    _metric(
        "O-22", "course_final_effective_fail_rate", "教学数据总览",
        "课程最终有效未通过率", "按学生取指定课程最后一条真实有效结果后计算仍未通过比例。",
        "最终有效结果未通过学生数÷有最终有效结果学生数×100%",
        "不同于成绩记录人次未通过率；分母为0时不输出0%。",
        "在课程详情确认当前仍受影响的学生比例。",
        "fact_grade", "课程×学期×授权范围", "成绩发布后", "3.0",
        "code/backend/api/routers/dashboard.py#course_detail",
        (_page(DASHBOARD, "课程详情·最终有效未通过率", "课程详情KPI卡。", "kpi_card", "dashboard:course:final-fail-rate", "code/frontend/src/views/teaching-analysis/dashboard/CourseDetail.vue#kpi"),),
    ),
    _metric(
        "O-23", "course_average_gpa", "教学数据总览",
        "课程平均GPA", "按学生取指定课程最后一条真实有效且有绩点的结果后求算术平均。",
        "AVG（每名学生该课程最后有效课程绩点）",
        "不按课程学分二次加权；缺少绩点的结果不纳入。",
        "与课程平均分配套观察课程结果水平。",
        "fact_grade", "课程×学期×授权范围", "成绩发布后", "3.0",
        "code/backend/api/routers/dashboard.py#course_detail",
        (_page(DASHBOARD, "课程详情·课程平均GPA", "课程详情KPI卡。", "kpi_card", "dashboard:course:average-gpa", "code/frontend/src/views/teaching-analysis/dashboard/CourseDetail.vue#kpi"),),
    ),
    _metric(
        "TECH-SCOPE-FIRST-ATTEMPT-PASS-RATE", "scope_first_attempt_pass_rate", "教学数据总览",
        "授权范围首次修读人次通过率", "当前授权范围内首次修读有效人次的通过比例。",
        "首次修读通过人次÷首次修读有效人次×100%",
        "按人次聚合；不与按去重学生表述的同名候选指标强行合并。",
        "观察授权范围的首次修读结果，并支持历史变化核查。",
        "grade_attempt / agg_course_pass_stat", "授权范围×学期", "成绩发布后", "1.0",
        "code/backend/api/routers/dashboard.py#_v2_pass_stats",
        (
            _page(DASHBOARD, "总览首页·课程通过率结构·首次通过率", "首次/补考/重修通过率结构。", "kpi_card", "dashboard:pass-rate:first", "code/frontend/src/views/teaching-analysis/dashboard/index.vue#coursePassRates"),
            _page(DASHBOARD, "总览下钻·首次通过率历史弹窗", "授权范围逐学期首次修读人次通过率。", "history_dialog", "dashboard:history:first-pass", "code/backend/api/routers/dashboard.py#metric_history"),
        ),
    ),
    _metric(
        "A-02", "current_alert_record_count", "学业预警监控",
        "当前规则触发次数", "当前仍有效的预警规则记录条数。",
        "COUNT（当前有效fact_alert记录）",
        "同一学生可命中多条规则；触发次数不等于预警学生人数。",
        "衡量当前规则事实和核查证据规模。",
        "fact_alert", "规则触发记录×当前快照", "预警重算后", "2.0",
        "code/backend/api/routers/alert_monitor.py#alert_summary",
        (_page(ALERT, "预警监控·当前预警学生卡·规则触发次数", "当前预警学生卡片副说明。", "supporting_value", "alert:summary:record-count", "code/frontend/src/views/teaching-analysis/alert/index.vue#kpiCards"),),
    ),
    _metric(
        "A-03", "highest_risk_level_student_count", "学业预警监控",
        "最高风险等级人数", "每名当前预警学生只按所命中规则中的最高等级归组。",
        "按学生取当前有效预警最高等级后去重计数",
        "严重、警告和提醒互斥计数；明细仍保留全部规则。",
        "按最高风险等级安排核查优先级。",
        "fact_alert", "学生×当前快照×最高等级", "预警重算后", "2.0",
        "code/backend/api/routers/alert_monitor.py#alert_summary",
        (
            _page(ALERT, "预警监控·当前严重学生", "最高等级为严重的学生卡片及名单下钻。", "kpi_card", "alert:summary:critical", "code/frontend/src/views/teaching-analysis/alert/index.vue#kpiCards"),
            _page(ALERT, "预警监控·学生名单·最高风险", "名单的互斥最高风险列。", "table_column", "alert:list:highest-level", "code/frontend/src/views/teaching-analysis/alert/index.vue#studentColumns"),
        ),
    ),
    _metric(
        "A-09", "gpa_continuous_decline_signal", "学业预警监控",
        "GPA持续下降", "连续有效学期学分加权GPA逐期下降并满足已发布规则的学生信号。",
        "最近2至3个有有效GPA的学期中，学生学期学分加权GPA逐期下降且首末学期累计降幅>0.3时命中R1严重规则",
        "具体观察窗和下降幅度属于规则版本，不写入指标公式。",
        "发现持续下滑并进入人工核查。",
        "agg_student_term_growth / fact_alert / sys_alert_rule", "学生×规则计算批次", "预警重算后", "2.0",
        "code/backend/etl/seed.py#ALERT_RULES",
        (_page(ALERT, "预警监控·GPA持续下降规则信号", "规则筛选、主要触发证据和学生信号清单。", "rule_signal", "alert:rule:R1", "code/backend/etl/seed.py#ALERT_RULES"),),
    ),
    _metric(
        "A-10", "unresolved_course_accumulation_signal", "学业预警监控",
        "近期未解决课程累计", "当前未解决的不同课程数满足已发布规则的学生信号。",
        "按课程ID去重统计学生最近2个有效学期曾未通过且截至统计时点仍无通过结果的课程数；=2门命中R2W警告规则，≥3门命中R2严重规则",
        "同一课程多次未通过只算一门；观察窗和门数属于规则版本。",
        "识别课程欠账累积。",
        "agg_student_course_outcome / fact_alert / sys_alert_rule", "学生×规则计算批次", "预警重算后", "2.0",
        "code/backend/etl/seed.py#ALERT_RULES",
        (_page(ALERT, "预警监控·未解决课程累计规则信号", "严重和警告两档规则的触发证据。", "rule_signal", "alert:rule:R2-R2W", "code/backend/etl/seed.py#ALERT_RULES"),),
    ),
    _metric(
        "A-11", "credit_gap_alert_signal", "学业预警监控",
        "学分缺口预警", "计划应完成学分与已认可学分的差值满足已发布规则的学生信号。",
        "期望进度应完成学分－学生已修有效学分>10学分时命中R3警告规则",
        "仅对培养方案与进度要求可用的学生计算；阈值属于规则版本。",
        "识别培养进度滞后。",
        "student_plan_progress_summary / fact_alert / sys_alert_rule", "学生×规则计算批次", "预警重算后", "2.0",
        "code/backend/etl/seed.py#ALERT_RULES",
        (_page(ALERT, "预警监控·学分缺口规则信号", "规则筛选和学生主要触发证据。", "rule_signal", "alert:rule:R3", "code/backend/etl/seed.py#ALERT_RULES"),),
    ),
    _metric(
        "A-12", "required_course_failure_signal", "学业预警监控",
        "必修课程未通过预警", "培养方案核心课或无方案时必修课的未解决结果满足已发布规则的学生信号。",
        "最近2个有效学期内，有培养方案时按方案核心课程、无方案时按课程必修标志统计当前未解决课程；按课程ID去重后≥2门时命中R4提醒规则",
        "有培养方案时按方案核心课；无方案时仅能按必修标记，阈值属于规则版本。",
        "识别毕业关键课程风险。",
        "grade_attempt / curriculum plan / fact_alert / sys_alert_rule", "学生×规则计算批次", "预警重算后", "2.0",
        "code/backend/etl/seed.py#ALERT_RULES",
        (_page(ALERT, "预警监控·核心/必修课程规则信号", "规则筛选和学生主要触发证据。", "rule_signal", "alert:rule:R4", "code/backend/etl/seed.py#ALERT_RULES"),),
    ),
    _metric(
        "A-13", "academic_status_combination_signal", "学业预警监控",
        "学籍风险组合", "GPA和未解决课程同时满足已发布组合规则的学生信号。",
        "学生本学期GPA<1.8，且最近2个有效学期当前未解决课程按课程ID去重后≥2门时命中R6严重规则；两个条件必须同时满足",
        "具体GPA和课程门数阈值属于规则版本；信号不代替学籍处分结论。",
        "形成高优先级核查线索。",
        "agg_student_term_growth / agg_student_course_outcome / fact_alert", "学生×规则计算批次", "预警重算后", "2.0",
        "code/backend/etl/seed.py#ALERT_RULES",
        (_page(ALERT, "预警监控·学籍风险组合规则信号", "规则筛选和学生主要触发证据。", "rule_signal", "alert:rule:R6", "code/backend/etl/seed.py#ALERT_RULES"),),
    ),
    _metric(
        "A-14", "first_year_setback_student_count", "学业预警监控",
        "大一有未通过学生数", "大一第一或第二常规学期出现明确未通过成绩的去重学生数。",
        "COUNT(DISTINCT student_id WHERE 大一常规学期有效未通过记录数>0)",
        "仅纳入有有效入学年且大一常规学期存在有效成绩的学生。",
        "识别早期课程受挫规模。",
        "grade_attempt / dim_student", "学生×大一观察期", "成绩发布后", "2.0",
        "code/backend/api/routers/v2.py#early_setback_topic",
        (
            _page(ALERT, "低年级风险观察·大一有未通过学生", "摘要卡与学生名单预设。", "kpi_card", "alert:early-setback:setback", "code/frontend/src/views/teaching-analysis/alert/EarlySetback.vue#kpis"),
            _page(ALERT, "低年级风险观察·组织未通过学生数", "年级和组织关注优先级表。", "table_column", "alert:early-setback:organization-setback", "code/frontend/src/views/teaching-analysis/alert/EarlySetback.vue#focusColumns"),
        ),
    ),
    _metric(
        "A-15", "first_year_setback_student_rate", "学业预警监控",
        "大一有未通过学生比例", "大一有未通过学生占纳入低年级观察学生的比例。",
        "大一有未通过学生数÷纳入低年级观察学生数×100%",
        "分母排除无有效入学年或大一常规学期无有效成绩的学生。",
        "比较组织和年级的早期受挫集中度。",
        "grade_attempt / dim_student", "组织或年级×大一观察期", "成绩发布后", "2.0",
        "code/backend/api/routers/v2.py#early_setback_topic",
        (_page(ALERT, "低年级风险观察·未通过学生比例", "摘要卡副说明、年级表和组织排序。", "table_column", "alert:early-setback:setback-rate", "code/frontend/src/views/teaching-analysis/alert/EarlySetback.vue#focusColumns"),),
    ),
    _metric(
        "A-19", "similar_alert_trajectory_distribution", "学业预警监控",
        "同类轨迹分布", "按预警规则和等级分桶，汇总后续解除、GPA变化、新增未通过、风险升级和毕业结果。",
        "按预警规则ID×风险等级分桶，对具备后续观察期的预警记录分别统计解除状态、GPA变化方向、新增未通过课程档位、同级或更高风险升级和毕业结果分布；GPA变化以±0.05为稳定带，样本数<10标记低置信",
        "历史统计分布不构成个体预测；低样本标记低置信，毕业结果可能含合成兜底。",
        "帮助判断某类预警的常见后续走向。",
        "fact_alert / alert_event / fact_grade / graduation_outcome / fact_graduation", "规则×等级×历史预警记录", "成绩、预警或毕业结果更新后", "1.0",
        "code/backend/api/routers/alert_trajectory.py#compute_trajectory",
        (
            _page(ALERT, "学生预警核查·同类轨迹·解除占比", "同类历史预警的解除分布。", "chart_series", "alert:trajectory:resolved", "code/backend/api/routers/alert_trajectory.py#_bucket_stats"),
            _page(ALERT, "学生预警核查·同类轨迹·GPA变化", "后续可观察学期GPA方向分布。", "chart_series", "alert:trajectory:gpa", "code/backend/api/routers/alert_trajectory.py#_bucket_stats"),
            _page(ALERT, "学生预警核查·同类轨迹·新增未通过", "后续学期新增未通过课程分布。", "chart_series", "alert:trajectory:new-fail", "code/backend/api/routers/alert_trajectory.py#_bucket_stats"),
            _page(ALERT, "学生预警核查·同类轨迹·风险升级", "后续同级或更高等级预警比例。", "chart_series", "alert:trajectory:escalate", "code/backend/api/routers/alert_trajectory.py#_bucket_stats"),
            _page(ALERT, "学生预警核查·同类轨迹·毕业结果", "有毕业结果样本的去向分布及来源。", "chart_series", "alert:trajectory:graduation", "code/backend/api/routers/alert_trajectory.py#_bucket_stats"),
        ),
    ),
    _metric(
        "A-20", "critical_pending_review_student_count", "学业预警监控",
        "严重且仍有待核查学生数", "最高风险为严重且至少一条当前规则仍待核查的去重学生数。",
        "COUNT(DISTINCT student_id WHERE 最高风险=严重 AND 管理状态=待核查)",
        "待核查是管理过程状态，不表示风险原因已经确定。",
        "形成本轮优先核查的基础队列。",
        "fact_alert / alert_event", "学生×当前快照", "预警或核查状态更新后", "2.0",
        "code/backend/api/routers/alert_monitor.py#alert_summary",
        (_page(ALERT, "预警监控·严重且待核查", "摘要卡与名单组合筛选。", "kpi_card", "alert:summary:critical-pending", "code/frontend/src/views/teaching-analysis/alert/index.vue#kpiCards"),),
    ),
    _metric(
        "A-21", "pending_review_student_count", "学业预警监控",
        "仍有待核查学生数", "当前预警学生中至少一条规则尚无有效核查记录的去重人数。",
        "COUNT(DISTINCT student_id WHERE 任一当前预警workflow_status=new)",
        "一名学生部分规则已核查、部分规则待核查时仍计入。",
        "评估尚需形成核查事实的工作量。",
        "fact_alert / alert_event", "学生×当前快照", "核查状态更新后", "2.0",
        "code/backend/api/routers/alert_monitor.py#alert_summary",
        (_page(ALERT, "预警监控·待核查学生", "摘要卡、名单筛选和管理状态列。", "kpi_card", "alert:summary:pending", "code/frontend/src/views/teaching-analysis/alert/index.vue#kpiCards"),),
    ),
    _metric(
        "A-24", "alert_priority_score", "学业预警监控",
        "优先核查分", "按已发布优先级规则组合最高风险、核查状态、规则叠加和持续时长。",
        "最高风险分（严重50、警告30、提醒15）＋管理状态分（待核查15、核查中8）＋多规则分〔MIN(MAX(当前规则数－1,0),3)×5〕＋持续时长分（≥60天10、≥30天5、其余0）",
        "仅用于安排核查先后，不是风险概率、学生评价或处分依据。",
        "将有限核查精力优先用于风险高、证据叠加且尚未闭合的学生。",
        "fact_alert / alert_event", "学生×当前快照", "预警或核查状态更新后", "2.0",
        "code/backend/api/routers/alert_monitor.py#alert_priority",
        (_page(ALERT, "预警监控·本轮优先核查队列", "优先分、原因分解和学生核查入口。", "priority_queue", "alert:priority:score", "code/frontend/src/views/teaching-analysis/alert/index.vue#priorityRows"),),
    ),
    _metric(
        "A-25", "current_alert_time_distribution", "学业预警监控",
        "当前预警时间分布", "当前仍命中的预警按生成月份汇总去重学生数和规则触发次数。",
        "按生成月份汇总当前有效预警学生数与记录数，取最近有数据月份",
        "这是当前风险池的生成时间结构，不是历史月度新增趋势；无数据月份不补零。",
        "识别当前风险池中滞留时间较长的对象。",
        "fact_alert", "生成月份×当前快照", "预警重算后", "2.0",
        "code/backend/api/routers/alert_monitor.py#alert_time_distribution",
        (_page(ALERT, "预警监控·当前预警时间分布", "学生数与规则触发次数图表。", "chart", "alert:time-distribution", "code/frontend/src/views/teaching-analysis/alert/index.vue#timeOption"),),
    ),
    _metric(
        "A-26", "organization_active_alert_student_rate", "学业预警监控",
        "组织当前预警学生率", "组织当前预警去重学生占相同查询范围内有效在籍学生的比例。",
        "组织当前预警去重学生数÷同一查询条件下组织有效在籍学生数×100%",
        "组织与年级条件同时约束分子分母；预警类型、等级只约束分子。",
        "发现预警学生相对集中的组织。",
        "fact_alert / dim_student / dim_college / dim_major / dim_class", "组织×当前查询", "预警或学籍更新后", "2.0",
        "code/backend/api/routers/alert_monitor.py#alert_distribution",
        (_page(ALERT, "预警监控·组织当前预警学生率", "学院、专业或班级分布和基准线。", "chart", "alert:distribution:organization-rate", "code/frontend/src/views/teaching-analysis/alert/index.vue#distributionOption"),),
    ),
    _metric(
        "A-27", "post_first_year_no_new_failure_student_count", "学业预警监控",
        "后续未再出现未通过学生数", "大一有未通过记录、后续常规学期已有成绩且没有未通过记录的去重学生数。",
        "COUNT(DISTINCT student_id WHERE 大一未通过>0 AND 后续有效修读>0 AND 后续未通过=0)",
        "只表示后续结果改善，不表示原未通过课程已经通过。",
        "保留改善证据，避免长期沿用大一标签。",
        "grade_attempt / dim_student", "学生×低年级观察期", "成绩发布后", "2.0",
        "code/backend/api/routers/v2.py#early_setback_topic",
        (_page(ALERT, "低年级风险观察·后续未再出现未通过", "摘要卡、组织表和名单预设。", "kpi_card", "alert:early-setback:recovered", "code/frontend/src/views/teaching-analysis/alert/EarlySetback.vue#kpis"),),
    ),
    _metric(
        "A-28", "post_first_year_persistent_failure_student_count", "学业预警监控",
        "后续持续出现未通过学生数", "大一有未通过记录且后续未通过记录数超过大一阶段的去重学生数。",
        "COUNT(DISTINCT student_id WHERE 后续未通过记录数>大一未通过记录数)",
        "按记录数描述持续出现，不推断教师、课程或学生个人原因。",
        "优先进入学生和课程证据核查。",
        "grade_attempt / dim_student", "学生×低年级观察期", "成绩发布后", "2.0",
        "code/backend/api/routers/v2.py#early_setback_topic",
        (_page(ALERT, "低年级风险观察·后续持续出现未通过", "摘要卡、组织排序和名单预设。", "kpi_card", "alert:early-setback:persistent", "code/frontend/src/views/teaching-analysis/alert/EarlySetback.vue#kpis"),),
    ),
    _metric(
        "A-29", "post_first_year_pending_observation_student_count", "学业预警监控",
        "暂无后续成绩学生数", "大一有未通过记录但尚无后续常规学期有效成绩的去重学生数。",
        "COUNT(DISTINCT student_id WHERE 大一未通过>0 AND 后续有效修读记录=0)",
        "不可观察不等于改善或恶化；需要在后续成绩发布后复核。",
        "区分不可观察样本与持续困难样本。",
        "grade_attempt / dim_student", "学生×低年级观察期", "成绩发布后", "2.0",
        "code/backend/api/routers/v2.py#early_setback_topic",
        (_page(ALERT, "低年级风险观察·暂无后续成绩", "摘要卡与名单预设。", "kpi_card", "alert:early-setback:pending", "code/frontend/src/views/teaching-analysis/alert/EarlySetback.vue#kpis"),),
    ),
    _metric(
        "A-30", "latest_alert_generated_date", "学业预警监控",
        "最新预警统计时间", "当前查询范围内仍有效预警记录的最大生成日期。",
        "MAX（当前有效预警created_at）按日期展示",
        "只说明当前风险池最后生成记录日期，不代表全部源数据更新时间。",
        "帮助判断当前预警统计的新鲜度。",
        "fact_alert", "当前查询范围", "预警重算后", "2.0",
        "code/backend/api/routers/alert_monitor.py#alert_time_distribution",
        (_page(ALERT, "预警监控·最新预警统计时间", "页面标题旁的数据时点。", "context", "alert:header:latest-date", "code/frontend/src/views/teaching-analysis/alert/index.vue#latestGeneratedDate"),),
    ),
    _metric(
        "A-31", "early_year_observable_student_count", "学业预警监控",
        "纳入低年级观察学生数", "有有效入学年且大一第一或第二常规学期至少一条有效成绩的去重学生数。",
        "COUNT(DISTINCT student_id WHERE 大一常规学期有效成绩记录数>0)",
        "无有效入学年或大一常规学期无有效成绩的学生不进入分母。",
        "作为早期受挫比例分母并说明观察覆盖。",
        "grade_attempt / dim_student", "学生×大一观察期", "成绩发布后", "2.0",
        "code/backend/api/routers/v2.py#early_setback_topic",
        (_page(ALERT, "低年级风险观察·纳入观察学生", "摘要卡及各组织观察样本数。", "kpi_card", "alert:early-setback:eligible", "code/frontend/src/views/teaching-analysis/alert/EarlySetback.vue#kpis"),),
    ),
    _metric(
        "D-01", "student_term_weighted_gpa", "学生成长与学业分析",
        "学期GPA", "学生在指定学期的课程绩点按计入GPA学分加权结果。",
        "Σ（课程绩点×课程学分）÷Σ计入GPA课程学分",
        "缺少绩点或有效学分时不计算；列表、证据和档案应复用同一结果。",
        "形成可跨页面核对的学期成长轨迹。",
        "agg_student_term_growth / fact_grade", "学生×学期", "成绩发布后", "2.0",
        "code/backend/api/student_growth.py#_term_facts",
        (
            _page(STUDENT, "学生成长名单·GPA起点与终点", "起始和目标学期GPA及变化。", "table_column", "students:growth-list:gpa", "code/frontend/src/views/teaching-analysis/students/Analysis.vue#studentCols"),
            _page(STUDENT, "我的学生/班级·本学期GPA", "导师学生表和班级学生展开表。", "table_column", "students:my-scope:term-gpa", "code/backend/api/routers/students.py#_scope_metrics"),
            _page(STUDENT, "学生详情·学期成长轨迹·GPA", "学期汇总与GPA趋势。", "chart_series", "students:detail:semester-gpa", "code/frontend/src/views/teaching-analysis/students/Detail.vue#semesterSummary"),
        ),
    ),
    _metric(
        "D-02", "student_gpa_change", "学生成长与学业分析",
        "GPA变化", "目标学期GPA减去起始学期GPA。",
        "目标学期GPA－起始学期GPA",
        "两个参与学期均有有效GPA时才计算。",
        "判断所选观察区间的绩点方向和幅度。",
        "agg_student_term_growth", "学生×学期对", "成绩发布后", "2.0",
        "code/backend/api/student_growth.py#build_growth_snapshot",
        (_page(STUDENT, "学生成长名单·GPA起点→终点", "名单展示两端值和变化方向。", "table_column", "students:growth-list:gpa-change", "code/frontend/src/views/teaching-analysis/students/Analysis.vue#studentCols"),),
    ),
    _metric(
        "D-03", "student_term_failed_course_count", "学生成长与学业分析",
        "学期未通过课程数", "学生指定学期内结果未通过的不同课程数。",
        "COUNT(DISTINCT course_id WHERE 学期有效结果未通过)",
        "同一学生同一课程同学期重复记录只算一门；不等于未通过记录数。",
        "观察当期困难涉及多少门课程。",
        "agg_student_term_growth / fact_grade", "学生×学期", "成绩发布后", "2.0",
        "code/backend/api/student_growth.py#_term_facts",
        (
            _page(STUDENT, "学生成长名单·未通过起点与终点", "起始和目标学期未通过课程数。", "table_column", "students:growth-list:fail-count", "code/frontend/src/views/teaching-analysis/students/Analysis.vue#studentCols"),
            _page(STUDENT, "我的学生/班级·本学期未通过", "导师和班级学生行的课程数。", "table_column", "students:my-scope:fail-count", "code/backend/api/routers/students.py#_term_fail_count_map"),
            _page(STUDENT, "学生详情·学期成长轨迹·未通过课程数", "学期汇总中的未通过课程数。", "detail_value", "students:detail:semester-fails", "code/frontend/src/views/teaching-analysis/students/Detail.vue#semesterSummary"),
        ),
    ),
    _metric(
        "D-04", "student_failed_course_count_change", "学生成长与学业分析",
        "未通过课程数变化", "目标学期未通过课程数减去起始学期未通过课程数。",
        "目标学期未通过课程数－起始学期未通过课程数",
        "两个参与学期均有有效成绩证据时才计算。",
        "判断困难范围扩大、收缩或保持。",
        "agg_student_term_growth", "学生×学期对", "成绩发布后", "2.0",
        "code/backend/api/student_growth.py#build_growth_snapshot",
        (_page(STUDENT, "学生成长名单·未通过起点→终点", "名单展示课程数变化。", "table_column", "students:growth-list:fail-change", "code/frontend/src/views/teaching-analysis/students/Analysis.vue#studentCols"),),
    ),
    _metric(
        "D-06", "student_academic_profile_migration", "学生成长与学业分析",
        "学业画像迁移", "联合GPA变化和未通过课程数变化，将可比较学生分类。",
        "GPA变化≥0.3且未通过课程数未增加，或未通过课程数至少减少1且GPA下降未达到0.3，判为改善；GPA变化≤-0.3且未通过课程数未减少，或未通过课程数至少增加1且GPA上升未达到0.3，判为恶化；改善与恶化信号并存判为分化，其余判为稳定",
        "仅对两个参与学期均有有效成绩证据的学生分类；阈值属于规则版本。",
        "区分改善、恶化、表现分化和基本稳定。",
        "agg_student_term_growth", "学生×学期对", "成绩发布后", "2.0",
        "code/backend/api/student_growth.py#_classification",
        (_page(STUDENT, "学生成长名单·变化结论", "改善、恶化、分化、稳定分类。", "table_column", "students:growth-list:migration", "code/backend/api/student_growth.py#build_growth_snapshot"),),
    ),
    _metric(
        "D-07", "clearly_improved_student_count", "学生成长与学业分析",
        "明确改善学生", "学业画像迁移结果为明确改善的去重学生数。",
        "COUNT(DISTINCT student_id WHERE 学业画像迁移=明确改善)",
        "观察学期不同会改变分组；分母为两学期均有成绩证据的学生。",
        "识别已出现积极变化的学生。",
        "agg_student_term_growth", "授权范围×学期对", "成绩发布后", "2.0",
        "code/backend/api/student_growth.py#build_growth_snapshot",
        (_page(STUDENT, "学生成长概览·明确改善学生", "指标卡与名单预设。", "kpi_card", "students:growth:improved", "code/frontend/src/views/teaching-analysis/students/Analysis.vue#metricCards"),),
    ),
    _metric(
        "D-08", "clearly_declined_student_count", "学生成长与学业分析",
        "明确恶化学生", "学业画像迁移结果为明确恶化的去重学生数。",
        "COUNT(DISTINCT student_id WHERE 学业画像迁移=明确恶化)",
        "不是预警等级，也不自动触发处置。",
        "提前识别成绩与未通过情况明显恶化的学生。",
        "agg_student_term_growth", "授权范围×学期对", "成绩发布后", "2.0",
        "code/backend/api/student_growth.py#build_growth_snapshot",
        (
            _page(STUDENT, "学生成长概览·明确恶化学生", "指标卡与名单预设。", "kpi_card", "students:growth:declined", "code/frontend/src/views/teaching-analysis/students/Analysis.vue#metricCards"),
            _page(STUDENT, "学生成长·组织比较·明确恶化率", "组织表中的恶化人数和比例。", "table_column", "students:growth:organization-declined", "code/backend/api/student_growth.py#_organization_rows"),
        ),
    ),
    _metric(
        "D-10", "repeated_unresolved_course_student_count", "学生成长与学业分析",
        "重复未解决课程", "存在同一课程至少两次未通过且最新有效结果仍未通过的学生数。",
        "COUNT(DISTINCT student_id WHERE 任一课程fail_count≥2且latest_is_pass=0)",
        "最新有效结果已通过的课程转入历史已解决，不进入本指标。",
        "识别反复受挫且当前仍需解决的课程和学生。",
        "agg_student_course_outcome", "学生×统计时点", "成绩发布后", "2.0",
        "code/backend/api/student_growth.py#_unresolved_course_outcomes",
        (
            _page(STUDENT, "学生成长概览·重复未解决", "指标卡、关注分组和名单优先级。", "kpi_card", "students:growth:repeated-unresolved", "code/frontend/src/views/teaching-analysis/students/Analysis.vue#metricCards"),
            _page(STUDENT, "学生详情·历史未通过课程·重复未解决", "课程状态标签与失败次数。", "table_column", "students:detail:repeated-unresolved", "code/frontend/src/views/teaching-analysis/students/Detail.vue#failTrace"),
        ),
    ),
    _metric(
        "D-11", "student_alert_history", "学生成长与学业分析",
        "历史预警记录", "学生历次预警的时间、规则、等级、证据和状态变化。",
        "按学生读取全部预警记录并按时间倒序保留规则版本",
        "历史预警与当前有效预警必须分开解释。",
        "比较学生风险变化并保留证据链。",
        "fact_alert / alert_event / alert_event_history", "学生×预警记录", "预警或核查状态更新后", "2.0",
        "code/backend/api/routers/alert.py#student_detail",
        (_page(STUDENT, "学生详情·预警记录与成长轨迹", "预警历史、状态变化和时间线。", "detail_section", "students:detail:alert-history", "code/frontend/src/views/teaching-analysis/students/Detail.vue#alertHistory"),),
    ),
    _metric(
        "D-18", "my_class_academic_summary", "学生成长与学业分析",
        "我的班级", "按当前人员—行政班有效关系形成班级人数、GPA、未通过率、学分完成率和预警摘要。",
        "仅在当前登录人有效行政班关系范围内汇总班级学业指标",
        "班级汇总是工作范围视图，不得扩大到未授权班级。",
        "辅导员、班主任先看班级整体，再下钻学生。",
        "staff_student_scope / dim_student / fact_grade / alert_event", "人员×行政班×学期", "关系、成绩或预警更新后", "2.0",
        "code/backend/api/routers/students.py#my_scope",
        (_page(STUDENT, "我的班级学业关注·班级卡片", "班级汇总和展开学生表。", "workspace_summary", "students:my-scope:classes", "code/frontend/src/views/teaching-analysis/students/MyScope.vue#class-grid"),),
    ),
    _metric(
        "D-19", "my_mentee_academic_summary", "学生成长与学业分析",
        "我的学生", "按当前导师—学生有效关系逐人展示GPA、未通过课程、学分完成和预警。",
        "仅在当前登录人有效导师—学生关系范围内汇总和展示",
        "不得通过导师身份查看关系范围外学生。",
        "导师逐人掌握学业状态并安排核查顺序。",
        "staff_student_scope / dim_student / fact_grade / alert_event", "人员×学生×学期", "关系、成绩或预警更新后", "2.0",
        "code/backend/api/routers/students.py#my_scope",
        (_page(STUDENT, "我的学生学业关注·学生表", "导师范围的学生学业证据列表。", "workspace_table", "students:my-scope:mentees", "code/frontend/src/views/teaching-analysis/students/MyScope.vue#myStudentCols"),),
    ),
    _metric(
        "D-20", "comparable_student_coverage", "学生成长与学业分析",
        "可比较学生及覆盖率", "两个参与学期有效在籍名单交集人数及其占名单并集的比例。",
        "可比较学生数=两学期在籍学生交集；覆盖率=交集÷并集×100%",
        "学期在籍名单不可用时拒绝计算，不以当前学籍或成绩人数替代。",
        "先确认参与学生覆盖，再解释成长变化。",
        "历史学期students / dim_student", "授权范围×学期对", "学籍同步后", "2.0",
        "code/backend/api/student_growth.py#_comparison_cohort",
        (
            _page(STUDENT, "学生成长概览·可比较学生情况看板", "交集人数、并集人数和覆盖率。", "kpi_board", "students:growth:comparison-board", "code/frontend/src/views/teaching-analysis/students/Analysis.vue#comparison-board"),
            _page(STUDENT, "学生成长·组织比较·可比较覆盖", "学院、专业或班级覆盖率。", "table_column", "students:growth:organization-coverage", "code/backend/api/student_growth.py#_organization_rows"),
        ),
    ),
    _metric(
        "D-21", "continuous_setback_student_count", "学生成长与学业分析",
        "连续受挫学生", "起始学期和目标学期均至少有一门未通过课程的去重学生数。",
        "COUNT(DISTINCT student_id WHERE 起始学期未通过课程数>0 AND 目标学期未通过课程数>0)",
        "只表示两个观察学期均受挫，不等于每个连续学期均受挫。",
        "识别需要持续关注的学生。",
        "agg_student_term_growth", "授权范围×学期对", "成绩发布后", "2.0",
        "code/backend/api/student_growth.py#build_growth_snapshot",
        (_page(STUDENT, "学生成长概览·连续受挫学生", "指标卡、组织比较和名单预设。", "kpi_card", "students:growth:continuous", "code/frontend/src/views/teaching-analysis/students/Analysis.vue#metricCards"),),
    ),
    _metric(
        "D-22", "low_grade_first_setback_student_count", "学生成长与学业分析",
        "低年级首次受挫学生", "当前范围最新两个年级中，目标学期首次出现可观测未通过记录的去重学生数。",
        "COUNT(DISTINCT student_id WHERE 属于最新两个年级 AND 目标学期未通过>0 AND 更早历史无未通过)",
        "首次仅指已接入历史范围；历史数据不完整时必须披露边界。",
        "在受挫早期识别并安排学习支持。",
        "agg_student_term_growth / fact_grade / dim_student", "授权范围×学期对", "成绩发布后", "2.0",
        "code/backend/api/student_growth.py#build_growth_snapshot",
        (_page(STUDENT, "学生成长概览·低年级首次受挫", "指标卡、组织比较和名单预设。", "kpi_card", "students:growth:first-setback", "code/frontend/src/views/teaching-analysis/students/Analysis.vue#metricCards"),),
    ),
    _metric(
        "D-23", "current_unresolved_course_count", "学生成长与学业分析",
        "当前未解决课程", "历史曾未通过且同一课程最新有效结果仍未通过的不同课程数或清单。",
        "按学生和课程取最新有效结果，COUNT(DISTINCT course_id WHERE latest_is_pass=0且历史失败>0)",
        "每门课程只保留最新有效状态；课程替代和认定以培养质量模块为准。",
        "直接回答学生当前仍需解决哪些课程。",
        "agg_student_course_outcome / fact_grade", "学生×统计时点", "成绩发布后", "2.0",
        "code/backend/api/student_growth.py#_unresolved_course_outcomes",
        (
            _page(STUDENT, "学生成长名单·当前未通过课程", "当前未解决课程数和前五门课程。", "table_column", "students:growth-list:unresolved", "code/frontend/src/views/teaching-analysis/students/Analysis.vue#studentCols"),
            _page(STUDENT, "学生详情·历史未通过课程·当前未解决", "课程级当前状态与最近学期。", "table_column", "students:detail:unresolved", "code/frontend/src/views/teaching-analysis/students/Detail.vue#failTrace"),
        ),
    ),
    _metric(
        "D-24", "historically_resolved_course_count", "学生成长与学业分析",
        "历史已解决课程", "历史曾未通过但同一课程最新有效结果已通过的不同课程数或清单。",
        "按学生和课程取最新有效结果，COUNT(DISTINCT course_id WHERE 历史失败>0且latest_is_pass=1)",
        "作为成长证据，不计入当前未解决；后续再次失败时状态重新计算。",
        "核验补考、重修或后续学习已经取得的结果。",
        "agg_student_course_outcome / fact_grade", "学生×统计时点", "成绩发布后", "2.0",
        "code/backend/api/routers/alert.py#student_detail",
        (_page(STUDENT, "学生详情·历史未通过课程·历史已解决", "课程级解决状态和解决学期。", "table_column", "students:detail:resolved", "code/frontend/src/views/teaching-analysis/students/Detail.vue#failTrace"),),
    ),
    _metric(
        "D-25", "student_with_open_alert_event_count", "学生成长与学业分析",
        "当前有效预警", "预警事件工作流尚未进入已解决或已关闭的去重学生数。",
        "COUNT(DISTINCT student_id WHERE alert_event.workflow_status NOT IN resolved,closed)",
        "按学生计数；不同于当前规则触发记录数和事件条数。",
        "把当前成绩变化与仍需核查的正式预警事件对照。",
        "alert_event", "授权范围×统计时点", "预警事件状态更新后", "2.0",
        "code/backend/api/routers/students.py#_open_event_maps",
        (
            _page(STUDENT, "学生成长名单·当前有效预警", "学生行的未解除预警事件数量。", "table_column", "students:growth-list:open-alerts", "code/frontend/src/views/teaching-analysis/students/Analysis.vue#studentCols"),
            _page(STUDENT, "我的班级/学生·有未解除预警", "顶部去重学生数和班级范围汇总。", "kpi_card", "students:my-scope:students-with-open-alerts", "code/frontend/src/views/teaching-analysis/students/MyScope.vue#summary"),
        ),
    ),
    _metric(
        "D-26", "transparent_growth_priority_list", "学生成长与学业分析",
        "透明优先核查名单", "按公开的关注分组顺序组织学生名单，不生成隐藏综合风险分。",
        "按公开分组依次排序：同时命中连续受挫和重复未解决、低年级首次受挫、明确恶化且未通过课程增加、仅GPA明显下降、其他关注学生；不生成隐藏综合风险分",
        "关注分组允许重叠，人数不得直接相加；排序不是学生评价。",
        "让管理者知道先看谁及进入名单的原因。",
        "agg_student_term_growth / agg_student_course_outcome / alert_event", "学生×学期对", "成绩发布后", "2.0",
        "code/backend/api/routers/students.py#growth_priority_list",
        (_page(STUDENT, "学生成长·优先核查学生名单", "透明分组排序、触发原因和证据下钻。", "priority_list", "students:growth:priority-list", "code/frontend/src/views/teaching-analysis/students/Analysis.vue#studentCols"),),
    ),
    _metric(
        "O-06", "student_cumulative_gpa", "学生成长与学业分析",
        "学生总GPA", "按每门课程最新真实有效结果和课程学分计算累计学分加权GPA。",
        "Σ（最终有效课程绩点×课程学分）÷Σ计入GPA课程学分",
        "缺少绩点或有效学分的课程排除并披露；不是学期GPA。",
        "在学生证据和完整档案中提供统一累计GPA。",
        "fact_grade", "学生×累计观察期", "成绩发布后", "1.0",
        "code/backend/api/routers/alert.py#student_detail",
        (_page(STUDENT, "学生详情·总GPA", "学生详情KPI及纳入学分、排除课程说明。", "kpi_card", "students:detail:cumulative-gpa", "code/frontend/src/views/teaching-analysis/students/Detail.vue#kpis"),),
    ),
    _metric(
        "G-20", "student_earned_credit", "学生成长与学业分析",
        "获得学分", "按课程去重汇总学生历史通过课程的学分。",
        "SUM（每门已通过课程只计一次的课程学分）",
        "课程替代、认定和重复修读的正式规则仍需由培养质量模块核验。",
        "说明学生已取得学分并作为学分完成率分子。",
        "fact_grade", "学生×累计观察期", "成绩发布后", "2.0",
        "code/backend/api/academic_metrics.py#earned_credit_map",
        (_page(STUDENT, "学生详情·已修学分", "学生详情KPI和培养进度摘要。", "kpi_card", "students:detail:earned-credit", "code/backend/api/routers/alert.py#student_detail"),),
    ),
    _metric(
        "O-16", "student_credit_completion_rate", "学生成长与学业分析",
        "学分完成率", "学生已获得学分占专业年级要求总学分的比例。",
        "MIN（获得学分÷要求总学分×100%，100%）",
        "只对能够匹配有效要求总学分的学生计算。",
        "观察培养进度并支持班级、导师范围核查。",
        "fact_grade / fact_major_req", "学生×统计时点", "成绩或培养要求更新后", "2.0",
        "code/backend/api/routers/students.py#_scope_metrics",
        (
            _page(STUDENT, "我的学生/班级·学分完成率", "学生行的完成率进度。", "table_column", "students:my-scope:credit-ratio", "code/frontend/src/views/teaching-analysis/students/MyScope.vue#myStudentCols"),
            _page(STUDENT, "学生详情·培养进度", "已获学分、要求学分和完成率。", "detail_value", "students:detail:credit-completion", "code/backend/api/routers/alert.py#student_detail"),
        ),
    ),
    _metric(
        "TECH-CREDIT-COMPLETION-MEDIAN", "credit_completion_rate_median", "学生成长与学业分析",
        "学分完成率中位数", "当前人员关系范围内可计算学生学分完成率的中位数。",
        "MEDIAN（每生学分完成率）",
        "要求总学分缺失的学生不进入中位数；不是总体已修学分除以总体要求学分。",
        "用较稳健的集中趋势了解班级或导师学生培养进度。",
        "fact_grade / fact_major_req / staff_student_scope", "人员关系范围×统计时点", "成绩或培养要求更新后", "1.0",
        "code/backend/api/routers/students.py#_scope_metrics",
        (_page(STUDENT, "我的班级/学生·学分完成率中位数", "顶部汇总卡和班级卡。", "kpi_card", "students:my-scope:credit-median", "code/frontend/src/views/teaching-analysis/students/MyScope.vue#summary"),),
    ),
    _metric(
        "TECH-OPEN-ALERT-EVENT-COUNT", "open_alert_event_count", "学生成长与学业分析",
        "未解除预警事件数", "工作流状态尚未进入已解决或已关闭的预警事件条数。",
        "COUNT（alert_event WHERE workflow_status NOT IN resolved,closed）",
        "按事件条数统计；同一学生可对应多条，不等于当前规则触发次数或预警学生数。",
        "估算当前人员关系范围内需要核查的事件工作量。",
        "alert_event", "人员关系范围×统计时点", "预警事件状态更新后", "1.0",
        "code/backend/api/routers/students.py#_open_event_maps",
        (_page(STUDENT, "我的班级/学生·未解除预警事件", "顶部卡副值、班级卡和学生行。", "supporting_value", "students:my-scope:open-alert-events", "code/frontend/src/views/teaching-analysis/students/MyScope.vue#summary"),),
    ),
)


VERIFIED_ALIASES: tuple[dict, ...] = (
    {"metric_id": "O-05", "alias": "学生平均 GPA", "alias_type": "display", "source_ref": "code/frontend/src/views/teaching-analysis/dashboard/index.vue#managementSummary"},
    {"metric_id": "O-05", "alias": "本学期平均GPA", "alias_type": "display", "source_ref": "code/frontend/src/views/teaching-analysis/students/MyScope.vue#summary"},
    {"metric_id": "O-05", "alias": "范围GPA均值", "alias_type": "display", "source_ref": "code/backend/api/routers/students.py#analysis"},
    {"metric_id": "O-13", "alias": "当前预警", "alias_type": "display", "source_ref": "code/backend/api/routers/dashboard.py#dashboard"},
    {"metric_id": "O-13", "alias": "当前预警学生", "alias_type": "display", "source_ref": "code/frontend/src/views/teaching-analysis/alert/index.vue#kpiCards"},
    {"metric_id": "O-13", "alias": "A-01", "alias_type": "document_code", "source_ref": "文档/4-需求文档/公共需求/本科教学分析与学业决策支持平台需求调研及指标口径确认书V2.md#L273"},
    {"metric_id": "O-14", "alias": "当前预警学生率", "alias_type": "display", "source_ref": "code/frontend/src/views/teaching-analysis/alert/index.vue#kpiCards"},
    {"metric_id": "O-19", "alias": "成绩覆盖率", "alias_type": "search", "source_ref": "code/backend/api/routers/dashboard.py#dashboard"},
    {"metric_id": "TECH-SCOPE-FIRST-ATTEMPT-PASS-RATE", "alias": "首次通过率", "alias_type": "display", "source_ref": "code/frontend/src/views/teaching-analysis/dashboard/index.vue#coursePassRates"},
    {"metric_id": "A-21", "alias": "待核查学生", "alias_type": "display", "source_ref": "code/frontend/src/views/teaching-analysis/alert/index.vue#kpiCards"},
    {"metric_id": "A-24", "alias": "优先分", "alias_type": "display", "source_ref": "code/frontend/src/views/teaching-analysis/alert/index.vue#priorityRows"},
    {"metric_id": "A-27", "alias": "后续改善学生", "alias_type": "search", "source_ref": "code/backend/api/routers/v2.py#early_setback_topic"},
    {"metric_id": "D-08", "alias": "恶化学生", "alias_type": "search", "source_ref": "code/frontend/src/views/teaching-analysis/students/Analysis.vue#metricCards"},
    {"metric_id": "D-10", "alias": "重复未解决", "alias_type": "display", "source_ref": "code/frontend/src/views/teaching-analysis/students/Analysis.vue#metricCards"},
    {"metric_id": "D-22", "alias": "低年级首次受挫", "alias_type": "display", "source_ref": "code/frontend/src/views/teaching-analysis/students/Analysis.vue#metricCards"},
    {"metric_id": "D-23", "alias": "当前未通过课程", "alias_type": "display", "source_ref": "code/frontend/src/views/teaching-analysis/students/Analysis.vue#studentCols"},
    {"metric_id": "D-25", "alias": "有未解除预警", "alias_type": "display", "source_ref": "code/frontend/src/views/teaching-analysis/students/MyScope.vue#summary"},
)


VERIFIED_DEPENDENCIES: tuple[dict, ...] = (
    {"source_metric_id": "O-14", "target_metric_id": "O-13", "relation_type": "numerator", "description": "当前有效预警学生数是预警学生率分子。", "source_ref": "code/backend/api/routers/dashboard.py#dashboard"},
    {"source_metric_id": "O-14", "target_metric_id": "O-01", "relation_type": "denominator", "description": "同一授权范围在籍学生数是预警学生率分母。", "source_ref": "code/backend/api/routers/dashboard.py#dashboard"},
    {"source_metric_id": "O-19", "target_metric_id": "O-02", "relation_type": "numerator", "description": "有效成绩学生数是覆盖率分子。", "source_ref": "code/backend/api/routers/dashboard.py#dashboard"},
    {"source_metric_id": "O-19", "target_metric_id": "O-01", "relation_type": "denominator", "description": "同学期在籍学生数是覆盖率分母。", "source_ref": "code/backend/api/routers/dashboard.py#metric_history"},
    *({"source_metric_id": "O-17", "target_metric_id": metric_id, "relation_type": "comparison_input", "description": "学院横向偏离复用该基础指标的学院值和范围值。", "source_ref": "code/backend/api/routers/dashboard.py#dashboard"} for metric_id in ("O-03", "O-05", "O-10", "O-14", "O-19")),
    *({"source_metric_id": "O-18", "target_metric_id": metric_id, "relation_type": "period_input", "description": "可比学期变化复用该基础指标的相邻学期值。", "source_ref": "code/backend/api/routers/dashboard.py#metric_history"} for metric_id in ("O-05", "O-10", "O-14", "O-19", "TECH-SCOPE-FIRST-ATTEMPT-PASS-RATE", "G-13", "G-16", "C-18")),
    {"source_metric_id": "O-21", "target_metric_id": "O-20", "relation_type": "ranking_input", "description": "受影响学生数是重点课程的首要排序依据。", "source_ref": "code/backend/api/routers/dashboard.py#dashboard"},
    {"source_metric_id": "O-21", "target_metric_id": "O-11", "relation_type": "ranking_input", "description": "课程人次未通过率参与重点课程入选解释。", "source_ref": "code/backend/api/routers/dashboard.py#dashboard"},
    {"source_metric_id": "A-15", "target_metric_id": "A-14", "relation_type": "numerator", "description": "大一有未通过学生数是比例分子。", "source_ref": "code/backend/api/routers/v2.py#early_setback_topic"},
    {"source_metric_id": "A-15", "target_metric_id": "A-31", "relation_type": "denominator", "description": "纳入低年级观察学生数是比例分母。", "source_ref": "code/backend/api/routers/v2.py#early_setback_topic"},
    {"source_metric_id": "A-20", "target_metric_id": "A-03", "relation_type": "filter_input", "description": "严重且待核查先按学生最高风险筛选。", "source_ref": "code/backend/api/routers/alert_monitor.py#alert_summary"},
    {"source_metric_id": "A-20", "target_metric_id": "A-21", "relation_type": "filter_input", "description": "严重且待核查同时受待核查管理状态约束。", "source_ref": "code/backend/api/routers/alert_monitor.py#alert_summary"},
    *({"source_metric_id": "A-24", "target_metric_id": metric_id, "relation_type": "scoring_input", "description": "预警优先分使用该指标对应的风险、状态或叠加证据。", "source_ref": "code/backend/api/routers/alert_monitor.py#alert_priority"} for metric_id in ("A-03", "A-02", "A-21")),
    {"source_metric_id": "A-26", "target_metric_id": "O-13", "relation_type": "numerator", "description": "组织范围内当前有效预警学生数是比例分子。", "source_ref": "code/backend/api/routers/alert_monitor.py#alert_distribution"},
    {"source_metric_id": "A-26", "target_metric_id": "O-01", "relation_type": "denominator", "description": "组织范围内有效在籍学生数是比例分母。", "source_ref": "code/backend/api/routers/alert_monitor.py#alert_distribution"},
    {"source_metric_id": "D-02", "target_metric_id": "D-01", "relation_type": "period_input", "description": "GPA变化引用起始和目标学期GPA。", "source_ref": "code/backend/api/student_growth.py#build_growth_snapshot"},
    {"source_metric_id": "D-04", "target_metric_id": "D-03", "relation_type": "period_input", "description": "未通过课程数变化引用两个参与学期的课程数。", "source_ref": "code/backend/api/student_growth.py#build_growth_snapshot"},
    {"source_metric_id": "D-06", "target_metric_id": "D-02", "relation_type": "classification_input", "description": "画像迁移联合使用GPA变化。", "source_ref": "code/backend/api/student_growth.py#_classification"},
    {"source_metric_id": "D-06", "target_metric_id": "D-04", "relation_type": "classification_input", "description": "画像迁移联合使用未通过课程数变化。", "source_ref": "code/backend/api/student_growth.py#_classification"},
    {"source_metric_id": "D-07", "target_metric_id": "D-06", "relation_type": "classification_output", "description": "明确改善是学业画像迁移的一类结果。", "source_ref": "code/backend/api/student_growth.py#build_growth_snapshot"},
    {"source_metric_id": "D-08", "target_metric_id": "D-06", "relation_type": "classification_output", "description": "明确恶化是学业画像迁移的一类结果。", "source_ref": "code/backend/api/student_growth.py#build_growth_snapshot"},
    {"source_metric_id": "D-10", "target_metric_id": "D-23", "relation_type": "subset", "description": "重复未解决是当前未解决课程中的重复失败子集。", "source_ref": "code/backend/api/student_growth.py#_unresolved_course_outcomes"},
    {"source_metric_id": "D-21", "target_metric_id": "D-03", "relation_type": "period_input", "description": "连续受挫引用起始和目标学期未通过课程数。", "source_ref": "code/backend/api/student_growth.py#build_growth_snapshot"},
    {"source_metric_id": "D-22", "target_metric_id": "D-03", "relation_type": "period_input", "description": "低年级首次受挫引用目标学期未通过课程数和更早历史。", "source_ref": "code/backend/api/student_growth.py#build_growth_snapshot"},
    *({"source_metric_id": "D-26", "target_metric_id": metric_id, "relation_type": "priority_input", "description": "透明优先核查名单按公开关注指标排列。", "source_ref": "code/backend/api/routers/students.py#growth_priority_list"} for metric_id in ("D-08", "D-10", "D-21", "D-22", "D-02")),
    {"source_metric_id": "O-16", "target_metric_id": "G-20", "relation_type": "numerator", "description": "获得学分是学分完成率分子。", "source_ref": "code/backend/api/routers/students.py#_scope_metrics"},
    {"source_metric_id": "TECH-CREDIT-COMPLETION-MEDIAN", "target_metric_id": "O-16", "relation_type": "aggregation_input", "description": "范围中位数对每名可计算学生的学分完成率取中位数。", "source_ref": "code/backend/api/routers/students.py#_median"},
    {"source_metric_id": "D-18", "target_metric_id": "O-05", "relation_type": "summary_input", "description": "我的班级汇总复用学生平均GPA。", "source_ref": "code/backend/api/routers/students.py#_scope_metrics"},
    {"source_metric_id": "D-18", "target_metric_id": "O-10", "relation_type": "summary_input", "description": "我的班级汇总复用本学期未通过学生率。", "source_ref": "code/backend/api/routers/students.py#_scope_metrics"},
    {"source_metric_id": "D-18", "target_metric_id": "TECH-CREDIT-COMPLETION-MEDIAN", "relation_type": "summary_input", "description": "我的班级汇总展示学分完成率中位数。", "source_ref": "code/backend/api/routers/students.py#_scope_metrics"},
    {"source_metric_id": "D-18", "target_metric_id": "D-25", "relation_type": "summary_input", "description": "我的班级汇总展示有未解除预警学生数。", "source_ref": "code/backend/api/routers/students.py#_scope_metrics"},
    *({"source_metric_id": "D-19", "target_metric_id": metric_id, "relation_type": "row_input", "description": "我的学生逐人展示该学业指标。", "source_ref": "code/backend/api/routers/students.py#_scope_metrics"} for metric_id in ("D-01", "D-03", "O-16", "D-25")),
)


VERIFIED_RULE_BINDINGS: tuple[dict, ...] = (
    {"metric_id": "A-09", "rule_type": "alert_rule", "rule_id": "R1", "role": "trigger", "description": "GPA持续下降的当前启用阈值和观察窗。", "source_ref": "code/backend/etl/seed.py#ALERT_RULES"},
    {"metric_id": "A-10", "rule_type": "alert_rule", "rule_id": "R2", "role": "trigger", "description": "未解决课程累积严重规则。", "source_ref": "code/backend/etl/seed.py#ALERT_RULES"},
    {"metric_id": "A-10", "rule_type": "alert_rule", "rule_id": "R2W", "role": "trigger", "description": "未解决课程累积警告规则。", "source_ref": "code/backend/etl/seed.py#ALERT_RULES"},
    {"metric_id": "A-11", "rule_type": "alert_rule", "rule_id": "R3", "role": "trigger", "description": "学分缺口预警阈值。", "source_ref": "code/backend/etl/seed.py#ALERT_RULES"},
    {"metric_id": "A-12", "rule_type": "alert_rule", "rule_id": "R4", "role": "trigger", "description": "核心或必修课程未解决规则。", "source_ref": "code/backend/etl/seed.py#ALERT_RULES"},
    {"metric_id": "A-13", "rule_type": "alert_rule", "rule_id": "R6", "role": "trigger", "description": "GPA和未解决课程组合风险规则。", "source_ref": "code/backend/etl/seed.py#ALERT_RULES"},
    *({"metric_id": "O-13", "rule_type": "alert_rule", "rule_id": rule_id, "role": "output_population", "description": "当前有效预警学生数由已启用规则命中结果去重形成。", "source_ref": "code/backend/etl/seed.py#ALERT_RULES"} for rule_id in ("R1", "R2", "R2W", "R3", "R4", "R6")),
    *({"metric_id": "A-02", "rule_type": "alert_rule", "rule_id": rule_id, "role": "output_record", "description": "当前规则触发次数包含该规则的有效记录。", "source_ref": "code/backend/etl/seed.py#ALERT_RULES"} for rule_id in ("R1", "R2", "R2W", "R3", "R4", "R6")),
    {"metric_id": "A-24", "rule_type": "priority_rule", "rule_id": "alert-priority-v2.0", "role": "calculation", "description": "风险、管理状态、叠加规则和持续时长的评分权重。", "source_ref": "code/backend/api/routers/alert_monitor.py#alert_priority"},
    {"metric_id": "A-19", "rule_type": "trajectory_rule", "rule_id": "alert-trajectory-gpa-band-v1", "role": "classification", "description": "后续GPA变化方向分档阈值。", "source_ref": "code/backend/api/routers/alert_trajectory.py#GPA_DELTA_BAND"},
    {"metric_id": "A-19", "rule_type": "confidence_rule", "rule_id": "alert-trajectory-low-confidence-v1", "role": "disclosure", "description": "轨迹分桶的低置信样本阈值。", "source_ref": "code/backend/api/routers/alert_trajectory.py#LOW_CONFIDENCE_SAMPLE"},
    {"metric_id": "O-21", "rule_type": "ranking_rule", "rule_id": "dashboard-focus-course-v3", "role": "ranking", "description": "重点课程样本、影响规模、课程属性和变化排序规则。", "source_ref": "code/backend/api/routers/dashboard.py#dashboard"},
    {"metric_id": "D-06", "rule_type": "classification_rule", "rule_id": "student-growth-v2", "role": "classification", "description": "GPA变化与未通过课程变化联合分类规则。", "source_ref": "code/backend/api/student_growth.py#_classification"},
    {"metric_id": "D-07", "rule_type": "classification_rule", "rule_id": "student-growth-v2", "role": "output", "description": "明确改善分类及GPA变化阈值。", "source_ref": "code/backend/api/student_growth.py#_classification"},
    {"metric_id": "D-08", "rule_type": "classification_rule", "rule_id": "student-growth-v2", "role": "output", "description": "明确恶化分类及GPA变化阈值。", "source_ref": "code/backend/api/student_growth.py#_classification"},
    {"metric_id": "D-22", "rule_type": "scope_rule", "rule_id": "student-growth-v2", "role": "cohort", "description": "当前实现以授权范围内最新两个年级识别低年级群体。", "source_ref": "code/backend/api/student_growth.py#build_growth_snapshot"},
    {"metric_id": "D-26", "rule_type": "priority_rule", "rule_id": "student-growth-v2", "role": "ranking", "description": "透明优先名单的公开分组顺序。", "source_ref": "code/backend/api/routers/students.py#growth_priority_list"},
)


# Existing IMPLEMENTED_METRICS only record one page binding.  These usages make
# repeated appearances (cards, tables, sorting and history dialogs) explicit.
VERIFIED_USAGE_POINTS: tuple[dict, ...] = (
    {"metric_id": "O-01", **_page(DASHBOARD, "总览首页·分析范围·在籍学生数", "范围背景卡和学院规模字段。", "kpi_card", "dashboard:scope:students", "code/backend/api/routers/dashboard.py#dashboard")},
    {"metric_id": "O-01", **_page(DASHBOARD, "学院/专业详情·在籍学生数", "学院和专业详情KPI以及年级样本数。", "kpi_card", "dashboard:drill:students", "code/backend/api/routers/dashboard.py#college_detail")},
    {"metric_id": "O-10", **_page(DASHBOARD, "总览首页·当前挂科学生率", "背景KPI、管理摘要和学院比较。", "kpi_card", "dashboard:current-fail-rate:cards", "code/backend/api/routers/dashboard.py#dashboard")},
    {"metric_id": "O-10", **_page(DASHBOARD, "总览首页·学院比较·挂科学生率排序", "学院风险排序与偏离计算。", "sort_key", "dashboard:college:sort-fail-rate", "code/frontend/src/views/teaching-analysis/dashboard/index.vue#collegeRows")},
    {"metric_id": "O-10", **_page(DASHBOARD, "总览下钻·挂科学生率历史弹窗", "学校、学院和专业逐学期变化。", "history_dialog", "dashboard:history:current-fail-rate", "code/backend/api/routers/dashboard.py#metric_history")},
    {"metric_id": "O-10", **_page(DASHBOARD, "学院/专业详情·当前挂科学生率", "详情KPI和年级风险核查。", "kpi_card", "dashboard:drill:current-fail-rate", "code/backend/api/routers/dashboard.py#college_detail")},
    {"metric_id": "O-13", **_page(ALERT, "预警监控·当前预警学生", "去重学生摘要卡和全部名单预设。", "kpi_card", "alert:summary:current-students", "code/backend/api/routers/alert_monitor.py#alert_summary")},
    {"metric_id": "O-13", **_page(DASHBOARD, "专业详情·当前有效预警学生数", "专业详情KPI和专业预警名单下钻。", "kpi_card", "dashboard:major:active-alert-count", "code/backend/api/routers/dashboard.py#major_detail")},
    {"metric_id": "G-08", **_page(DASHBOARD, "总览首页·历史挂科经历率", "观察期历史受挫背景卡。", "kpi_card", "dashboard:history-fail-rate", "code/backend/api/routers/dashboard.py#dashboard")},
    {"metric_id": "T-01", **_page(DASHBOARD, "总览首页·本学期开课门数", "分析范围背景卡。", "kpi_card", "dashboard:scope:courses", "code/backend/api/routers/dashboard.py#dashboard")},
    {"metric_id": "CTX-TEACHER-COUNT", **_page(DASHBOARD, "总览首页·相关授课教师数", "受限身份的分析范围背景卡。", "kpi_card", "dashboard:scope:teachers", "code/backend/api/routers/dashboard.py#dashboard")},
    {"metric_id": "C-18", **_page(DASHBOARD, "总览首页·公共必修首次通过率", "课程通过率结构和历史变化。", "kpi_card", "dashboard:pass-rate:public-required", "code/backend/api/routers/dashboard.py#_v2_pass_stats")},
    {"metric_id": "C-18", **_page(DASHBOARD, "总览下钻·公共必修首次通过率历史弹窗", "逐学期公共必修首次通过率。", "history_dialog", "dashboard:history:public-required-pass", "code/backend/api/routers/dashboard.py#metric_history")},
    {"metric_id": "G-13", **_page(DASHBOARD, "总览首页·补考通过率", "课程通过率结构和重点课程表。", "kpi_card", "dashboard:pass-rate:makeup", "code/backend/api/routers/dashboard.py#_v2_pass_stats")},
    {"metric_id": "G-13", **_page(DASHBOARD, "总览下钻·补考通过率历史弹窗", "逐学期补考通过率。", "history_dialog", "dashboard:history:makeup-pass", "code/backend/api/routers/dashboard.py#metric_history")},
    {"metric_id": "G-16", **_page(DASHBOARD, "总览首页·重修通过率", "课程通过率结构和重点课程表。", "kpi_card", "dashboard:pass-rate:retake", "code/backend/api/routers/dashboard.py#_v2_pass_stats")},
    {"metric_id": "G-16", **_page(DASHBOARD, "总览下钻·重修通过率历史弹窗", "逐学期重修通过率。", "history_dialog", "dashboard:history:retake-pass", "code/backend/api/routers/dashboard.py#metric_history")},
)


VERIFIED_ISSUES: tuple[dict, ...] = (
    {
        "metric_id": "O-13", "issue_type": "duplicate_document_code",
        "severity": "info", "status": "documented",
        "description": "确认书O-13与A-01描述同一当前预警去重学生口径；代码目录保留已实施O-13为规范指标，A-01登记为文档编号别名。",
        "source_ref": "文档/4-需求文档/公共需求/本科教学分析与学业决策支持平台需求调研及指标口径确认书V2.md#L127,L273",
    },
    {
        "metric_id": "TECH-SCOPE-FIRST-ATTEMPT-PASS-RATE", "issue_type": "same_name_different_unit",
        "severity": "warning", "status": "open",
        "description": "总览当前实现按首次修读人次聚合；确认书G-05行仍含按学生人数表述，因此使用独立技术指标，未与G-05强制合并。",
        "source_ref": "code/backend/api/routers/dashboard.py#_v2_pass_stats",
    },
    {
        "metric_id": "TECH-OPEN-ALERT-EVENT-COUNT", "issue_type": "same_name_different_object",
        "severity": "info", "status": "documented",
        "description": "页面俗称“未解除预警”，这里统计alert_event工作流事件条数；A-02统计当前fact_alert规则触发记录，D-25统计涉及学生数，三者不得合并。",
        "source_ref": "code/backend/api/routers/students.py#_open_event_maps",
    },
    {
        "metric_id": "A-19", "issue_type": "gpa_submetric_formula_difference",
        "severity": "warning", "status": "open",
        "description": "同类轨迹子项当前按fact_grade.gpa算术平均形成学期GPA，与D-01学分加权学期GPA不同；保留独立复合指标，不声明依赖D-01。",
        "source_ref": "code/backend/api/routers/alert_trajectory.py#compute_trajectory",
    },
    {
        "metric_id": "A-19", "issue_type": "mixed_real_and_simulated_source",
        "severity": "warning", "status": "open",
        "description": "轨迹毕业结果优先使用V2真实数据，缺失时回退fact_graduation合成数据；页面必须继续披露来源计数。",
        "source_ref": "code/backend/api/routers/alert_trajectory.py#compute_trajectory",
    },
    {
        "metric_id": "D-22", "issue_type": "implemented_cohort_interpretation",
        "severity": "info", "status": "documented",
        "description": "当前实现把授权范围内年级值倒序后的最新两个年级作为低年级群体；该选择已作为student-growth-v2规则绑定，不写入通用指标阈值。",
        "source_ref": "code/backend/api/student_growth.py#build_growth_snapshot",
    },
)
