<template>
  <main class="processing-page">
    <header class="heading"><div><span class="eyebrow">系统管理</span><h1>后台处理服务</h1><p>配置原型内置处理服务、核对真实状态，并维护组织简报的委托授权。</p></div><el-button :loading="loading" @click="load">刷新实际状态</el-button></header>
    <div v-if="error" class="notice error" role="alert">{{ error }}</div>
    <div v-if="!view&&!loading" class="notice warning">当前无法读取处理服务。页面不能确认服务正常；请通过项目现有启动工具启动8011服务后重新查询。</div>
    <template v-if="view">
      <section class="status-card"><div><span>服务实际就绪</span><b :class="{warning:!status.ready}">{{ status.ready===true?'就绪':status.ready===false?'未就绪':'尚未确认' }}</b><small>当前状态来自本次接口查询</small></div><div><span>调度心跳</span><b>{{ status.schedulerAlive===true?'运行中':status.schedulerAlive===false?'已停止':'以心跳记录为准' }}</b><small>{{ date(status.lastHeartbeat||status.heartbeatAt||status.schedulerHeartbeat||status.heartbeat) }}</small></div><div><span>恢复状态</span><b>{{ status.recoveryState==='blocked'?'恢复受阻':status.recoveryState==='ready'||status.recoveryState==='completed'?'已完成':status.recoveryState||'尚未确认' }}</b><small>{{ status.recoveryReason||status.recovery?.reason||'恢复核对完成后才允许新执行' }}</small></div><div><span>自动提交</span><b>{{ view.effective?.automaticEnabled?'已允许':'未允许' }}</b><small>开关控制新的自动任务，实际进程沿用项目启动方式</small></div></section>
      <section v-if="status.recoveryState==='blocked'" class="notice warning"><b>恢复受阻，暂不接受新执行</b><p>{{ status.recoveryReason||status.recovery?.reason }}</p><ul v-if="status.blockedWorkers?.length"><li v-for="worker in status.blockedWorkers" :key="worker.executionId">执行 {{ worker.executionId }} · 工作进程 {{ worker.pid||'未确认' }} · {{ worker.reason }}</li></ul><p>已获准的历史和诊断可继续查看。重新检查只核对工作进程归属及退出证据。</p><el-button :loading="busy" @click="recheck">重新检查恢复</el-button></section>
      <nav class="tabs" aria-label="服务管理分区"><button :class="{active:tab==='config'}" @click="tab='config'">服务配置</button><button :class="{active:tab==='grants'}" @click="tab='grants'">委托授权</button><button :class="{active:tab==='diagnostics'}" @click="tab='diagnostics'">运行诊断</button></nav>
      <section v-if="tab==='config'" class="panel">
        <header class="panel-heading"><h2>配置草稿</h2><span>草稿修订 {{ view.revision }} · 有效修订 {{ view.effective?.revision||view.effectiveRevision||'尚未应用' }}</span></header>
        <el-form label-position="top"><div class="form-grid"><el-form-item label="服务编号"><el-input :model-value="form.serviceId" disabled /></el-form-item><el-form-item label="名称（必填）"><el-input v-model="form.name" maxlength="100" /></el-form-item><el-form-item label="部署环境"><el-input :model-value="form.environment" disabled /></el-form-item><el-form-item label="实际服务地址"><el-input :model-value="view.serviceUrl||status.serviceUrl||'本机内置侧车 8011'" disabled /></el-form-item><el-form-item label="数据配置引用"><el-select v-model="form.dataConfigRef" :disabled="dataRefs.length<=1"><el-option v-for="item in dataRefs" :key="item.id" :value="item.id" :label="item.label||item.name||item.id" /></el-select></el-form-item><el-form-item label="模型配置引用"><el-select v-model="form.modelConfigRef" :disabled="modelRefs.length<=1"><el-option v-for="item in modelRefs" :key="item.id" :value="item.id" :label="item.label||item.name||item.id" /></el-select></el-form-item><el-form-item label="单次执行总预算（秒，20—300）"><el-input-number v-model="form.timeoutSeconds" :min="20" :max="300" /></el-form-item><el-form-item label="瞬时故障重试次数（0—1）"><el-input-number v-model="form.retryLimit" :min="0" :max="1" /></el-form-item></div><el-form-item label="允许新的自动任务"><el-switch v-model="form.automaticEnabled" active-text="允许" inactive-text="暂停" /></el-form-item></el-form>
        <p class="muted">取数、核验、保存和可选解释共用预算。草稿保存不改变有效配置；一般调整影响后续运行，授权撤销即时生效。</p><p class="muted">数据引用变化需暂停受影响计划并重新试跑。模型尚未接通时按事实模式运行，模型名称不代表真实可用。</p>
        <div class="actions"><el-button type="primary" :disabled="!dirty||!form.name.trim()||busy" :loading="busy" @click="save">保存草稿</el-button><el-button :disabled="dirty||busy" @click="check">只读检查</el-button><el-button :disabled="dirty||busy||checks?.state!=='passed'||checks?.revision!==view.revision" @click="apply">应用当前草稿</el-button></div>
        <p v-if="dirty" class="muted">本次编辑尚未保存，请先保存再检查或应用。</p>
        <section v-if="checks" class="checks"><h3>最近只读检查</h3><p>{{ checks.summary||checks.message||'请查看各项实际检查结果' }}</p><article v-for="(item,index) in checkItems" :key="index"><el-tag :type="item.ok===true||item.state==='passed'?'success':item.ok===false||item.state==='failed'?'danger':'warning'" effect="plain">{{ item.ok===true||item.state==='passed'?'通过':item.ok===false||item.state==='failed'?'失败':'未确认' }}</el-tag><b>{{ item.name||item.title||item.key||item.source }}</b><span>{{ item.message||item.reason||item.note }}</span></article><small>检查只进行必要的只读连接及依赖核对，不启动全量业务分析。</small></section>
      </section>
      <section v-else-if="tab==='grants'" class="panel">
        <header class="panel-heading"><div><h2>组织简报委托授权</h2><p>授权服务主体执行固定课程任务；它独立于授予者浏览器登录，按有效期及撤销控制。</p></div><el-button type="primary" :disabled="busy" @click="openGrant()">新增授权</el-button></header>
        <p class="muted">当前114管理身份同时具备分析权和拟授权范围后才能授予。授权不会扩大读者权限；学校账号角色变化不会自动同步撤销本登记。</p>
        <el-empty v-if="!grants.length" description="暂无委托授权。人工试跑和人工正式生成可先进行。" :image-size="60" />
        <article v-for="grant in grants" :key="grant.grantId||grant.id" class="grant-row"><div><b>{{ grant.name||grant.grantId||grant.id }}</b><p>{{ grantScope(grant) }} · {{ (grant.taskIds||grant.allowedTaskIds||[]).join('、') }}</p><small>有效至 {{ date(grant.validUntil||grant.expiresAt) }} · {{ grantStatus(grant) }}</small></div><div class="actions"><el-button :disabled="busy||grant.state==='revoked'||grant.status==='revoked'" @click="openGrant(grant)">续期授权</el-button><el-button type="danger" plain :disabled="busy||grant.state==='revoked'||grant.status==='revoked'" @click="revoke(grant)">撤销</el-button></div></article>
      </section>
      <section v-else class="panel"><h2>脱敏运行诊断</h2><p class="muted">只展示实际记录中的阶段、编号和错误原因。数据库连接串、密码、Bearer和密钥不回显。</p><dl><dt>服务实例</dt><dd>{{ status.serviceInstance||status.serviceInstanceId||status.instanceId||'未提供' }}</dd><dt>恢复最后检查</dt><dd>{{ date(status.lastRecoveryCheck||status.recovery?.checkedAt) }}</dd><dt>实际占用</dt><dd>个人 {{ status.interactiveActive??'未提供' }} / 2；后台 {{ status.backgroundActive??'未提供' }} / 1</dd><dt>待执行请求</dt><dd>{{ status.pendingCount??'未提供' }}</dd></dl><article v-for="(item,index) in diagnostics" :key="item.executionId||index" class="diagnostic-row"><b>{{ item.executionId||item.id||item.phase }}</b><p>{{ item.phase||item.state }} · {{ item.reason||item.summary||item.message }}</p><small>{{ date(item.createdAt||item.checkedAt) }}</small></article><h3>本服务的实际执行记录</h3><el-button :loading="runsLoading" @click="loadRuns">刷新记录</el-button><p v-if="runsError" class="error">{{ runsError }}</p><article v-for="run in executions" :key="run.executionId||run.id" class="diagnostic-row"><b>{{ run.executionId||run.id }}</b><p>{{ triggerLabel(run.trigger) }} · {{ runState(run.state) }} · {{ run.phase||'阶段未记录' }}</p><p>解释：{{ explanationStateLabel(run.explanationState) }} · 工作进程：{{ run.workerFinished===false?'尚未结束，仍占用名额':'已结束' }} · 服务配置修订 {{ run.serviceConfigRevision??'未记录' }}</p><p>{{ run.summary }}</p><small>{{ date(run.createdAt) }}</small></article><el-empty v-if="!executions.length&&!runsLoading" description="当前获准范围暂无执行记录" :image-size="48" /><el-pagination layout="prev, pager, next" :page-size="20" :total="runTotal" :current-page="runPage" @current-change="runPage=$event;loadRuns()" /></section>
    </template>
    <el-dialog v-model="grantOpen" :title="renewing?'续期委托授权':'新增委托授权'" width="min(610px,94vw)" append-to-body :close-on-click-modal="false"><p>仅授予课程首修观察 C-PERFORMANCE，只读分析用途。</p><el-form label-position="top"><el-form-item label="授权范围（必填）"><el-select v-model="grantCollege" clearable placeholder="留空为全校，需全校权限" :disabled="!!renewing"><el-option v-for="item in options.colleges" :key="item.id" :value="item.id" :label="item.name" /></el-select></el-form-item><el-form-item label="有效结束（必填）"><el-date-picker v-model="grantUntil" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" /></el-form-item></el-form><p v-if="grantError" class="error">{{ grantError }}</p><template #footer><el-button :disabled="busy" @click="grantOpen=false">取消</el-button><el-button type="primary" :disabled="!grantUntil" :loading="busy" @click="saveGrant">{{ renewing?'登记续期授权':'登记授权' }}</el-button></template></el-dialog>
  </main>
</template>
<script setup lang="ts">
import {computed,onBeforeUnmount,onMounted,ref,watch} from 'vue'
import {ElMessageBox} from 'element-plus'
import {authStore} from '@/store/auth'
import {expertResourcesApi as api,explanationStateLabel,type ProcessingConfig,type ProcessingView} from '@/api/aiDecision/expertResources'
import type {ExpertExecution,ResourceOptions} from '@/types/expertResources'
const view=ref<ProcessingView|null>(null),form=ref<ProcessingConfig>({serviceId:'',name:'',environment:'',dataConfigRef:'',modelConfigRef:'',automaticEnabled:false,timeoutSeconds:180,retryLimit:0}),baseline=ref(''),options=ref<ResourceOptions>({plans:[],semesters:[],colleges:[]}),loading=ref(false),busy=ref(false),error=ref(''),tab=ref('config'),checks=ref<Record<string,any>|null>(null),grantOpen=ref(false),grantCollege=ref(''),grantUntil=ref(''),grantError=ref(''),renewing=ref<Record<string,any>|null>(null)
let epoch=0,request=0
const executions=ref<ExpertExecution[]>([]),runPage=ref(1),runTotal=ref(0),runsLoading=ref(false),runsError=ref('');let runsRequest=0
const dirty=computed(()=>JSON.stringify(form.value)!==baseline.value),status=computed(()=>view.value?.status||{}),grants=computed(()=>view.value?.grants||[]),dataRefs=computed(()=>view.value?.dataConfigRefs||[{id:form.value.dataConfigRef,label:'114测试库（受保护配置）'}]),modelRefs=computed(()=>view.value?.modelConfigRefs||[{id:form.value.modelConfigRef,label:'专家模型配置（真实可用性见检查）'}]),diagnostics=computed(()=>status.value.diagnostics||view.value?.diagnostics||[]),checkItems=computed(()=>{const c=checks.value?.checks||checks.value?.items||[];return Array.isArray(c)?c:Object.entries(c).map(([key,value])=>({key,...(value as object)}))})
function date(value?:string){if(!value)return '未提供';const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString('zh-CN',{hour12:false,timeZone:'Asia/Shanghai'})}
function grantStatus(g:Record<string,any>){if(g.state==='revoked'||g.status==='revoked')return '已撤销';if(new Date(g.validUntil||g.expiresAt).getTime()<=Date.now())return '已过期';return g.state==='active'||g.status==='active'?'有效':'未确认'}
function grantScope(g:Record<string,any>){return g.scope?.type==='all'?'授权全范围':(g.scope?.collegeIds||[]).map((id:string)=>options.value.colleges.find(c=>String(c.id)===String(id))?.name||id).join('、')||'范围未提供'}
function accept(value:ProcessingView){view.value=value;form.value={...value.draft};baseline.value=JSON.stringify(form.value);checks.value=value.check||null}
async function load(){const current=++request,identity=epoch;loading.value=true;error.value='';try{const value=await api.processing();if(current===request&&identity===epoch)accept(value)}catch(e){if(current===request&&identity===epoch){view.value=null;error.value=`处理服务状态无法读取：${(e as Error).message}`}}finally{if(current===request)loading.value=false}}
async function save(){if(!view.value||!form.value.name.trim())return;busy.value=true;error.value='';try{accept(await api.saveProcessing({...form.value,expectedRevision:view.value.revision}));checks.value=null}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function check(){if(!view.value||dirty.value)return;busy.value=true;error.value='';try{checks.value=await api.checkProcessing(view.value.revision)}catch(e){error.value=`只读检查失败：${(e as Error).message}`}finally{busy.value=false}}
async function apply(){if(!view.value||dirty.value)return;busy.value=true;error.value='';try{accept(await api.applyProcessing(view.value.revision))}catch(e){error.value=`应用结果尚未确认，请刷新有效配置核对：${(e as Error).message}`}finally{busy.value=false}}
async function recheck(){busy.value=true;error.value='';try{await api.recheckRecovery();await load()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
function openGrant(g?:Record<string,any>){renewing.value=g||null;grantCollege.value=g?.scope?.collegeIds?.[0]||'';grantUntil.value='';grantError.value='';grantOpen.value=true}
async function saveGrant(){if(!grantUntil.value)return;if(new Date(grantUntil.value)<=new Date()){grantError.value='有效结束需晚于当前时间。';return}busy.value=true;grantError.value='';try{if(renewing.value)await api.renewGrant(renewing.value.grantId||renewing.value.id,renewing.value.revision,grantUntil.value);else await api.createGrant({scope:grantCollege.value?{type:'college',collegeIds:[grantCollege.value]}:{type:'all',collegeIds:[]},taskIds:['C-PERFORMANCE'],validUntil:grantUntil.value});grantOpen.value=false;await load()}catch(e){grantError.value=(e as Error).message}finally{busy.value=false}}
async function revoke(g:Record<string,any>){try{await ElMessageBox.confirm('撤销后，服务将在关键阶段重新校验授权，阻止不再合法的执行与发布。历史保持当前读者权限。','撤销委托授权',{type:'warning',confirmButtonText:'撤销',cancelButtonText:'取消'});busy.value=true;await api.revokeGrant(g.grantId||g.id,g.revision);await load()}catch(e){if(e!=='cancel'&&e!=='close')error.value=(e as Error).message}finally{busy.value=false}}
async function loadRuns(){const current=++runsRequest,identity=epoch;runsLoading.value=true;runsError.value='';try{const result=await api.processingExecutions((runPage.value-1)*20,20);if(current!==runsRequest||identity!==epoch)return;executions.value=result.items;runTotal.value=result.total}catch(e){if(current===runsRequest)runsError.value=(e as Error).message}finally{if(current===runsRequest)runsLoading.value=false}}
function runState(state:string){return ({queued:'等待执行',running:'执行中',completed:'事实完成',partial:'部分事实',blocked:'条件未满足',failed:'执行失败',cancelled:'已取消'} as Record<string,string>)[state]||state}
function triggerLabel(trigger?:string){if(!trigger)return '未记录';return trigger==='manual'?'人工执行':trigger.startsWith('test:')?'真实5分钟到期（验证用途）':trigger.startsWith('weekly:')?'真实每周到期':trigger.startsWith('initial:')?'自动启用首期':trigger.startsWith('recovery:')?'重启恢复补跑':trigger}
watch(tab,value=>{if(value==='diagnostics')void loadRuns()})
watch(()=>[authStore.user?.username,authStore.user?.activeIdentityId,authStore.user?.permissionContext?.scopeFingerprint].join('|'),()=>{epoch++;request++;runsRequest++;view.value=null;checks.value=null;grantOpen.value=false;executions.value=[];if(authStore.user)void load()})
onMounted(async()=>{void load();try{options.value=await api.options()}catch{/* scope options remain empty when unavailable */}});onBeforeUnmount(()=>{epoch++;request++})
</script>
<style scoped>
.processing-page{padding:26px 28px;max-width:1400px;margin:auto;color:#2d435e;--el-color-primary:#344b77}.heading,.panel-heading{display:flex;justify-content:space-between;align-items:flex-start;gap:20px}.eyebrow{font-size:12px;color:#7a899e}h1{font-size:24px;font-weight:600;margin:7px 0 10px}h2{font-size:17px;margin:0 0 12px;font-weight:600}h3{font-size:15px;font-weight:600}.heading p,.panel-heading p{font-size:13px;color:#70839b;line-height:1.8;margin:0}.status-card{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:15px;margin:26px 0}.status-card>div{border:1px solid #e0e7ef;border-radius:8px;padding:18px;background:white}.status-card span{display:block;font-size:12px;color:#73869f}.status-card b{display:block;font-size:20px;font-weight:600;margin:12px 0}.status-card small{display:block;font-size:11px;color:#8190a5;line-height:1.8}.tabs{display:flex;gap:26px;border-bottom:1px solid #e0e7ef;margin:24px 0}.tabs button{border:0;border-bottom:2px solid transparent;background:none;padding:12px 0;font:inherit;font-size:14px;color:#71829a;cursor:pointer}.tabs button.active{border-bottom-color:#344b77;color:#344b77;font-weight:600}.panel{border:1px solid #e0e7ef;border-radius:8px;padding:24px;background:#fff}.panel-heading{margin-bottom:24px}.panel-heading>span{font-size:12px;color:#8392a6}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 25px;max-width:850px}.form-grid .el-select{width:100%}.muted{font-size:12px;color:#7689a1;line-height:1.85}.notice{background:#f3f7fb;padding:14px;border-radius:7px;font-size:13px;line-height:1.8;margin:20px 0}.notice p{margin:8px 0}.warning{color:#98742d;background:#fff9ed}.error{color:#a73642;background:#fff2f4}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}.actions>.el-button{margin:0}.checks{border-top:1px solid #e5ecf4;padding-top:18px;margin-top:24px}.checks>p{font-size:13px;color:#627b99;line-height:1.8}.checks article{display:flex;gap:12px;align-items:center;margin:12px 0;font-size:13px}.checks small{font-size:11px;color:#7c8fa9}.grant-row{display:flex;justify-content:space-between;gap:16px;border-bottom:1px solid #e7edf4;padding:20px 0}.grant-row p,.diagnostic-row p{font-size:13px;line-height:1.8;color:#6c809c}.grant-row small,.diagnostic-row small{font-size:11px;color:#8091a8}.grant-row .actions{margin-top:0}.diagnostic-row{padding:16px;border:1px solid #e0e7ef;border-radius:7px;margin:15px 0}dl{display:grid;grid-template-columns:140px minmax(0,1fr);gap:15px;font-size:13px;line-height:1.8}dt{color:#7a8ea8}dd{margin:0;overflow-wrap:anywhere}@media(max-width:850px){.status-card{grid-template-columns:repeat(2,minmax(0,1fr))}.heading,.panel-heading,.grant-row{flex-wrap:wrap}.processing-page{padding:18px 12px}}@media(max-width:600px){.form-grid{grid-template-columns:1fr}.status-card{grid-template-columns:1fr}.panel{padding:18px}.checks article{flex-wrap:wrap}}
</style>
